/*
 * Binance Spot WebSocket API
 * OpenAPI Specifications for the Binance Spot WebSocket API  API documents:   - [Github web-socket-api documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-api.md)   - [General API information for web-socket-api on website](https://developers.binance.com/docs/binance-spot-api-docs/web-socket-api/general-api-information)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.quarkus.spot.model;

import com.binance.connector.client.common.DecimalFormatter;
import com.fasterxml.jackson.annotation.JsonInclude;


import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.stream.Collectors;


@JsonInclude(JsonInclude.Include.NON_NULL)
public class AccountRateLimitsOrdersRequest extends BaseDTO {
    private Double recvWindow;

    public Double getRecvWindow() {
        return recvWindow;
    }
    public void setRecvWindow( Double recvWindow) {
        this.recvWindow = recvWindow;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AccountRateLimitsOrdersRequest accountRateLimitsOrdersRequest =
                (AccountRateLimitsOrdersRequest) o;
        return Objects.equals(this.recvWindow, accountRateLimitsOrdersRequest.recvWindow);
    }

    @Override
    public int hashCode() {
        return Objects.hash(recvWindow);
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();
        Map<String, String> valMap = new TreeMap<String, String>();
        valMap.put("apiKey", getApiKey());
        Double recvWindowValue = getRecvWindow();
        if (recvWindowValue != null) {
            String recvWindowValueAsString =
                    DecimalFormatter.getFormatter().format(recvWindowValue);
            valMap.put("recvWindow", recvWindowValueAsString);
        }

        valMap.put("timestamp", getTimestamp());
        return asciiEncode(
                valMap.keySet().stream()
                        .map(key -> key + "=" + valMap.get(key))
                        .collect(Collectors.joining("&")));
    }
    public static String asciiEncode(String s) {
        return new String(s.getBytes(), StandardCharsets.US_ASCII);
    }
}
