/*
 * Binance Spot WebSocket API
 * OpenAPI Specifications for the Binance Spot WebSocket API  API documents:   - [Github web-socket-api documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-api.md)   - [General API information for web-socket-api on website](https://developers.binance.com/docs/binance-spot-api-docs/web-socket-api/general-api-information)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.quarkus.spot.model;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.stream.Collectors;

public class AccountRateLimitsOrdersResponseResultInner extends BaseDTO {
    private String rateLimitType;
    private String interval;
    private Long intervalNum;
    private Long limit;
    private Long count;

    public String getRateLimitType() {
        return rateLimitType;
    }
    public void setRateLimitType( String rateLimitType) {
        this.rateLimitType = rateLimitType;
    }

    public String getInterval() {
        return interval;
    }
    public void setInterval( String interval) {
        this.interval = interval;
    }

    public Long getIntervalNum() {
        return intervalNum;
    }
    public void setIntervalNum( Long intervalNum) {
        this.intervalNum = intervalNum;
    }

    public Long getLimit() {
        return limit;
    }
    public void setLimit( Long limit) {
        this.limit = limit;
    }

    public Long getCount() {
        return count;
    }
    public void setCount( Long count) {
        this.count = count;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AccountRateLimitsOrdersResponseResultInner accountRateLimitsOrdersResponseResultInner =
                (AccountRateLimitsOrdersResponseResultInner) o;
        return Objects.equals(
                        this.rateLimitType,
                        accountRateLimitsOrdersResponseResultInner.rateLimitType)
                && Objects.equals(
                        this.interval, accountRateLimitsOrdersResponseResultInner.interval)
                && Objects.equals(
                        this.intervalNum, accountRateLimitsOrdersResponseResultInner.intervalNum)
                && Objects.equals(this.limit, accountRateLimitsOrdersResponseResultInner.limit)
                && Objects.equals(this.count, accountRateLimitsOrdersResponseResultInner.count);
    }

    @Override
    public int hashCode() {
        return Objects.hash(rateLimitType, interval, intervalNum, limit, count);
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();
        Map<String, String> valMap = new TreeMap<String, String>();
        valMap.put("apiKey", getApiKey());
        String rateLimitTypeValue = getRateLimitType();
        if (rateLimitTypeValue != null) {
            String rateLimitTypeValueAsString = rateLimitTypeValue.toString();
            valMap.put("rateLimitType", rateLimitTypeValueAsString);
        }
        String intervalValue = getInterval();
        if (intervalValue != null) {
            String intervalValueAsString = intervalValue.toString();
            valMap.put("interval", intervalValueAsString);
        }
        Long intervalNumValue = getIntervalNum();
        if (intervalNumValue != null) {
            String intervalNumValueAsString = intervalNumValue.toString();
            valMap.put("intervalNum", intervalNumValueAsString);
        }
        Long limitValue = getLimit();
        if (limitValue != null) {
            String limitValueAsString = limitValue.toString();
            valMap.put("limit", limitValueAsString);
        }
        Long countValue = getCount();
        if (countValue != null) {
            String countValueAsString = countValue.toString();
            valMap.put("count", countValueAsString);
        }

        valMap.put("timestamp", getTimestamp());
        return asciiEncode(
                valMap.keySet().stream()
                        .map(key -> key + "=" + valMap.get(key))
                        .collect(Collectors.joining("&")));
    }

    public Map<String, Object> toMap() {
        Map<String, Object> valMap = new TreeMap<String, Object>();
        valMap.put("apiKey", getApiKey());
        Object rateLimitTypeValue = getRateLimitType();
        if (rateLimitTypeValue != null) {
            valMap.put("rateLimitType", rateLimitTypeValue);
        }
        Object intervalValue = getInterval();
        if (intervalValue != null) {
            valMap.put("interval", intervalValue);
        }
        Object intervalNumValue = getIntervalNum();
        if (intervalNumValue != null) {
            valMap.put("intervalNum", intervalNumValue);
        }
        Object limitValue = getLimit();
        if (limitValue != null) {
            valMap.put("limit", limitValue);
        }
        Object countValue = getCount();
        if (countValue != null) {
            valMap.put("count", countValue);
        }

        valMap.put("timestamp", getTimestamp());
        return valMap;
    }

    public static String asciiEncode(String s) {
        return new String(s.getBytes(), StandardCharsets.US_ASCII);
    }
}
