/*
 * Binance Spot WebSocket API
 * OpenAPI Specifications for the Binance Spot WebSocket API  API documents:   - [Github web-socket-api documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-api.md)   - [General API information for web-socket-api on website](https://developers.binance.com/docs/binance-spot-api-docs/web-socket-api/general-api-information)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.quarkus.spot.model;

import com.binance.connector.client.common.DecimalFormatter;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.stream.Collectors;


/** AccountStatusRequest */
public class AccountStatusRequest extends BaseDTO {
    private Boolean omitZeroBalances;
    private Double recvWindow;

    public Boolean getOmitZeroBalances() {
        return omitZeroBalances;
    }
    public void setOmitZeroBalances( Boolean omitZeroBalances) {
        this.omitZeroBalances = omitZeroBalances;
    }

    public Double getRecvWindow() {
        return recvWindow;
    }
    public void setRecvWindow( Double recvWindow) {
        this.recvWindow = recvWindow;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AccountStatusRequest accountStatusRequest = (AccountStatusRequest) o;
        return Objects.equals(this.omitZeroBalances, accountStatusRequest.omitZeroBalances)
                && Objects.equals(this.recvWindow, accountStatusRequest.recvWindow);
    }

    @Override
    public int hashCode() {
        return Objects.hash(omitZeroBalances, recvWindow);
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();
        Map<String, String> valMap = new TreeMap<String, String>();
        valMap.put("apiKey", getApiKey());
        Boolean omitZeroBalancesValue = getOmitZeroBalances();
        if (omitZeroBalancesValue != null) {
            String omitZeroBalancesValueAsString = omitZeroBalancesValue.toString();
            valMap.put("omitZeroBalances", omitZeroBalancesValueAsString);
        }
        Double recvWindowValue = getRecvWindow();
        if (recvWindowValue != null) {
            String recvWindowValueAsString =
                    DecimalFormatter.getFormatter().format(recvWindowValue);
            valMap.put("recvWindow", recvWindowValueAsString);
        }

        valMap.put("timestamp", getTimestamp());
        return asciiEncode(
                valMap.keySet().stream()
                        .map(key -> key + "=" + valMap.get(key))
                        .collect(Collectors.joining("&")));
    }

    public Map<String, Object> toMap() {
        Map<String, Object> valMap = new TreeMap<String, Object>();
        valMap.put("apiKey", getApiKey());
        Object omitZeroBalancesValue = getOmitZeroBalances();
        if (omitZeroBalancesValue != null) {
            valMap.put("omitZeroBalances", omitZeroBalancesValue);
        }
        Object recvWindowValue = getRecvWindow();
        if (recvWindowValue != null) {
            valMap.put("recvWindow", recvWindowValue);
        }

        valMap.put("timestamp", getTimestamp());
        return valMap;
    }

    public static String asciiEncode(String s) {
        return new String(s.getBytes(), StandardCharsets.US_ASCII);
    }
}
