/*
 * Binance Spot WebSocket Streams
 * OpenAPI Specifications for the Binance Spot WebSocket Streams  API documents:   - [Github web-socket-streams documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-streams.md)   - [General API information for web-socket-streams on website](https://developers.binance.com/docs/binance-spot-api-docs/web-socket-streams)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.quarkus.spot.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.nio.charset.StandardCharsets;
import java.util.Map;
import java.util.Objects;
import java.util.TreeMap;
import java.util.stream.Collectors;


public class AggTradeResponse extends BaseDTO {
    public static final String SERIALIZED_NAME_E_LOWER_CASE = "e";

    @JsonProperty(SERIALIZED_NAME_E_LOWER_CASE)

    private String eLowerCase;

    public static final String SERIALIZED_NAME_E = "E";

    @JsonProperty(SERIALIZED_NAME_E)

    private Long E;

    public static final String SERIALIZED_NAME_S_LOWER_CASE = "s";

    @JsonProperty(SERIALIZED_NAME_S_LOWER_CASE)
    
    private String sLowerCase;

    public static final String SERIALIZED_NAME_A_LOWER_CASE = "a";

    @JsonProperty(SERIALIZED_NAME_A_LOWER_CASE)
    
    private Long aLowerCase;

    public static final String SERIALIZED_NAME_P_LOWER_CASE = "p";

    @JsonProperty(SERIALIZED_NAME_P_LOWER_CASE)
    
    private String pLowerCase;

    public static final String SERIALIZED_NAME_Q_LOWER_CASE = "q";

    @JsonProperty(SERIALIZED_NAME_Q_LOWER_CASE)
    
    private String qLowerCase;

    public static final String SERIALIZED_NAME_F_LOWER_CASE = "f";

    @JsonProperty(SERIALIZED_NAME_F_LOWER_CASE)
    
    private Long fLowerCase;

    public static final String SERIALIZED_NAME_L_LOWER_CASE = "l";

    @JsonProperty(SERIALIZED_NAME_L_LOWER_CASE)
    
    private Long lLowerCase;

    public static final String SERIALIZED_NAME_T = "T";

    @JsonProperty(SERIALIZED_NAME_T)
    
    private Long T;

    public static final String SERIALIZED_NAME_M_LOWER_CASE = "m";

    @JsonProperty(SERIALIZED_NAME_M_LOWER_CASE)
    
    private Boolean mLowerCase;

    public static final String SERIALIZED_NAME_M = "M";

    @JsonProperty(SERIALIZED_NAME_M)
    
    private Boolean M;

    public String geteLowerCase() {
        return eLowerCase;
    }

    public void seteLowerCase( String eLowerCase) {
        this.eLowerCase = eLowerCase;
    }

    public Long getE() {
        return E;
    }

    public void setE( Long E) {
        this.E = E;
    }

    public AggTradeResponse sLowerCase( String sLowerCase) {
        this.sLowerCase = sLowerCase;
        return this;
    }

    /**
     * Get sLowerCase
     *
     * @return sLowerCase
     */
    
    public String getsLowerCase() {
        return sLowerCase;
    }

    public void setsLowerCase( String sLowerCase) {
        this.sLowerCase = sLowerCase;
    }

    public AggTradeResponse aLowerCase( Long aLowerCase) {
        this.aLowerCase = aLowerCase;
        return this;
    }

    /**
     * Get aLowerCase
     *
     * @return aLowerCase
     */
    
    public Long getaLowerCase() {
        return aLowerCase;
    }

    public void setaLowerCase( Long aLowerCase) {
        this.aLowerCase = aLowerCase;
    }

    public AggTradeResponse pLowerCase( String pLowerCase) {
        this.pLowerCase = pLowerCase;
        return this;
    }

    /**
     * Get pLowerCase
     *
     * @return pLowerCase
     */
    
    public String getpLowerCase() {
        return pLowerCase;
    }

    public void setpLowerCase( String pLowerCase) {
        this.pLowerCase = pLowerCase;
    }

    public AggTradeResponse qLowerCase( String qLowerCase) {
        this.qLowerCase = qLowerCase;
        return this;
    }

    /**
     * Get qLowerCase
     *
     * @return qLowerCase
     */
    
    public String getqLowerCase() {
        return qLowerCase;
    }

    public void setqLowerCase( String qLowerCase) {
        this.qLowerCase = qLowerCase;
    }

    public AggTradeResponse fLowerCase( Long fLowerCase) {
        this.fLowerCase = fLowerCase;
        return this;
    }

    /**
     * Get fLowerCase
     *
     * @return fLowerCase
     */
    
    public Long getfLowerCase() {
        return fLowerCase;
    }

    public void setfLowerCase( Long fLowerCase) {
        this.fLowerCase = fLowerCase;
    }

    public AggTradeResponse lLowerCase( Long lLowerCase) {
        this.lLowerCase = lLowerCase;
        return this;
    }

    /**
     * Get lLowerCase
     *
     * @return lLowerCase
     */
    
    public Long getlLowerCase() {
        return lLowerCase;
    }

    public void setlLowerCase( Long lLowerCase) {
        this.lLowerCase = lLowerCase;
    }

    public AggTradeResponse T( Long T) {
        this.T = T;
        return this;
    }

    /**
     * Get T
     *
     * @return T
     */
    
    public Long getT() {
        return T;
    }

    public void setT( Long T) {
        this.T = T;
    }

    public AggTradeResponse mLowerCase( Boolean mLowerCase) {
        this.mLowerCase = mLowerCase;
        return this;
    }

    /**
     * Get mLowerCase
     *
     * @return mLowerCase
     */
    
    public Boolean getmLowerCase() {
        return mLowerCase;
    }

    public void setmLowerCase( Boolean mLowerCase) {
        this.mLowerCase = mLowerCase;
    }

    public AggTradeResponse M( Boolean M) {
        this.M = M;
        return this;
    }

    /**
     * Get M
     *
     * @return M
     */
    
    public Boolean getM() {
        return M;
    }

    public void setM( Boolean M) {
        this.M = M;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AggTradeResponse aggTradeResponse = (AggTradeResponse) o;
        return Objects.equals(this.eLowerCase, aggTradeResponse.eLowerCase)
                && Objects.equals(this.E, aggTradeResponse.E)
                && Objects.equals(this.sLowerCase, aggTradeResponse.sLowerCase)
                && Objects.equals(this.aLowerCase, aggTradeResponse.aLowerCase)
                && Objects.equals(this.pLowerCase, aggTradeResponse.pLowerCase)
                && Objects.equals(this.qLowerCase, aggTradeResponse.qLowerCase)
                && Objects.equals(this.fLowerCase, aggTradeResponse.fLowerCase)
                && Objects.equals(this.lLowerCase, aggTradeResponse.lLowerCase)
                && Objects.equals(this.T, aggTradeResponse.T)
                && Objects.equals(this.mLowerCase, aggTradeResponse.mLowerCase)
                && Objects.equals(this.M, aggTradeResponse.M);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                eLowerCase,
                E,
                sLowerCase,
                aLowerCase,
                pLowerCase,
                qLowerCase,
                fLowerCase,
                lLowerCase,
                T,
                mLowerCase,
                M);
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();
        Map<String, String> valMap = new TreeMap<String, String>();
        valMap.put("apiKey", getApiKey());
        String eLowerCaseValue = geteLowerCase();
        if (eLowerCaseValue != null) {
            String eLowerCaseValueAsString = eLowerCaseValue.toString();
            valMap.put("eLowerCase", eLowerCaseValueAsString);
        }
        Long EValue = getE();
        if (EValue != null) {
            String EValueAsString = EValue.toString();
            valMap.put("E", EValueAsString);
        }
        String sLowerCaseValue = getsLowerCase();
        if (sLowerCaseValue != null) {
            String sLowerCaseValueAsString = sLowerCaseValue.toString();
            valMap.put("sLowerCase", sLowerCaseValueAsString);
        }
        Long aLowerCaseValue = getaLowerCase();
        if (aLowerCaseValue != null) {
            String aLowerCaseValueAsString = aLowerCaseValue.toString();
            valMap.put("aLowerCase", aLowerCaseValueAsString);
        }
        String pLowerCaseValue = getpLowerCase();
        if (pLowerCaseValue != null) {
            String pLowerCaseValueAsString = pLowerCaseValue.toString();
            valMap.put("pLowerCase", pLowerCaseValueAsString);
        }
        String qLowerCaseValue = getqLowerCase();
        if (qLowerCaseValue != null) {
            String qLowerCaseValueAsString = qLowerCaseValue.toString();
            valMap.put("qLowerCase", qLowerCaseValueAsString);
        }
        Long fLowerCaseValue = getfLowerCase();
        if (fLowerCaseValue != null) {
            String fLowerCaseValueAsString = fLowerCaseValue.toString();
            valMap.put("fLowerCase", fLowerCaseValueAsString);
        }
        Long lLowerCaseValue = getlLowerCase();
        if (lLowerCaseValue != null) {
            String lLowerCaseValueAsString = lLowerCaseValue.toString();
            valMap.put("lLowerCase", lLowerCaseValueAsString);
        }
        Long TValue = getT();
        if (TValue != null) {
            String TValueAsString = TValue.toString();
            valMap.put("T", TValueAsString);
        }
        Boolean mLowerCaseValue = getmLowerCase();
        if (mLowerCaseValue != null) {
            String mLowerCaseValueAsString = mLowerCaseValue.toString();
            valMap.put("mLowerCase", mLowerCaseValueAsString);
        }
        Boolean MValue = getM();
        if (MValue != null) {
            String MValueAsString = MValue.toString();
            valMap.put("M", MValueAsString);
        }

        valMap.put("timestamp", getTimestamp());
        return asciiEncode(
                valMap.keySet().stream()
                        .map(key -> key + "=" + valMap.get(key))
                        .collect(Collectors.joining("&")));
    }

    public static String asciiEncode(String s) {
        return new String(s.getBytes(), StandardCharsets.US_ASCII);
    }
}
