/*
 * Binance Spot WebSocket API
 * OpenAPI Specifications for the Binance Spot WebSocket API  API documents:   - [Github web-socket-api documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-api.md)   - [General API information for web-socket-api on website](https://developers.binance.com/docs/binance-spot-api-docs/web-socket-api/general-api-information)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.quarkus.spot.model;

import com.binance.connector.client.common.DecimalFormatter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.stream.Collectors;

@JsonInclude(JsonInclude.Include.NON_NULL)
public class AllOrderListsRequest extends BaseDTO {
    public static final String SERIALIZED_NAME_FROM_ID = "fromId";

    @JsonProperty(SERIALIZED_NAME_FROM_ID)
    
    private Integer fromId;

    public static final String SERIALIZED_NAME_START_TIME = "startTime";

    @JsonProperty(SERIALIZED_NAME_START_TIME)
    
    private Long startTime;

    public static final String SERIALIZED_NAME_END_TIME = "endTime";

    @JsonProperty(SERIALIZED_NAME_END_TIME)
    
    private Long endTime;

    public static final String SERIALIZED_NAME_LIMIT = "limit";

    @JsonProperty(SERIALIZED_NAME_LIMIT)
    
    private Integer limit;

    public static final String SERIALIZED_NAME_RECV_WINDOW = "recvWindow";

    @JsonProperty(SERIALIZED_NAME_RECV_WINDOW)
    
    private Long recvWindow;

    public AllOrderListsRequest() {}

    public AllOrderListsRequest fromId( Integer fromId) {
        this.fromId = fromId;
        return this;
    }

    /**
     * Get fromId
     *
     * @return fromId
     */
    
    public Integer getFromId() {
        return fromId;
    }

    public void setFromId( Integer fromId) {
        this.fromId = fromId;
    }

    public AllOrderListsRequest startTime( Long startTime) {
        this.startTime = startTime;
        return this;
    }

    /**
     * Get startTime
     *
     * @return startTime
     */
    
    public Long getStartTime() {
        return startTime;
    }

    public void setStartTime( Long startTime) {
        this.startTime = startTime;
    }

    public AllOrderListsRequest endTime( Long endTime) {
        this.endTime = endTime;
        return this;
    }

    /**
     * Get endTime
     *
     * @return endTime
     */
    
    public Long getEndTime() {
        return endTime;
    }

    public void setEndTime( Long endTime) {
        this.endTime = endTime;
    }

    public AllOrderListsRequest limit( Integer limit) {
        this.limit = limit;
        return this;
    }

    /**
     * Get limit
     *
     * @return limit
     */
    
    public Integer getLimit() {
        return limit;
    }

    public void setLimit( Integer limit) {
        this.limit = limit;
    }

    public AllOrderListsRequest recvWindow( Long recvWindow) {
        this.recvWindow = recvWindow;
        return this;
    }

    /**
     * Get recvWindow
     *
     * @return recvWindow
     */
    public Long getRecvWindow() {
        return recvWindow;
    }

    public void setRecvWindow( Long recvWindow) {
        this.recvWindow = recvWindow;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AllOrderListsRequest allOrderListsRequest = (AllOrderListsRequest) o;
        return Objects.equals(this.fromId, allOrderListsRequest.fromId)
                && Objects.equals(this.startTime, allOrderListsRequest.startTime)
                && Objects.equals(this.endTime, allOrderListsRequest.endTime)
                && Objects.equals(this.limit, allOrderListsRequest.limit)
                && Objects.equals(this.recvWindow, allOrderListsRequest.recvWindow);
    }

    @Override
    public int hashCode() {
        return Objects.hash(fromId, startTime, endTime, limit, recvWindow);
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();
        Map<String, String> valMap = new TreeMap<String, String>();
        valMap.put("apiKey", getApiKey());
        Integer fromIdValue = getFromId();
        if (fromIdValue != null) {
            String fromIdValueAsString = fromIdValue.toString();
            valMap.put("fromId", fromIdValueAsString);
        }
        Long startTimeValue = getStartTime();
        if (startTimeValue != null) {
            String startTimeValueAsString = startTimeValue.toString();
            valMap.put("startTime", startTimeValueAsString);
        }
        Long endTimeValue = getEndTime();
        if (endTimeValue != null) {
            String endTimeValueAsString = endTimeValue.toString();
            valMap.put("endTime", endTimeValueAsString);
        }
        Integer limitValue = getLimit();
        if (limitValue != null) {
            String limitValueAsString = limitValue.toString();
            valMap.put("limit", limitValueAsString);
        }
        Long recvWindowValue = getRecvWindow();
        if (recvWindowValue != null) {
            String recvWindowValueAsString =
                    DecimalFormatter.getFormatter().format(recvWindowValue);
            valMap.put("recvWindow", recvWindowValueAsString);
        }

        valMap.put("timestamp", getTimestamp());
        return asciiEncode(
                valMap.keySet().stream()
                        .map(key -> key + "=" + valMap.get(key))
                        .collect(Collectors.joining("&")));
    }

    public static String asciiEncode(String s) {
        return new String(s.getBytes(), StandardCharsets.US_ASCII);
    }

}
