/*
 * Binance Spot WebSocket Streams
 * OpenAPI Specifications for the Binance Spot WebSocket Streams  API documents:   - [Github web-socket-streams documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-streams.md)   - [General API information for web-socket-streams on website](https://developers.binance.com/docs/binance-spot-api-docs/web-socket-streams)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.quarkus.spot.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.stream.Collectors;

public class AllTickerResponseInner extends BaseDTO {
    public static final String SERIALIZED_NAME_E_LOWER_CASE = "e";

    @JsonProperty(SERIALIZED_NAME_E_LOWER_CASE)
    
    private String eLowerCase;

    public static final String SERIALIZED_NAME_E = "E";

    @JsonProperty(SERIALIZED_NAME_E)
    
    private Long E;

    public static final String SERIALIZED_NAME_S_LOWER_CASE = "s";

    @JsonProperty(SERIALIZED_NAME_S_LOWER_CASE)
    
    private String sLowerCase;

    public static final String SERIALIZED_NAME_P_LOWER_CASE = "p";

    @JsonProperty(SERIALIZED_NAME_P_LOWER_CASE)
    
    private String pLowerCase;

    public static final String SERIALIZED_NAME_P = "P";

    @JsonProperty(SERIALIZED_NAME_P)
    
    private String P;

    public static final String SERIALIZED_NAME_W_LOWER_CASE = "w";

    @JsonProperty(SERIALIZED_NAME_W_LOWER_CASE)
    
    private String wLowerCase;

    public static final String SERIALIZED_NAME_X_LOWER_CASE = "x";

    @JsonProperty(SERIALIZED_NAME_X_LOWER_CASE)
    
    private String xLowerCase;

    public static final String SERIALIZED_NAME_C_LOWER_CASE = "c";

    @JsonProperty(SERIALIZED_NAME_C_LOWER_CASE)
    
    private String cLowerCase;

    public static final String SERIALIZED_NAME_Q = "Q";

    @JsonProperty(SERIALIZED_NAME_Q)
    
    private String Q;

    public static final String SERIALIZED_NAME_B_LOWER_CASE = "b";

    @JsonProperty(SERIALIZED_NAME_B_LOWER_CASE)
    
    private String bLowerCase;

    public static final String SERIALIZED_NAME_B = "B";

    @JsonProperty(SERIALIZED_NAME_B)
    
    private String B;

    public static final String SERIALIZED_NAME_A_LOWER_CASE = "a";

    @JsonProperty(SERIALIZED_NAME_A_LOWER_CASE)
    
    private String aLowerCase;

    public static final String SERIALIZED_NAME_A = "A";

    @JsonProperty(SERIALIZED_NAME_A)
    
    private String A;

    public static final String SERIALIZED_NAME_O_LOWER_CASE = "o";

    @JsonProperty(SERIALIZED_NAME_O_LOWER_CASE)
    
    private String oLowerCase;

    public static final String SERIALIZED_NAME_H_LOWER_CASE = "h";

    @JsonProperty(SERIALIZED_NAME_H_LOWER_CASE)
    
    private String hLowerCase;

    public static final String SERIALIZED_NAME_L_LOWER_CASE = "l";

    @JsonProperty(SERIALIZED_NAME_L_LOWER_CASE)
    
    private String lLowerCase;

    public static final String SERIALIZED_NAME_V_LOWER_CASE = "v";

    @JsonProperty(SERIALIZED_NAME_V_LOWER_CASE)
    
    private String vLowerCase;

    public static final String SERIALIZED_NAME_Q_LOWER_CASE = "q";

    @JsonProperty(SERIALIZED_NAME_Q_LOWER_CASE)
    
    private String qLowerCase;

    public static final String SERIALIZED_NAME_O = "O";

    @JsonProperty(SERIALIZED_NAME_O)
    
    private Long O;

    public static final String SERIALIZED_NAME_C = "C";

    @JsonProperty(SERIALIZED_NAME_C)
    
    private Long C;

    public static final String SERIALIZED_NAME_F = "F";

    @JsonProperty(SERIALIZED_NAME_F)
    
    private Long F;

    public static final String SERIALIZED_NAME_L = "L";

    @JsonProperty(SERIALIZED_NAME_L)
    
    private Long L;

    public static final String SERIALIZED_NAME_N_LOWER_CASE = "n";

    @JsonProperty(SERIALIZED_NAME_N_LOWER_CASE)
    
    private Long nLowerCase;

    public AllTickerResponseInner() {}

    public AllTickerResponseInner eLowerCase( String eLowerCase) {
        this.eLowerCase = eLowerCase;
        return this;
    }

    /**
     * Get eLowerCase
     *
     * @return eLowerCase
     */
    
    public String geteLowerCase() {
        return eLowerCase;
    }

    public void seteLowerCase( String eLowerCase) {
        this.eLowerCase = eLowerCase;
    }

    public AllTickerResponseInner E( Long E) {
        this.E = E;
        return this;
    }

    /**
     * Get E
     *
     * @return E
     */
    
    public Long getE() {
        return E;
    }

    public void setE( Long E) {
        this.E = E;
    }

    public AllTickerResponseInner sLowerCase( String sLowerCase) {
        this.sLowerCase = sLowerCase;
        return this;
    }

    /**
     * Get sLowerCase
     *
     * @return sLowerCase
     */
    
    public String getsLowerCase() {
        return sLowerCase;
    }

    public void setsLowerCase( String sLowerCase) {
        this.sLowerCase = sLowerCase;
    }

    public AllTickerResponseInner pLowerCase( String pLowerCase) {
        this.pLowerCase = pLowerCase;
        return this;
    }

    /**
     * Get pLowerCase
     *
     * @return pLowerCase
     */
    
    public String getpLowerCase() {
        return pLowerCase;
    }

    public void setpLowerCase( String pLowerCase) {
        this.pLowerCase = pLowerCase;
    }

    public AllTickerResponseInner P( String P) {
        this.P = P;
        return this;
    }

    /**
     * Get P
     *
     * @return P
     */
    
    public String getP() {
        return P;
    }

    public void setP( String P) {
        this.P = P;
    }

    public AllTickerResponseInner wLowerCase( String wLowerCase) {
        this.wLowerCase = wLowerCase;
        return this;
    }

    /**
     * Get wLowerCase
     *
     * @return wLowerCase
     */
    
    public String getwLowerCase() {
        return wLowerCase;
    }

    public void setwLowerCase( String wLowerCase) {
        this.wLowerCase = wLowerCase;
    }

    public AllTickerResponseInner xLowerCase( String xLowerCase) {
        this.xLowerCase = xLowerCase;
        return this;
    }

    /**
     * Get xLowerCase
     *
     * @return xLowerCase
     */
    
    public String getxLowerCase() {
        return xLowerCase;
    }

    public void setxLowerCase( String xLowerCase) {
        this.xLowerCase = xLowerCase;
    }

    public AllTickerResponseInner cLowerCase( String cLowerCase) {
        this.cLowerCase = cLowerCase;
        return this;
    }

    /**
     * Get cLowerCase
     *
     * @return cLowerCase
     */
    
    public String getcLowerCase() {
        return cLowerCase;
    }

    public void setcLowerCase( String cLowerCase) {
        this.cLowerCase = cLowerCase;
    }

    public AllTickerResponseInner Q( String Q) {
        this.Q = Q;
        return this;
    }

    /**
     * Get Q
     *
     * @return Q
     */
    
    public String getQ() {
        return Q;
    }

    public void setQ( String Q) {
        this.Q = Q;
    }

    public AllTickerResponseInner bLowerCase( String bLowerCase) {
        this.bLowerCase = bLowerCase;
        return this;
    }

    /**
     * Get bLowerCase
     *
     * @return bLowerCase
     */
    
    public String getbLowerCase() {
        return bLowerCase;
    }

    public void setbLowerCase( String bLowerCase) {
        this.bLowerCase = bLowerCase;
    }

    public AllTickerResponseInner B( String B) {
        this.B = B;
        return this;
    }

    /**
     * Get B
     *
     * @return B
     */
    
    public String getB() {
        return B;
    }

    public void setB( String B) {
        this.B = B;
    }

    public AllTickerResponseInner aLowerCase( String aLowerCase) {
        this.aLowerCase = aLowerCase;
        return this;
    }

    /**
     * Get aLowerCase
     *
     * @return aLowerCase
     */
    
    public String getaLowerCase() {
        return aLowerCase;
    }

    public void setaLowerCase( String aLowerCase) {
        this.aLowerCase = aLowerCase;
    }

    public AllTickerResponseInner A( String A) {
        this.A = A;
        return this;
    }

    /**
     * Get A
     *
     * @return A
     */
    
    public String getA() {
        return A;
    }

    public void setA( String A) {
        this.A = A;
    }

    public AllTickerResponseInner oLowerCase( String oLowerCase) {
        this.oLowerCase = oLowerCase;
        return this;
    }

    /**
     * Get oLowerCase
     *
     * @return oLowerCase
     */
    
    public String getoLowerCase() {
        return oLowerCase;
    }

    public void setoLowerCase( String oLowerCase) {
        this.oLowerCase = oLowerCase;
    }

    public AllTickerResponseInner hLowerCase( String hLowerCase) {
        this.hLowerCase = hLowerCase;
        return this;
    }

    /**
     * Get hLowerCase
     *
     * @return hLowerCase
     */
    
    public String gethLowerCase() {
        return hLowerCase;
    }

    public void sethLowerCase( String hLowerCase) {
        this.hLowerCase = hLowerCase;
    }

    public AllTickerResponseInner lLowerCase( String lLowerCase) {
        this.lLowerCase = lLowerCase;
        return this;
    }

    /**
     * Get lLowerCase
     *
     * @return lLowerCase
     */
    
    public String getlLowerCase() {
        return lLowerCase;
    }

    public void setlLowerCase( String lLowerCase) {
        this.lLowerCase = lLowerCase;
    }

    public AllTickerResponseInner vLowerCase( String vLowerCase) {
        this.vLowerCase = vLowerCase;
        return this;
    }

    /**
     * Get vLowerCase
     *
     * @return vLowerCase
     */
    
    public String getvLowerCase() {
        return vLowerCase;
    }

    public void setvLowerCase( String vLowerCase) {
        this.vLowerCase = vLowerCase;
    }

    public AllTickerResponseInner qLowerCase( String qLowerCase) {
        this.qLowerCase = qLowerCase;
        return this;
    }

    /**
     * Get qLowerCase
     *
     * @return qLowerCase
     */
    
    public String getqLowerCase() {
        return qLowerCase;
    }

    public void setqLowerCase( String qLowerCase) {
        this.qLowerCase = qLowerCase;
    }

    public AllTickerResponseInner O( Long O) {
        this.O = O;
        return this;
    }

    /**
     * Get O
     *
     * @return O
     */
    
    public Long getO() {
        return O;
    }

    public void setO( Long O) {
        this.O = O;
    }

    public AllTickerResponseInner C( Long C) {
        this.C = C;
        return this;
    }

    /**
     * Get C
     *
     * @return C
     */
    
    public Long getC() {
        return C;
    }

    public void setC( Long C) {
        this.C = C;
    }

    public AllTickerResponseInner F( Long F) {
        this.F = F;
        return this;
    }

    /**
     * Get F
     *
     * @return F
     */
    
    public Long getF() {
        return F;
    }

    public void setF( Long F) {
        this.F = F;
    }

    public AllTickerResponseInner L( Long L) {
        this.L = L;
        return this;
    }

    /**
     * Get L
     *
     * @return L
     */
    
    public Long getL() {
        return L;
    }

    public void setL( Long L) {
        this.L = L;
    }

    public AllTickerResponseInner nLowerCase( Long nLowerCase) {
        this.nLowerCase = nLowerCase;
        return this;
    }

    /**
     * Get nLowerCase
     *
     * @return nLowerCase
     */
    
    public Long getnLowerCase() {
        return nLowerCase;
    }

    public void setnLowerCase( Long nLowerCase) {
        this.nLowerCase = nLowerCase;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AllTickerResponseInner allTickerResponseInner = (AllTickerResponseInner) o;
        return Objects.equals(this.eLowerCase, allTickerResponseInner.eLowerCase)
                && Objects.equals(this.E, allTickerResponseInner.E)
                && Objects.equals(this.sLowerCase, allTickerResponseInner.sLowerCase)
                && Objects.equals(this.pLowerCase, allTickerResponseInner.pLowerCase)
                && Objects.equals(this.P, allTickerResponseInner.P)
                && Objects.equals(this.wLowerCase, allTickerResponseInner.wLowerCase)
                && Objects.equals(this.xLowerCase, allTickerResponseInner.xLowerCase)
                && Objects.equals(this.cLowerCase, allTickerResponseInner.cLowerCase)
                && Objects.equals(this.Q, allTickerResponseInner.Q)
                && Objects.equals(this.bLowerCase, allTickerResponseInner.bLowerCase)
                && Objects.equals(this.B, allTickerResponseInner.B)
                && Objects.equals(this.aLowerCase, allTickerResponseInner.aLowerCase)
                && Objects.equals(this.A, allTickerResponseInner.A)
                && Objects.equals(this.oLowerCase, allTickerResponseInner.oLowerCase)
                && Objects.equals(this.hLowerCase, allTickerResponseInner.hLowerCase)
                && Objects.equals(this.lLowerCase, allTickerResponseInner.lLowerCase)
                && Objects.equals(this.vLowerCase, allTickerResponseInner.vLowerCase)
                && Objects.equals(this.qLowerCase, allTickerResponseInner.qLowerCase)
                && Objects.equals(this.O, allTickerResponseInner.O)
                && Objects.equals(this.C, allTickerResponseInner.C)
                && Objects.equals(this.F, allTickerResponseInner.F)
                && Objects.equals(this.L, allTickerResponseInner.L)
                && Objects.equals(this.nLowerCase, allTickerResponseInner.nLowerCase);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                eLowerCase,
                E,
                sLowerCase,
                pLowerCase,
                P,
                wLowerCase,
                xLowerCase,
                cLowerCase,
                Q,
                bLowerCase,
                B,
                aLowerCase,
                A,
                oLowerCase,
                hLowerCase,
                lLowerCase,
                vLowerCase,
                qLowerCase,
                O,
                C,
                F,
                L,
                nLowerCase);
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();
        Map<String, String> valMap = new TreeMap<String, String>();
        valMap.put("apiKey", getApiKey());
        String eLowerCaseValue = geteLowerCase();
        if (eLowerCaseValue != null) {
            String eLowerCaseValueAsString = eLowerCaseValue.toString();
            valMap.put("eLowerCase", eLowerCaseValueAsString);
        }
        Long EValue = getE();
        if (EValue != null) {
            String EValueAsString = EValue.toString();
            valMap.put("E", EValueAsString);
        }
        String sLowerCaseValue = getsLowerCase();
        if (sLowerCaseValue != null) {
            String sLowerCaseValueAsString = sLowerCaseValue.toString();
            valMap.put("sLowerCase", sLowerCaseValueAsString);
        }
        String pLowerCaseValue = getpLowerCase();
        if (pLowerCaseValue != null) {
            String pLowerCaseValueAsString = pLowerCaseValue.toString();
            valMap.put("pLowerCase", pLowerCaseValueAsString);
        }
        String PValue = getP();
        if (PValue != null) {
            String PValueAsString = PValue.toString();
            valMap.put("P", PValueAsString);
        }
        String wLowerCaseValue = getwLowerCase();
        if (wLowerCaseValue != null) {
            String wLowerCaseValueAsString = wLowerCaseValue.toString();
            valMap.put("wLowerCase", wLowerCaseValueAsString);
        }
        String xLowerCaseValue = getxLowerCase();
        if (xLowerCaseValue != null) {
            String xLowerCaseValueAsString = xLowerCaseValue.toString();
            valMap.put("xLowerCase", xLowerCaseValueAsString);
        }
        String cLowerCaseValue = getcLowerCase();
        if (cLowerCaseValue != null) {
            String cLowerCaseValueAsString = cLowerCaseValue.toString();
            valMap.put("cLowerCase", cLowerCaseValueAsString);
        }
        String QValue = getQ();
        if (QValue != null) {
            String QValueAsString = QValue.toString();
            valMap.put("Q", QValueAsString);
        }
        String bLowerCaseValue = getbLowerCase();
        if (bLowerCaseValue != null) {
            String bLowerCaseValueAsString = bLowerCaseValue.toString();
            valMap.put("bLowerCase", bLowerCaseValueAsString);
        }
        String BValue = getB();
        if (BValue != null) {
            String BValueAsString = BValue.toString();
            valMap.put("B", BValueAsString);
        }
        String aLowerCaseValue = getaLowerCase();
        if (aLowerCaseValue != null) {
            String aLowerCaseValueAsString = aLowerCaseValue.toString();
            valMap.put("aLowerCase", aLowerCaseValueAsString);
        }
        String AValue = getA();
        if (AValue != null) {
            String AValueAsString = AValue.toString();
            valMap.put("A", AValueAsString);
        }
        String oLowerCaseValue = getoLowerCase();
        if (oLowerCaseValue != null) {
            String oLowerCaseValueAsString = oLowerCaseValue.toString();
            valMap.put("oLowerCase", oLowerCaseValueAsString);
        }
        String hLowerCaseValue = gethLowerCase();
        if (hLowerCaseValue != null) {
            String hLowerCaseValueAsString = hLowerCaseValue.toString();
            valMap.put("hLowerCase", hLowerCaseValueAsString);
        }
        String lLowerCaseValue = getlLowerCase();
        if (lLowerCaseValue != null) {
            String lLowerCaseValueAsString = lLowerCaseValue.toString();
            valMap.put("lLowerCase", lLowerCaseValueAsString);
        }
        String vLowerCaseValue = getvLowerCase();
        if (vLowerCaseValue != null) {
            String vLowerCaseValueAsString = vLowerCaseValue.toString();
            valMap.put("vLowerCase", vLowerCaseValueAsString);
        }
        String qLowerCaseValue = getqLowerCase();
        if (qLowerCaseValue != null) {
            String qLowerCaseValueAsString = qLowerCaseValue.toString();
            valMap.put("qLowerCase", qLowerCaseValueAsString);
        }
        Long OValue = getO();
        if (OValue != null) {
            String OValueAsString = OValue.toString();
            valMap.put("O", OValueAsString);
        }
        Long CValue = getC();
        if (CValue != null) {
            String CValueAsString = CValue.toString();
            valMap.put("C", CValueAsString);
        }
        Long FValue = getF();
        if (FValue != null) {
            String FValueAsString = FValue.toString();
            valMap.put("F", FValueAsString);
        }
        Long LValue = getL();
        if (LValue != null) {
            String LValueAsString = LValue.toString();
            valMap.put("L", LValueAsString);
        }
        Long nLowerCaseValue = getnLowerCase();
        if (nLowerCaseValue != null) {
            String nLowerCaseValueAsString = nLowerCaseValue.toString();
            valMap.put("nLowerCase", nLowerCaseValueAsString);
        }

        valMap.put("timestamp", getTimestamp());
        return asciiEncode(
                valMap.keySet().stream()
                        .map(key -> key + "=" + valMap.get(key))
                        .collect(Collectors.joining("&")));
    }

    public static String asciiEncode(String s) {
        return new String(s.getBytes(), StandardCharsets.US_ASCII);
    }
}
