/*
 * Binance Spot WebSocket API
 * OpenAPI Specifications for the Binance Spot WebSocket API  API documents:   - [Github web-socket-api documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-api.md)   - [General API information for web-socket-api on website](https://developers.binance.com/docs/binance-spot-api-docs/web-socket-api/general-api-information)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.quarkus.spot.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.stream.Collectors;

public class AvgPriceResponseResult extends BaseDTO {
    public static final String SERIALIZED_NAME_MINS = "mins";

    @JsonProperty(SERIALIZED_NAME_MINS)
    
    private Long mins;

    public static final String SERIALIZED_NAME_PRICE = "price";

    @JsonProperty(SERIALIZED_NAME_PRICE)
    
    private String price;

    public static final String SERIALIZED_NAME_CLOSE_TIME = "closeTime";

    @JsonProperty(SERIALIZED_NAME_CLOSE_TIME)
    
    private Long closeTime;

    public AvgPriceResponseResult() {}

    public AvgPriceResponseResult mins( Long mins) {
        this.mins = mins;
        return this;
    }

    /**
     * Get mins
     *
     * @return mins
     */
    
    public Long getMins() {
        return mins;
    }

    public void setMins( Long mins) {
        this.mins = mins;
    }

    public AvgPriceResponseResult price( String price) {
        this.price = price;
        return this;
    }

    /**
     * Get price
     *
     * @return price
     */
    
    public String getPrice() {
        return price;
    }

    public void setPrice( String price) {
        this.price = price;
    }

    public AvgPriceResponseResult closeTime( Long closeTime) {
        this.closeTime = closeTime;
        return this;
    }

    /**
     * Get closeTime
     *
     * @return closeTime
     */
    
    public Long getCloseTime() {
        return closeTime;
    }

    public void setCloseTime( Long closeTime) {
        this.closeTime = closeTime;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AvgPriceResponseResult avgPriceResponseResult = (AvgPriceResponseResult) o;
        return Objects.equals(this.mins, avgPriceResponseResult.mins)
                && Objects.equals(this.price, avgPriceResponseResult.price)
                && Objects.equals(this.closeTime, avgPriceResponseResult.closeTime);
    }

    @Override
    public int hashCode() {
        return Objects.hash(mins, price, closeTime);
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();
        Map<String, String> valMap = new TreeMap<String, String>();
        valMap.put("apiKey", getApiKey());
        Long minsValue = getMins();
        if (minsValue != null) {
            String minsValueAsString = minsValue.toString();
            valMap.put("mins", minsValueAsString);
        }
        String priceValue = getPrice();
        if (priceValue != null) {
            String priceValueAsString = priceValue.toString();
            valMap.put("price", priceValueAsString);
        }
        Long closeTimeValue = getCloseTime();
        if (closeTimeValue != null) {
            String closeTimeValueAsString = closeTimeValue.toString();
            valMap.put("closeTime", closeTimeValueAsString);
        }

        valMap.put("timestamp", getTimestamp());
        return asciiEncode(
                valMap.keySet().stream()
                        .map(key -> key + "=" + valMap.get(key))
                        .collect(Collectors.joining("&")));
    }

    public Map<String, Object> toMap() {
        Map<String, Object> valMap = new TreeMap<String, Object>();
        valMap.put("apiKey", getApiKey());
        Object minsValue = getMins();
        if (minsValue != null) {
            valMap.put("mins", minsValue);
        }
        Object priceValue = getPrice();
        if (priceValue != null) {
            valMap.put("price", priceValue);
        }
        Object closeTimeValue = getCloseTime();
        if (closeTimeValue != null) {
            valMap.put("closeTime", closeTimeValue);
        }

        valMap.put("timestamp", getTimestamp());
        return valMap;
    }

    public static String asciiEncode(String s) {
        return new String(s.getBytes(), StandardCharsets.US_ASCII);
    }

}
