/*
 * Binance Spot WebSocket Streams
 * OpenAPI Specifications for the Binance Spot WebSocket Streams  API documents:   - [Github web-socket-streams documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-streams.md)   - [General API information for web-socket-streams on website](https://developers.binance.com/docs/binance-spot-api-docs/web-socket-streams)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.quarkus.spot.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.stream.Collectors;

public class BookTickerResponse extends BaseDTO {
    public static final String SERIALIZED_NAME_U_LOWER_CASE = "u";

    @JsonProperty(SERIALIZED_NAME_U_LOWER_CASE)
    
    private Long uLowerCase;

    public static final String SERIALIZED_NAME_S_LOWER_CASE = "s";

    @JsonProperty(SERIALIZED_NAME_S_LOWER_CASE)
    
    private String sLowerCase;

    public static final String SERIALIZED_NAME_B_LOWER_CASE = "b";

    @JsonProperty(SERIALIZED_NAME_B_LOWER_CASE)
    
    private String bLowerCase;

    public static final String SERIALIZED_NAME_B = "B";

    @JsonProperty(SERIALIZED_NAME_B)
    
    private String B;

    public static final String SERIALIZED_NAME_A_LOWER_CASE = "a";

    @JsonProperty(SERIALIZED_NAME_A_LOWER_CASE)
    
    private String aLowerCase;

    public static final String SERIALIZED_NAME_A = "A";

    @JsonProperty(SERIALIZED_NAME_A)
    
    private String A;

    public BookTickerResponse() {}

    public BookTickerResponse uLowerCase( Long uLowerCase) {
        this.uLowerCase = uLowerCase;
        return this;
    }

    /**
     * Get uLowerCase
     *
     * @return uLowerCase
     */
    
    public Long getuLowerCase() {
        return uLowerCase;
    }

    public void setuLowerCase( Long uLowerCase) {
        this.uLowerCase = uLowerCase;
    }

    public BookTickerResponse sLowerCase( String sLowerCase) {
        this.sLowerCase = sLowerCase;
        return this;
    }

    /**
     * Get sLowerCase
     *
     * @return sLowerCase
     */
    
    public String getsLowerCase() {
        return sLowerCase;
    }

    public void setsLowerCase( String sLowerCase) {
        this.sLowerCase = sLowerCase;
    }

    public BookTickerResponse bLowerCase( String bLowerCase) {
        this.bLowerCase = bLowerCase;
        return this;
    }

    /**
     * Get bLowerCase
     *
     * @return bLowerCase
     */
    
    public String getbLowerCase() {
        return bLowerCase;
    }

    public void setbLowerCase( String bLowerCase) {
        this.bLowerCase = bLowerCase;
    }

    public BookTickerResponse B( String B) {
        this.B = B;
        return this;
    }

    /**
     * Get B
     *
     * @return B
     */
    
    public String getB() {
        return B;
    }

    public void setB( String B) {
        this.B = B;
    }

    public BookTickerResponse aLowerCase( String aLowerCase) {
        this.aLowerCase = aLowerCase;
        return this;
    }

    /**
     * Get aLowerCase
     *
     * @return aLowerCase
     */
    
    public String getaLowerCase() {
        return aLowerCase;
    }

    public void setaLowerCase( String aLowerCase) {
        this.aLowerCase = aLowerCase;
    }

    public BookTickerResponse A( String A) {
        this.A = A;
        return this;
    }

    /**
     * Get A
     *
     * @return A
     */
    
    public String getA() {
        return A;
    }

    public void setA( String A) {
        this.A = A;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        BookTickerResponse bookTickerResponse = (BookTickerResponse) o;
        return Objects.equals(this.uLowerCase, bookTickerResponse.uLowerCase)
                && Objects.equals(this.sLowerCase, bookTickerResponse.sLowerCase)
                && Objects.equals(this.bLowerCase, bookTickerResponse.bLowerCase)
                && Objects.equals(this.B, bookTickerResponse.B)
                && Objects.equals(this.aLowerCase, bookTickerResponse.aLowerCase)
                && Objects.equals(this.A, bookTickerResponse.A);
    }

    @Override
    public int hashCode() {
        return Objects.hash(uLowerCase, sLowerCase, bLowerCase, B, aLowerCase, A);
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();
        Map<String, String> valMap = new TreeMap<String, String>();
        valMap.put("apiKey", getApiKey());
        Long uLowerCaseValue = getuLowerCase();
        if (uLowerCaseValue != null) {
            String uLowerCaseValueAsString = uLowerCaseValue.toString();
            valMap.put("uLowerCase", uLowerCaseValueAsString);
        }
        String sLowerCaseValue = getsLowerCase();
        if (sLowerCaseValue != null) {
            String sLowerCaseValueAsString = sLowerCaseValue.toString();
            valMap.put("sLowerCase", sLowerCaseValueAsString);
        }
        String bLowerCaseValue = getbLowerCase();
        if (bLowerCaseValue != null) {
            String bLowerCaseValueAsString = bLowerCaseValue.toString();
            valMap.put("bLowerCase", bLowerCaseValueAsString);
        }
        String BValue = getB();
        if (BValue != null) {
            String BValueAsString = BValue.toString();
            valMap.put("B", BValueAsString);
        }
        String aLowerCaseValue = getaLowerCase();
        if (aLowerCaseValue != null) {
            String aLowerCaseValueAsString = aLowerCaseValue.toString();
            valMap.put("aLowerCase", aLowerCaseValueAsString);
        }
        String AValue = getA();
        if (AValue != null) {
            String AValueAsString = AValue.toString();
            valMap.put("A", AValueAsString);
        }

        valMap.put("timestamp", getTimestamp());
        return asciiEncode(
                valMap.keySet().stream()
                        .map(key -> key + "=" + valMap.get(key))
                        .collect(Collectors.joining("&")));
    }

    public static String asciiEncode(String s) {
        return new String(s.getBytes(), StandardCharsets.US_ASCII);
    }

}
