/*
 * Binance Spot WebSocket API
 * OpenAPI Specifications for the Binance Spot WebSocket API  API documents:   - [Github web-socket-api documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-api.md)   - [General API information for web-socket-api on website](https://developers.binance.com/docs/binance-spot-api-docs/web-socket-api/general-api-information)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.quarkus.spot.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.stream.Collectors;

public class ExchangeInfoResponseResultSorsInner extends BaseDTO {
    public static final String SERIALIZED_NAME_BASE_ASSET = "baseAsset";

    @JsonProperty(SERIALIZED_NAME_BASE_ASSET)
    
    private String baseAsset;

    public static final String SERIALIZED_NAME_SYMBOLS = "symbols";

    @JsonProperty(SERIALIZED_NAME_SYMBOLS)
    
    private List<String> symbols;

    public ExchangeInfoResponseResultSorsInner() {}

    public ExchangeInfoResponseResultSorsInner baseAsset(
             String baseAsset) {
        this.baseAsset = baseAsset;
        return this;
    }

    /**
     * Get baseAsset
     *
     * @return baseAsset
     */
    
    public String getBaseAsset() {
        return baseAsset;
    }

    public void setBaseAsset( String baseAsset) {
        this.baseAsset = baseAsset;
    }

    public ExchangeInfoResponseResultSorsInner symbols(
             List<String> symbols) {
        this.symbols = symbols;
        return this;
    }

    public ExchangeInfoResponseResultSorsInner addSymbolsItem(String symbolsItem) {
        if (this.symbols == null) {
            this.symbols = new ArrayList<>();
        }
        this.symbols.add(symbolsItem);
        return this;
    }

    /**
     * Get symbols
     *
     * @return symbols
     */
    
    public List<String> getSymbols() {
        return symbols;
    }

    public void setSymbols( List<String> symbols) {
        this.symbols = symbols;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ExchangeInfoResponseResultSorsInner exchangeInfoResponseResultSorsInner =
                (ExchangeInfoResponseResultSorsInner) o;
        return Objects.equals(this.baseAsset, exchangeInfoResponseResultSorsInner.baseAsset)
                && Objects.equals(this.symbols, exchangeInfoResponseResultSorsInner.symbols);
    }

    @Override
    public int hashCode() {
        return Objects.hash(baseAsset, symbols);
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();
        Map<String, String> valMap = new TreeMap<String, String>();
        valMap.put("apiKey", getApiKey());
        String baseAssetValue = getBaseAsset();
        if (baseAssetValue != null) {
            String baseAssetValueAsString = baseAssetValue.toString();
            valMap.put("baseAsset", baseAssetValueAsString);
        }
        List<String> symbolsValue = getSymbols();
        if (symbolsValue != null) {
            String symbolsValueAsString = symbolsValue.toString();
            valMap.put("symbols", symbolsValueAsString);
        }

        valMap.put("timestamp", getTimestamp());
        return asciiEncode(
                valMap.keySet().stream()
                        .map(key -> key + "=" + valMap.get(key))
                        .collect(Collectors.joining("&")));
    }

    public static String asciiEncode(String s) {
        return new String(s.getBytes(), StandardCharsets.US_ASCII);
    }

}
