/*
 * Binance Spot WebSocket API
 * OpenAPI Specifications for the Binance Spot WebSocket API  API documents:   - [Github web-socket-api documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-api.md)   - [General API information for web-socket-api on website](https://developers.binance.com/docs/binance-spot-api-docs/web-socket-api/general-api-information)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.quarkus.spot.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.vertx.core.json.Json;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.stream.Collectors;

public class ExchangeInfoResponseResult extends BaseDTO {
    public static final String SERIALIZED_NAME_TIMEZONE = "timezone";

    @JsonProperty(SERIALIZED_NAME_TIMEZONE)
    
    private String timezone;

    public static final String SERIALIZED_NAME_SERVER_TIME = "serverTime";

    @JsonProperty(SERIALIZED_NAME_SERVER_TIME)
    
    private Long serverTime;

    public static final String SERIALIZED_NAME_RATE_LIMITS = "rateLimits";

    @JsonProperty(SERIALIZED_NAME_RATE_LIMITS)
    
    private List<RateLimits> rateLimits;

    public static final String SERIALIZED_NAME_EXCHANGE_FILTERS = "exchangeFilters";

    @JsonProperty(SERIALIZED_NAME_EXCHANGE_FILTERS)
    
    private List<ExchangeFilters> exchangeFilters;

    public static final String SERIALIZED_NAME_SYMBOLS = "symbols";

    @JsonProperty(SERIALIZED_NAME_SYMBOLS)
    
    private List<ExchangeInfoResponseResultSymbolsInner> symbols;

    public static final String SERIALIZED_NAME_SORS = "sors";

    @JsonProperty(SERIALIZED_NAME_SORS)
    
    private List<ExchangeInfoResponseResultSorsInner> sors;

    public ExchangeInfoResponseResult() {}

    public ExchangeInfoResponseResult timezone( String timezone) {
        this.timezone = timezone;
        return this;
    }

    /**
     * Get timezone
     *
     * @return timezone
     */
    
    public String getTimezone() {
        return timezone;
    }

    public void setTimezone( String timezone) {
        this.timezone = timezone;
    }

    public ExchangeInfoResponseResult serverTime( Long serverTime) {
        this.serverTime = serverTime;
        return this;
    }

    /**
     * Get serverTime
     *
     * @return serverTime
     */
    
    public Long getServerTime() {
        return serverTime;
    }

    public void setServerTime( Long serverTime) {
        this.serverTime = serverTime;
    }

    public ExchangeInfoResponseResult rateLimits(
             List<RateLimits> rateLimits) {
        this.rateLimits = rateLimits;
        return this;
    }

    public ExchangeInfoResponseResult addRateLimitsItem(RateLimits rateLimitsItem) {
        if (this.rateLimits == null) {
            this.rateLimits = new ArrayList<>();
        }
        this.rateLimits.add(rateLimitsItem);
        return this;
    }

    /**
     * Get rateLimits
     *
     * @return rateLimits
     */
    public List<RateLimits> getRateLimits() {
        return rateLimits;
    }

    public void setRateLimits( List<RateLimits> rateLimits) {
        this.rateLimits = rateLimits;
    }

    public ExchangeInfoResponseResult exchangeFilters(
             List<ExchangeFilters> exchangeFilters) {
        this.exchangeFilters = exchangeFilters;
        return this;
    }

    public ExchangeInfoResponseResult addExchangeFiltersItem(ExchangeFilters exchangeFiltersItem) {
        if (this.exchangeFilters == null) {
            this.exchangeFilters = new ArrayList<>();
        }
        this.exchangeFilters.add(exchangeFiltersItem);
        return this;
    }

    /**
     * Get exchangeFilters
     *
     * @return exchangeFilters
     */
    public List<ExchangeFilters> getExchangeFilters() {
        return exchangeFilters;
    }

    public void setExchangeFilters(
             List<ExchangeFilters> exchangeFilters) {
        this.exchangeFilters = exchangeFilters;
    }

    public ExchangeInfoResponseResult symbols(
            
                    List<ExchangeInfoResponseResultSymbolsInner> symbols) {
        this.symbols = symbols;
        return this;
    }

    public ExchangeInfoResponseResult addSymbolsItem(
            ExchangeInfoResponseResultSymbolsInner symbolsItem) {
        if (this.symbols == null) {
            this.symbols = new ArrayList<>();
        }
        this.symbols.add(symbolsItem);
        return this;
    }

    /**
     * Get symbols
     *
     * @return symbols
     */
    public List<ExchangeInfoResponseResultSymbolsInner> getSymbols() {
        return symbols;
    }

    public void setSymbols(
            
                    List<ExchangeInfoResponseResultSymbolsInner> symbols) {
        this.symbols = symbols;
    }

    public ExchangeInfoResponseResult sors(
             List<ExchangeInfoResponseResultSorsInner> sors) {
        this.sors = sors;
        return this;
    }

    public ExchangeInfoResponseResult addSorsItem(ExchangeInfoResponseResultSorsInner sorsItem) {
        if (this.sors == null) {
            this.sors = new ArrayList<>();
        }
        this.sors.add(sorsItem);
        return this;
    }

    /**
     * Get sors
     *
     * @return sors
     */
    public List<ExchangeInfoResponseResultSorsInner> getSors() {
        return sors;
    }

    public void setSors(
             List<ExchangeInfoResponseResultSorsInner> sors) {
        this.sors = sors;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ExchangeInfoResponseResult exchangeInfoResponseResult = (ExchangeInfoResponseResult) o;
        return Objects.equals(this.timezone, exchangeInfoResponseResult.timezone)
                && Objects.equals(this.serverTime, exchangeInfoResponseResult.serverTime)
                && Objects.equals(this.rateLimits, exchangeInfoResponseResult.rateLimits)
                && Objects.equals(this.exchangeFilters, exchangeInfoResponseResult.exchangeFilters)
                && Objects.equals(this.symbols, exchangeInfoResponseResult.symbols)
                && Objects.equals(this.sors, exchangeInfoResponseResult.sors);
    }

    @Override
    public int hashCode() {
        return Objects.hash(timezone, serverTime, rateLimits, exchangeFilters, symbols, sors);
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();
        Map<String, String> valMap = new TreeMap<String, String>();
        valMap.put("apiKey", getApiKey());
        String timezoneValue = getTimezone();
        if (timezoneValue != null) {
            String timezoneValueAsString = timezoneValue.toString();
            valMap.put("timezone", timezoneValueAsString);
        }
        Long serverTimeValue = getServerTime();
        if (serverTimeValue != null) {
            String serverTimeValueAsString = serverTimeValue.toString();
            valMap.put("serverTime", serverTimeValueAsString);
        }
        List<RateLimits> rateLimitsValue = getRateLimits();
        if (rateLimitsValue != null) {
            String rateLimitsValueAsString = Json.encode(rateLimitsValue);
            valMap.put("rateLimits", rateLimitsValueAsString);
        }
        List<ExchangeFilters> exchangeFiltersValue = getExchangeFilters();
        if (exchangeFiltersValue != null) {
            String exchangeFiltersValueAsString = Json.encode(exchangeFiltersValue);
            valMap.put("exchangeFilters", exchangeFiltersValueAsString);
        }
        List<ExchangeInfoResponseResultSymbolsInner> symbolsValue = getSymbols();
        if (symbolsValue != null) {
            String symbolsValueAsString = Json.encode(symbolsValue);
            valMap.put("symbols", symbolsValueAsString);
        }
        List<ExchangeInfoResponseResultSorsInner> sorsValue = getSors();
        if (sorsValue != null) {
            String sorsValueAsString = Json.encode(sorsValue);
            valMap.put("sors", sorsValueAsString);
        }

        valMap.put("timestamp", getTimestamp());
        return asciiEncode(
                valMap.keySet().stream()
                        .map(key -> key + "=" + valMap.get(key))
                        .collect(Collectors.joining("&")));
    }

    public static String asciiEncode(String s) {
        return new String(s.getBytes(), StandardCharsets.US_ASCII);
    }

}
