/*
 * Binance Spot WebSocket API
 * OpenAPI Specifications for the Binance Spot WebSocket API  API documents:   - [Github web-socket-api documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-api.md)   - [General API information for web-socket-api on website](https://developers.binance.com/docs/binance-spot-api-docs/web-socket-api/general-api-information)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.quarkus.spot.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.vertx.core.json.Json;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.stream.Collectors;

public class ExchangeInfoResponse extends BaseDTO {
    public static final String SERIALIZED_NAME_ID = "id";

    @JsonProperty(SERIALIZED_NAME_ID)
    
    private String id;

    public static final String SERIALIZED_NAME_STATUS = "status";

    @JsonProperty(SERIALIZED_NAME_STATUS)
    
    private Long status;

    public static final String SERIALIZED_NAME_RESULT = "result";

    @JsonProperty(SERIALIZED_NAME_RESULT)
    
    private ExchangeInfoResponseResult result;

    public static final String SERIALIZED_NAME_RATE_LIMITS = "rateLimits";

    @JsonProperty(SERIALIZED_NAME_RATE_LIMITS)
    
    private List<RateLimits> rateLimits;

    public ExchangeInfoResponse() {}

    public ExchangeInfoResponse id( String id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     */
    
    public String getId() {
        return id;
    }

    public void setId( String id) {
        this.id = id;
    }

    public ExchangeInfoResponse status( Long status) {
        this.status = status;
        return this;
    }

    /**
     * Get status
     *
     * @return status
     */
    
    public Long getStatus() {
        return status;
    }

    public void setStatus( Long status) {
        this.status = status;
    }

    public ExchangeInfoResponse result(
             ExchangeInfoResponseResult result) {
        this.result = result;
        return this;
    }

    /**
     * Get result
     *
     * @return result
     */
    public ExchangeInfoResponseResult getResult() {
        return result;
    }

    public void setResult( ExchangeInfoResponseResult result) {
        this.result = result;
    }

    public ExchangeInfoResponse rateLimits(
             List<RateLimits> rateLimits) {
        this.rateLimits = rateLimits;
        return this;
    }

    public ExchangeInfoResponse addRateLimitsItem(RateLimits rateLimitsItem) {
        if (this.rateLimits == null) {
            this.rateLimits = new ArrayList<>();
        }
        this.rateLimits.add(rateLimitsItem);
        return this;
    }

    /**
     * Get rateLimits
     *
     * @return rateLimits
     */
    public List<RateLimits> getRateLimits() {
        return rateLimits;
    }

    public void setRateLimits( List<RateLimits> rateLimits) {
        this.rateLimits = rateLimits;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ExchangeInfoResponse exchangeInfoResponse = (ExchangeInfoResponse) o;
        return Objects.equals(this.id, exchangeInfoResponse.id)
                && Objects.equals(this.status, exchangeInfoResponse.status)
                && Objects.equals(this.result, exchangeInfoResponse.result)
                && Objects.equals(this.rateLimits, exchangeInfoResponse.rateLimits);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, status, result, rateLimits);
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();
        Map<String, String> valMap = new TreeMap<String, String>();
        valMap.put("apiKey", getApiKey());
        String idValue = getId();
        if (idValue != null) {
            String idValueAsString = idValue.toString();
            valMap.put("id", idValueAsString);
        }
        Long statusValue = getStatus();
        if (statusValue != null) {
            String statusValueAsString = statusValue.toString();
            valMap.put("status", statusValueAsString);
        }
        ExchangeInfoResponseResult resultValue = getResult();
        if (resultValue != null) {
            String resultValueAsString = Json.encode(resultValue);
            valMap.put("result", resultValueAsString);
        }
        List<RateLimits> rateLimitsValue = getRateLimits();
        if (rateLimitsValue != null) {
            String rateLimitsValueAsString = Json.encode(rateLimitsValue);
            valMap.put("rateLimits", rateLimitsValueAsString);
        }

        valMap.put("timestamp", getTimestamp());
        return asciiEncode(
                valMap.keySet().stream()
                        .map(key -> key + "=" + valMap.get(key))
                        .collect(Collectors.joining("&")));
    }

    public static String asciiEncode(String s) {
        return new String(s.getBytes(), StandardCharsets.US_ASCII);
    }

}
