/*
 * Binance Spot WebSocket Streams
 * OpenAPI Specifications for the Binance Spot WebSocket Streams  API documents:   - [Github web-socket-streams documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-streams.md)   - [General API information for web-socket-streams on website](https://developers.binance.com/docs/binance-spot-api-docs/web-socket-streams)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.quarkus.spot.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.vertx.core.json.Json;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.stream.Collectors;

public class KlineResponse extends BaseDTO {
    public static final String SERIALIZED_NAME_E_LOWER_CASE = "e";

    @JsonProperty(SERIALIZED_NAME_E_LOWER_CASE)
    
    private String eLowerCase;

    public static final String SERIALIZED_NAME_E = "E";

    @JsonProperty(SERIALIZED_NAME_E)
    
    private Long E;

    public static final String SERIALIZED_NAME_S_LOWER_CASE = "s";

    @JsonProperty(SERIALIZED_NAME_S_LOWER_CASE)
    
    private String sLowerCase;

    public static final String SERIALIZED_NAME_K_LOWER_CASE = "k";

    @JsonProperty(SERIALIZED_NAME_K_LOWER_CASE)
    
    private KlineResponseK kLowerCase;

    public KlineResponse() {}

    public KlineResponse eLowerCase( String eLowerCase) {
        this.eLowerCase = eLowerCase;
        return this;
    }

    /**
     * Get eLowerCase
     *
     * @return eLowerCase
     */
    
    public String geteLowerCase() {
        return eLowerCase;
    }

    public void seteLowerCase( String eLowerCase) {
        this.eLowerCase = eLowerCase;
    }

    public KlineResponse E( Long E) {
        this.E = E;
        return this;
    }

    /**
     * Get E
     *
     * @return E
     */
    
    public Long getE() {
        return E;
    }

    public void setE( Long E) {
        this.E = E;
    }

    public KlineResponse sLowerCase( String sLowerCase) {
        this.sLowerCase = sLowerCase;
        return this;
    }

    /**
     * Get sLowerCase
     *
     * @return sLowerCase
     */
    
    public String getsLowerCase() {
        return sLowerCase;
    }

    public void setsLowerCase( String sLowerCase) {
        this.sLowerCase = sLowerCase;
    }

    public KlineResponse kLowerCase( KlineResponseK kLowerCase) {
        this.kLowerCase = kLowerCase;
        return this;
    }

    /**
     * Get kLowerCase
     *
     * @return kLowerCase
     */
    public KlineResponseK getkLowerCase() {
        return kLowerCase;
    }

    public void setkLowerCase( KlineResponseK kLowerCase) {
        this.kLowerCase = kLowerCase;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        KlineResponse klineResponse = (KlineResponse) o;
        return Objects.equals(this.eLowerCase, klineResponse.eLowerCase)
                && Objects.equals(this.E, klineResponse.E)
                && Objects.equals(this.sLowerCase, klineResponse.sLowerCase)
                && Objects.equals(this.kLowerCase, klineResponse.kLowerCase);
    }

    @Override
    public int hashCode() {
        return Objects.hash(eLowerCase, E, sLowerCase, kLowerCase);
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();
        Map<String, String> valMap = new TreeMap<String, String>();
        valMap.put("apiKey", getApiKey());
        String eLowerCaseValue = geteLowerCase();
        if (eLowerCaseValue != null) {
            String eLowerCaseValueAsString = eLowerCaseValue.toString();
            valMap.put("eLowerCase", eLowerCaseValueAsString);
        }
        Long EValue = getE();
        if (EValue != null) {
            String EValueAsString = EValue.toString();
            valMap.put("E", EValueAsString);
        }
        String sLowerCaseValue = getsLowerCase();
        if (sLowerCaseValue != null) {
            String sLowerCaseValueAsString = sLowerCaseValue.toString();
            valMap.put("sLowerCase", sLowerCaseValueAsString);
        }
        KlineResponseK kLowerCaseValue = getkLowerCase();
        if (kLowerCaseValue != null) {
            String kLowerCaseValueAsString = Json.encode(kLowerCaseValue);
            valMap.put("kLowerCase", kLowerCaseValueAsString);
        }

        valMap.put("timestamp", getTimestamp());
        return asciiEncode(
                valMap.keySet().stream()
                        .map(key -> key + "=" + valMap.get(key))
                        .collect(Collectors.joining("&")));
    }

    public Map<String, Object> toMap() {
        Map<String, Object> valMap = new TreeMap<String, Object>();
        valMap.put("apiKey", getApiKey());
        Object eLowerCaseValue = geteLowerCase();
        if (eLowerCaseValue != null) {
            valMap.put("eLowerCase", eLowerCaseValue);
        }
        Object EValue = getE();
        if (EValue != null) {
            valMap.put("E", EValue);
        }
        Object sLowerCaseValue = getsLowerCase();
        if (sLowerCaseValue != null) {
            valMap.put("sLowerCase", sLowerCaseValue);
        }
        Object kLowerCaseValue = getkLowerCase();
        if (kLowerCaseValue != null) {
            valMap.put("kLowerCase", kLowerCaseValue);
        }

        valMap.put("timestamp", getTimestamp());
        return valMap;
    }

    public static String asciiEncode(String s) {
        return new String(s.getBytes(), StandardCharsets.US_ASCII);
    }
}
