/*
 * Binance Spot WebSocket API
 * OpenAPI Specifications for the Binance Spot WebSocket API  API documents:   - [Github web-socket-api documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-api.md)   - [General API information for web-socket-api on website](https://developers.binance.com/docs/binance-spot-api-docs/web-socket-api/general-api-information)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.quarkus.spot.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.stream.Collectors;

public class MaxAssetFilter extends BaseDTO {
    public static final String SERIALIZED_NAME_FILTER_TYPE = "filterType";

    @JsonProperty(SERIALIZED_NAME_FILTER_TYPE)
    
    private String filterType;

    public static final String SERIALIZED_NAME_QTY_EXPONENT = "qtyExponent";

    @JsonProperty(SERIALIZED_NAME_QTY_EXPONENT)
    
    private Integer qtyExponent;

    public static final String SERIALIZED_NAME_LIMIT = "limit";

    @JsonProperty(SERIALIZED_NAME_LIMIT)
    
    private String limit;

    public static final String SERIALIZED_NAME_ASSET = "asset";

    @JsonProperty(SERIALIZED_NAME_ASSET)
    
    private String asset;

    public MaxAssetFilter() {}

    public MaxAssetFilter filterType( String filterType) {
        this.filterType = filterType;
        return this;
    }

    /**
     * Get filterType
     *
     * @return filterType
     */
    
    public String getFilterType() {
        return filterType;
    }

    public void setFilterType( String filterType) {
        this.filterType = filterType;
    }

    public MaxAssetFilter qtyExponent( Integer qtyExponent) {
        this.qtyExponent = qtyExponent;
        return this;
    }

    /**
     * Get qtyExponent
     *
     * @return qtyExponent
     */
    
    public Integer getQtyExponent() {
        return qtyExponent;
    }

    public void setQtyExponent( Integer qtyExponent) {
        this.qtyExponent = qtyExponent;
    }

    public MaxAssetFilter limit( String limit) {
        this.limit = limit;
        return this;
    }

    /**
     * Get limit
     *
     * @return limit
     */
    
    public String getLimit() {
        return limit;
    }

    public void setLimit( String limit) {
        this.limit = limit;
    }

    public MaxAssetFilter asset( String asset) {
        this.asset = asset;
        return this;
    }

    /**
     * Get asset
     *
     * @return asset
     */
    
    public String getAsset() {
        return asset;
    }

    public void setAsset( String asset) {
        this.asset = asset;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MaxAssetFilter maxAssetFilter = (MaxAssetFilter) o;
        return Objects.equals(this.filterType, maxAssetFilter.filterType)
                && Objects.equals(this.qtyExponent, maxAssetFilter.qtyExponent)
                && Objects.equals(this.limit, maxAssetFilter.limit)
                && Objects.equals(this.asset, maxAssetFilter.asset);
    }

    @Override
    public int hashCode() {
        return Objects.hash(filterType, qtyExponent, limit, asset);
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();
        Map<String, String> valMap = new TreeMap<String, String>();
        valMap.put("apiKey", getApiKey());
        String filterTypeValue = getFilterType();
        if (filterTypeValue != null) {
            String filterTypeValueAsString = filterTypeValue.toString();
            valMap.put("filterType", filterTypeValueAsString);
        }
        Integer qtyExponentValue = getQtyExponent();
        if (qtyExponentValue != null) {
            String qtyExponentValueAsString = qtyExponentValue.toString();
            valMap.put("qtyExponent", qtyExponentValueAsString);
        }
        String limitValue = getLimit();
        if (limitValue != null) {
            String limitValueAsString = limitValue.toString();
            valMap.put("limit", limitValueAsString);
        }
        String assetValue = getAsset();
        if (assetValue != null) {
            String assetValueAsString = assetValue.toString();
            valMap.put("asset", assetValueAsString);
        }

        valMap.put("timestamp", getTimestamp());
        return asciiEncode(
                valMap.keySet().stream()
                        .map(key -> key + "=" + valMap.get(key))
                        .collect(Collectors.joining("&")));
    }

    public static String asciiEncode(String s) {
        return new String(s.getBytes(), StandardCharsets.US_ASCII);
    }

}
