/*
 * Binance Spot WebSocket API
 * OpenAPI Specifications for the Binance Spot WebSocket API  API documents:   - [Github web-socket-api documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-api.md)   - [General API information for web-socket-api on website](https://developers.binance.com/docs/binance-spot-api-docs/web-socket-api/general-api-information)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.quarkus.spot.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.nio.charset.StandardCharsets;
import java.util.Map;
import java.util.Objects;
import java.util.TreeMap;
import java.util.stream.Collectors;

public class MaxNumOrderListsFilter extends BaseDTO {
    public static final String SERIALIZED_NAME_FILTER_TYPE = "filterType";

    @JsonProperty(SERIALIZED_NAME_FILTER_TYPE)
    
    private String filterType;

    public static final String SERIALIZED_NAME_MAX_NUM_ORDER_LISTS = "maxNumOrderLists";

    @JsonProperty(SERIALIZED_NAME_MAX_NUM_ORDER_LISTS)
    
    private Long maxNumOrderLists;

    public MaxNumOrderListsFilter() {}

    public MaxNumOrderListsFilter filterType( String filterType) {
        this.filterType = filterType;
        return this;
    }

    /**
     * Get filterType
     *
     * @return filterType
     */
    
    public String getFilterType() {
        return filterType;
    }

    public void setFilterType( String filterType) {
        this.filterType = filterType;
    }

    public MaxNumOrderListsFilter maxNumOrderLists(
             Long maxNumOrderLists) {
        this.maxNumOrderLists = maxNumOrderLists;
        return this;
    }

    /**
     * Get maxNumOrderLists
     *
     * @return maxNumOrderLists
     */
    
    public Long getMaxNumOrderLists() {
        return maxNumOrderLists;
    }

    public void setMaxNumOrderLists( Long maxNumOrderLists) {
        this.maxNumOrderLists = maxNumOrderLists;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MaxNumOrderListsFilter maxNumOrderListsFilter = (MaxNumOrderListsFilter) o;
        return Objects.equals(this.filterType, maxNumOrderListsFilter.filterType)
                && Objects.equals(this.maxNumOrderLists, maxNumOrderListsFilter.maxNumOrderLists);
    }

    @Override
    public int hashCode() {
        return Objects.hash(filterType, maxNumOrderLists);
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();
        Map<String, String> valMap = new TreeMap<String, String>();
        valMap.put("apiKey", getApiKey());
        String filterTypeValue = getFilterType();
        if (filterTypeValue != null) {
            String filterTypeValueAsString = filterTypeValue.toString();
            valMap.put("filterType", filterTypeValueAsString);
        }
        Long maxNumOrderListsValue = getMaxNumOrderLists();
        if (maxNumOrderListsValue != null) {
            String maxNumOrderListsValueAsString = maxNumOrderListsValue.toString();
            valMap.put("maxNumOrderLists", maxNumOrderListsValueAsString);
        }

        valMap.put("timestamp", getTimestamp());
        return asciiEncode(
                valMap.keySet().stream()
                        .map(key -> key + "=" + valMap.get(key))
                        .collect(Collectors.joining("&")));
    }

    public static String asciiEncode(String s) {
        return new String(s.getBytes(), StandardCharsets.US_ASCII);
    }

}
