/*
 * Binance Spot WebSocket Streams
 * OpenAPI Specifications for the Binance Spot WebSocket Streams  API documents:   - [Github web-socket-streams documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-streams.md)   - [General API information for web-socket-streams on website](https://developers.binance.com/docs/binance-spot-api-docs/web-socket-streams)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.quarkus.spot.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.stream.Collectors;

public class MiniTickerResponse extends BaseDTO {
    public static final String SERIALIZED_NAME_E_LOWER_CASE = "e";

    @JsonProperty(SERIALIZED_NAME_E_LOWER_CASE)
    
    private String eLowerCase;

    public static final String SERIALIZED_NAME_E = "E";

    @JsonProperty(SERIALIZED_NAME_E)
    
    private Long E;

    public static final String SERIALIZED_NAME_S_LOWER_CASE = "s";

    @JsonProperty(SERIALIZED_NAME_S_LOWER_CASE)
    
    private String sLowerCase;

    public static final String SERIALIZED_NAME_C_LOWER_CASE = "c";

    @JsonProperty(SERIALIZED_NAME_C_LOWER_CASE)
    
    private String cLowerCase;

    public static final String SERIALIZED_NAME_O_LOWER_CASE = "o";

    @JsonProperty(SERIALIZED_NAME_O_LOWER_CASE)
    
    private String oLowerCase;

    public static final String SERIALIZED_NAME_H_LOWER_CASE = "h";

    @JsonProperty(SERIALIZED_NAME_H_LOWER_CASE)
    
    private String hLowerCase;

    public static final String SERIALIZED_NAME_L_LOWER_CASE = "l";

    @JsonProperty(SERIALIZED_NAME_L_LOWER_CASE)
    
    private String lLowerCase;

    public static final String SERIALIZED_NAME_V_LOWER_CASE = "v";

    @JsonProperty(SERIALIZED_NAME_V_LOWER_CASE)
    
    private String vLowerCase;

    public static final String SERIALIZED_NAME_Q_LOWER_CASE = "q";

    @JsonProperty(SERIALIZED_NAME_Q_LOWER_CASE)
    
    private String qLowerCase;

    public MiniTickerResponse() {}

    public MiniTickerResponse eLowerCase( String eLowerCase) {
        this.eLowerCase = eLowerCase;
        return this;
    }

    /**
     * Get eLowerCase
     *
     * @return eLowerCase
     */
    
    public String geteLowerCase() {
        return eLowerCase;
    }

    public void seteLowerCase( String eLowerCase) {
        this.eLowerCase = eLowerCase;
    }

    public MiniTickerResponse E( Long E) {
        this.E = E;
        return this;
    }

    /**
     * Get E
     *
     * @return E
     */
    
    public Long getE() {
        return E;
    }

    public void setE( Long E) {
        this.E = E;
    }

    public MiniTickerResponse sLowerCase( String sLowerCase) {
        this.sLowerCase = sLowerCase;
        return this;
    }

    /**
     * Get sLowerCase
     *
     * @return sLowerCase
     */
    
    public String getsLowerCase() {
        return sLowerCase;
    }

    public void setsLowerCase( String sLowerCase) {
        this.sLowerCase = sLowerCase;
    }

    public MiniTickerResponse cLowerCase( String cLowerCase) {
        this.cLowerCase = cLowerCase;
        return this;
    }

    /**
     * Get cLowerCase
     *
     * @return cLowerCase
     */
    
    public String getcLowerCase() {
        return cLowerCase;
    }

    public void setcLowerCase( String cLowerCase) {
        this.cLowerCase = cLowerCase;
    }

    public MiniTickerResponse oLowerCase( String oLowerCase) {
        this.oLowerCase = oLowerCase;
        return this;
    }

    /**
     * Get oLowerCase
     *
     * @return oLowerCase
     */
    
    public String getoLowerCase() {
        return oLowerCase;
    }

    public void setoLowerCase( String oLowerCase) {
        this.oLowerCase = oLowerCase;
    }

    public MiniTickerResponse hLowerCase( String hLowerCase) {
        this.hLowerCase = hLowerCase;
        return this;
    }

    /**
     * Get hLowerCase
     *
     * @return hLowerCase
     */
    
    public String gethLowerCase() {
        return hLowerCase;
    }

    public void sethLowerCase( String hLowerCase) {
        this.hLowerCase = hLowerCase;
    }

    public MiniTickerResponse lLowerCase( String lLowerCase) {
        this.lLowerCase = lLowerCase;
        return this;
    }

    /**
     * Get lLowerCase
     *
     * @return lLowerCase
     */
    
    public String getlLowerCase() {
        return lLowerCase;
    }

    public void setlLowerCase( String lLowerCase) {
        this.lLowerCase = lLowerCase;
    }

    public MiniTickerResponse vLowerCase( String vLowerCase) {
        this.vLowerCase = vLowerCase;
        return this;
    }

    /**
     * Get vLowerCase
     *
     * @return vLowerCase
     */
    
    public String getvLowerCase() {
        return vLowerCase;
    }

    public void setvLowerCase( String vLowerCase) {
        this.vLowerCase = vLowerCase;
    }

    public MiniTickerResponse qLowerCase( String qLowerCase) {
        this.qLowerCase = qLowerCase;
        return this;
    }

    /**
     * Get qLowerCase
     *
     * @return qLowerCase
     */
    
    public String getqLowerCase() {
        return qLowerCase;
    }

    public void setqLowerCase( String qLowerCase) {
        this.qLowerCase = qLowerCase;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MiniTickerResponse miniTickerResponse = (MiniTickerResponse) o;
        return Objects.equals(this.eLowerCase, miniTickerResponse.eLowerCase)
                && Objects.equals(this.E, miniTickerResponse.E)
                && Objects.equals(this.sLowerCase, miniTickerResponse.sLowerCase)
                && Objects.equals(this.cLowerCase, miniTickerResponse.cLowerCase)
                && Objects.equals(this.oLowerCase, miniTickerResponse.oLowerCase)
                && Objects.equals(this.hLowerCase, miniTickerResponse.hLowerCase)
                && Objects.equals(this.lLowerCase, miniTickerResponse.lLowerCase)
                && Objects.equals(this.vLowerCase, miniTickerResponse.vLowerCase)
                && Objects.equals(this.qLowerCase, miniTickerResponse.qLowerCase);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                eLowerCase,
                E,
                sLowerCase,
                cLowerCase,
                oLowerCase,
                hLowerCase,
                lLowerCase,
                vLowerCase,
                qLowerCase);
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();
        Map<String, String> valMap = new TreeMap<String, String>();
        valMap.put("apiKey", getApiKey());
        String eLowerCaseValue = geteLowerCase();
        if (eLowerCaseValue != null) {
            String eLowerCaseValueAsString = eLowerCaseValue.toString();
            valMap.put("eLowerCase", eLowerCaseValueAsString);
        }
        Long EValue = getE();
        if (EValue != null) {
            String EValueAsString = EValue.toString();
            valMap.put("E", EValueAsString);
        }
        String sLowerCaseValue = getsLowerCase();
        if (sLowerCaseValue != null) {
            String sLowerCaseValueAsString = sLowerCaseValue.toString();
            valMap.put("sLowerCase", sLowerCaseValueAsString);
        }
        String cLowerCaseValue = getcLowerCase();
        if (cLowerCaseValue != null) {
            String cLowerCaseValueAsString = cLowerCaseValue.toString();
            valMap.put("cLowerCase", cLowerCaseValueAsString);
        }
        String oLowerCaseValue = getoLowerCase();
        if (oLowerCaseValue != null) {
            String oLowerCaseValueAsString = oLowerCaseValue.toString();
            valMap.put("oLowerCase", oLowerCaseValueAsString);
        }
        String hLowerCaseValue = gethLowerCase();
        if (hLowerCaseValue != null) {
            String hLowerCaseValueAsString = hLowerCaseValue.toString();
            valMap.put("hLowerCase", hLowerCaseValueAsString);
        }
        String lLowerCaseValue = getlLowerCase();
        if (lLowerCaseValue != null) {
            String lLowerCaseValueAsString = lLowerCaseValue.toString();
            valMap.put("lLowerCase", lLowerCaseValueAsString);
        }
        String vLowerCaseValue = getvLowerCase();
        if (vLowerCaseValue != null) {
            String vLowerCaseValueAsString = vLowerCaseValue.toString();
            valMap.put("vLowerCase", vLowerCaseValueAsString);
        }
        String qLowerCaseValue = getqLowerCase();
        if (qLowerCaseValue != null) {
            String qLowerCaseValueAsString = qLowerCaseValue.toString();
            valMap.put("qLowerCase", qLowerCaseValueAsString);
        }

        valMap.put("timestamp", getTimestamp());
        return asciiEncode(
                valMap.keySet().stream()
                        .map(key -> key + "=" + valMap.get(key))
                        .collect(Collectors.joining("&")));
    }

    public Map<String, Object> toMap() {
        Map<String, Object> valMap = new TreeMap<String, Object>();
        valMap.put("apiKey", getApiKey());
        Object eLowerCaseValue = geteLowerCase();
        if (eLowerCaseValue != null) {
            valMap.put("eLowerCase", eLowerCaseValue);
        }
        Object EValue = getE();
        if (EValue != null) {
            valMap.put("E", EValue);
        }
        Object sLowerCaseValue = getsLowerCase();
        if (sLowerCaseValue != null) {
            valMap.put("sLowerCase", sLowerCaseValue);
        }
        Object cLowerCaseValue = getcLowerCase();
        if (cLowerCaseValue != null) {
            valMap.put("cLowerCase", cLowerCaseValue);
        }
        Object oLowerCaseValue = getoLowerCase();
        if (oLowerCaseValue != null) {
            valMap.put("oLowerCase", oLowerCaseValue);
        }
        Object hLowerCaseValue = gethLowerCase();
        if (hLowerCaseValue != null) {
            valMap.put("hLowerCase", hLowerCaseValue);
        }
        Object lLowerCaseValue = getlLowerCase();
        if (lLowerCaseValue != null) {
            valMap.put("lLowerCase", lLowerCaseValue);
        }
        Object vLowerCaseValue = getvLowerCase();
        if (vLowerCaseValue != null) {
            valMap.put("vLowerCase", vLowerCaseValue);
        }
        Object qLowerCaseValue = getqLowerCase();
        if (qLowerCaseValue != null) {
            valMap.put("qLowerCase", qLowerCaseValue);
        }

        valMap.put("timestamp", getTimestamp());
        return valMap;
    }

    public static String asciiEncode(String s) {
        return new String(s.getBytes(), StandardCharsets.US_ASCII);
    }
}
