/*
 * Binance Spot WebSocket API
 * OpenAPI Specifications for the Binance Spot WebSocket API  API documents:   - [Github web-socket-api documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-api.md)   - [General API information for web-socket-api on website](https://developers.binance.com/docs/binance-spot-api-docs/web-socket-api/general-api-information)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.quarkus.spot.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.stream.Collectors;

public class MyPreventedMatchesResponseResultInner extends BaseDTO {
    public static final String SERIALIZED_NAME_SYMBOL = "symbol";

    @JsonProperty(SERIALIZED_NAME_SYMBOL)
    
    private String symbol;

    public static final String SERIALIZED_NAME_PREVENTED_MATCH_ID = "preventedMatchId";

    @JsonProperty(SERIALIZED_NAME_PREVENTED_MATCH_ID)
    
    private Long preventedMatchId;

    public static final String SERIALIZED_NAME_TAKER_ORDER_ID = "takerOrderId";

    @JsonProperty(SERIALIZED_NAME_TAKER_ORDER_ID)
    
    private Long takerOrderId;

    public static final String SERIALIZED_NAME_MAKER_SYMBOL = "makerSymbol";

    @JsonProperty(SERIALIZED_NAME_MAKER_SYMBOL)
    
    private String makerSymbol;

    public static final String SERIALIZED_NAME_MAKER_ORDER_ID = "makerOrderId";

    @JsonProperty(SERIALIZED_NAME_MAKER_ORDER_ID)
    
    private Long makerOrderId;

    public static final String SERIALIZED_NAME_TRADE_GROUP_ID = "tradeGroupId";

    @JsonProperty(SERIALIZED_NAME_TRADE_GROUP_ID)
    
    private Long tradeGroupId;

    public static final String SERIALIZED_NAME_SELF_TRADE_PREVENTION_MODE =
            "selfTradePreventionMode";

    @JsonProperty(SERIALIZED_NAME_SELF_TRADE_PREVENTION_MODE)
    
    private String selfTradePreventionMode;

    public static final String SERIALIZED_NAME_PRICE = "price";

    @JsonProperty(SERIALIZED_NAME_PRICE)
    
    private String price;

    public static final String SERIALIZED_NAME_MAKER_PREVENTED_QUANTITY = "makerPreventedQuantity";

    @JsonProperty(SERIALIZED_NAME_MAKER_PREVENTED_QUANTITY)
    
    private String makerPreventedQuantity;

    public static final String SERIALIZED_NAME_TRANSACT_TIME = "transactTime";

    @JsonProperty(SERIALIZED_NAME_TRANSACT_TIME)
    
    private Long transactTime;

    public MyPreventedMatchesResponseResultInner() {}

    public MyPreventedMatchesResponseResultInner symbol(
             String symbol) {
        this.symbol = symbol;
        return this;
    }

    /**
     * Get symbol
     *
     * @return symbol
     */
    
    public String getSymbol() {
        return symbol;
    }

    public void setSymbol( String symbol) {
        this.symbol = symbol;
    }

    public MyPreventedMatchesResponseResultInner preventedMatchId(
             Long preventedMatchId) {
        this.preventedMatchId = preventedMatchId;
        return this;
    }

    /**
     * Get preventedMatchId
     *
     * @return preventedMatchId
     */
    
    public Long getPreventedMatchId() {
        return preventedMatchId;
    }

    public void setPreventedMatchId( Long preventedMatchId) {
        this.preventedMatchId = preventedMatchId;
    }

    public MyPreventedMatchesResponseResultInner takerOrderId(
             Long takerOrderId) {
        this.takerOrderId = takerOrderId;
        return this;
    }

    /**
     * Get takerOrderId
     *
     * @return takerOrderId
     */
    
    public Long getTakerOrderId() {
        return takerOrderId;
    }

    public void setTakerOrderId( Long takerOrderId) {
        this.takerOrderId = takerOrderId;
    }

    public MyPreventedMatchesResponseResultInner makerSymbol(
             String makerSymbol) {
        this.makerSymbol = makerSymbol;
        return this;
    }

    /**
     * Get makerSymbol
     *
     * @return makerSymbol
     */
    
    public String getMakerSymbol() {
        return makerSymbol;
    }

    public void setMakerSymbol( String makerSymbol) {
        this.makerSymbol = makerSymbol;
    }

    public MyPreventedMatchesResponseResultInner makerOrderId(
             Long makerOrderId) {
        this.makerOrderId = makerOrderId;
        return this;
    }

    /**
     * Get makerOrderId
     *
     * @return makerOrderId
     */
    
    public Long getMakerOrderId() {
        return makerOrderId;
    }

    public void setMakerOrderId( Long makerOrderId) {
        this.makerOrderId = makerOrderId;
    }

    public MyPreventedMatchesResponseResultInner tradeGroupId(
             Long tradeGroupId) {
        this.tradeGroupId = tradeGroupId;
        return this;
    }

    /**
     * Get tradeGroupId
     *
     * @return tradeGroupId
     */
    
    public Long getTradeGroupId() {
        return tradeGroupId;
    }

    public void setTradeGroupId( Long tradeGroupId) {
        this.tradeGroupId = tradeGroupId;
    }

    public MyPreventedMatchesResponseResultInner selfTradePreventionMode(
             String selfTradePreventionMode) {
        this.selfTradePreventionMode = selfTradePreventionMode;
        return this;
    }

    /**
     * Get selfTradePreventionMode
     *
     * @return selfTradePreventionMode
     */
    
    public String getSelfTradePreventionMode() {
        return selfTradePreventionMode;
    }

    public void setSelfTradePreventionMode(
             String selfTradePreventionMode) {
        this.selfTradePreventionMode = selfTradePreventionMode;
    }

    public MyPreventedMatchesResponseResultInner price( String price) {
        this.price = price;
        return this;
    }

    /**
     * Get price
     *
     * @return price
     */
    
    public String getPrice() {
        return price;
    }

    public void setPrice( String price) {
        this.price = price;
    }

    public MyPreventedMatchesResponseResultInner makerPreventedQuantity(
             String makerPreventedQuantity) {
        this.makerPreventedQuantity = makerPreventedQuantity;
        return this;
    }

    /**
     * Get makerPreventedQuantity
     *
     * @return makerPreventedQuantity
     */
    
    public String getMakerPreventedQuantity() {
        return makerPreventedQuantity;
    }

    public void setMakerPreventedQuantity(
             String makerPreventedQuantity) {
        this.makerPreventedQuantity = makerPreventedQuantity;
    }

    public MyPreventedMatchesResponseResultInner transactTime(
             Long transactTime) {
        this.transactTime = transactTime;
        return this;
    }

    /**
     * Get transactTime
     *
     * @return transactTime
     */
    
    public Long getTransactTime() {
        return transactTime;
    }

    public void setTransactTime( Long transactTime) {
        this.transactTime = transactTime;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MyPreventedMatchesResponseResultInner myPreventedMatchesResponseResultInner =
                (MyPreventedMatchesResponseResultInner) o;
        return Objects.equals(this.symbol, myPreventedMatchesResponseResultInner.symbol)
                && Objects.equals(
                        this.preventedMatchId,
                        myPreventedMatchesResponseResultInner.preventedMatchId)
                && Objects.equals(
                        this.takerOrderId, myPreventedMatchesResponseResultInner.takerOrderId)
                && Objects.equals(
                        this.makerSymbol, myPreventedMatchesResponseResultInner.makerSymbol)
                && Objects.equals(
                        this.makerOrderId, myPreventedMatchesResponseResultInner.makerOrderId)
                && Objects.equals(
                        this.tradeGroupId, myPreventedMatchesResponseResultInner.tradeGroupId)
                && Objects.equals(
                        this.selfTradePreventionMode,
                        myPreventedMatchesResponseResultInner.selfTradePreventionMode)
                && Objects.equals(this.price, myPreventedMatchesResponseResultInner.price)
                && Objects.equals(
                        this.makerPreventedQuantity,
                        myPreventedMatchesResponseResultInner.makerPreventedQuantity)
                && Objects.equals(
                        this.transactTime, myPreventedMatchesResponseResultInner.transactTime);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                symbol,
                preventedMatchId,
                takerOrderId,
                makerSymbol,
                makerOrderId,
                tradeGroupId,
                selfTradePreventionMode,
                price,
                makerPreventedQuantity,
                transactTime);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class MyPreventedMatchesResponseResultInner {\n");
        sb.append("		symbol: ").append(toIndentedString(symbol)).append("\n");
        sb.append("		preventedMatchId: ").append(toIndentedString(preventedMatchId)).append("\n");
        sb.append("		takerOrderId: ").append(toIndentedString(takerOrderId)).append("\n");
        sb.append("		makerSymbol: ").append(toIndentedString(makerSymbol)).append("\n");
        sb.append("		makerOrderId: ").append(toIndentedString(makerOrderId)).append("\n");
        sb.append("		tradeGroupId: ").append(toIndentedString(tradeGroupId)).append("\n");
        sb.append("		selfTradePreventionMode: ")
                .append(toIndentedString(selfTradePreventionMode))
                .append("\n");
        sb.append("		price: ").append(toIndentedString(price)).append("\n");
        sb.append("		makerPreventedQuantity: ")
                .append(toIndentedString(makerPreventedQuantity))
                .append("\n");
        sb.append("		transactTime: ").append(toIndentedString(transactTime)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();
        Map<String, String> valMap = new TreeMap<String, String>();
        valMap.put("apiKey", getApiKey());
        String symbolValue = getSymbol();
        if (symbolValue != null) {
            String symbolValueAsString = symbolValue.toString();
            valMap.put("symbol", symbolValueAsString);
        }
        Long preventedMatchIdValue = getPreventedMatchId();
        if (preventedMatchIdValue != null) {
            String preventedMatchIdValueAsString = preventedMatchIdValue.toString();
            valMap.put("preventedMatchId", preventedMatchIdValueAsString);
        }
        Long takerOrderIdValue = getTakerOrderId();
        if (takerOrderIdValue != null) {
            String takerOrderIdValueAsString = takerOrderIdValue.toString();
            valMap.put("takerOrderId", takerOrderIdValueAsString);
        }
        String makerSymbolValue = getMakerSymbol();
        if (makerSymbolValue != null) {
            String makerSymbolValueAsString = makerSymbolValue.toString();
            valMap.put("makerSymbol", makerSymbolValueAsString);
        }
        Long makerOrderIdValue = getMakerOrderId();
        if (makerOrderIdValue != null) {
            String makerOrderIdValueAsString = makerOrderIdValue.toString();
            valMap.put("makerOrderId", makerOrderIdValueAsString);
        }
        Long tradeGroupIdValue = getTradeGroupId();
        if (tradeGroupIdValue != null) {
            String tradeGroupIdValueAsString = tradeGroupIdValue.toString();
            valMap.put("tradeGroupId", tradeGroupIdValueAsString);
        }
        String selfTradePreventionModeValue = getSelfTradePreventionMode();
        if (selfTradePreventionModeValue != null) {
            String selfTradePreventionModeValueAsString = selfTradePreventionModeValue.toString();
            valMap.put("selfTradePreventionMode", selfTradePreventionModeValueAsString);
        }
        String priceValue = getPrice();
        if (priceValue != null) {
            String priceValueAsString = priceValue.toString();
            valMap.put("price", priceValueAsString);
        }
        String makerPreventedQuantityValue = getMakerPreventedQuantity();
        if (makerPreventedQuantityValue != null) {
            String makerPreventedQuantityValueAsString = makerPreventedQuantityValue.toString();
            valMap.put("makerPreventedQuantity", makerPreventedQuantityValueAsString);
        }
        Long transactTimeValue = getTransactTime();
        if (transactTimeValue != null) {
            String transactTimeValueAsString = transactTimeValue.toString();
            valMap.put("transactTime", transactTimeValueAsString);
        }

        valMap.put("timestamp", getTimestamp());
        return asciiEncode(
                valMap.keySet().stream()
                        .map(key -> key + "=" + valMap.get(key))
                        .collect(Collectors.joining("&")));
    }

    public Map<String, Object> toMap() {
        Map<String, Object> valMap = new TreeMap<String, Object>();
        valMap.put("apiKey", getApiKey());
        Object symbolValue = getSymbol();
        if (symbolValue != null) {
            valMap.put("symbol", symbolValue);
        }
        Object preventedMatchIdValue = getPreventedMatchId();
        if (preventedMatchIdValue != null) {
            valMap.put("preventedMatchId", preventedMatchIdValue);
        }
        Object takerOrderIdValue = getTakerOrderId();
        if (takerOrderIdValue != null) {
            valMap.put("takerOrderId", takerOrderIdValue);
        }
        Object makerSymbolValue = getMakerSymbol();
        if (makerSymbolValue != null) {
            valMap.put("makerSymbol", makerSymbolValue);
        }
        Object makerOrderIdValue = getMakerOrderId();
        if (makerOrderIdValue != null) {
            valMap.put("makerOrderId", makerOrderIdValue);
        }
        Object tradeGroupIdValue = getTradeGroupId();
        if (tradeGroupIdValue != null) {
            valMap.put("tradeGroupId", tradeGroupIdValue);
        }
        Object selfTradePreventionModeValue = getSelfTradePreventionMode();
        if (selfTradePreventionModeValue != null) {
            valMap.put("selfTradePreventionMode", selfTradePreventionModeValue);
        }
        Object priceValue = getPrice();
        if (priceValue != null) {
            valMap.put("price", priceValue);
        }
        Object makerPreventedQuantityValue = getMakerPreventedQuantity();
        if (makerPreventedQuantityValue != null) {
            valMap.put("makerPreventedQuantity", makerPreventedQuantityValue);
        }
        Object transactTimeValue = getTransactTime();
        if (transactTimeValue != null) {
            valMap.put("transactTime", transactTimeValue);
        }

        valMap.put("timestamp", getTimestamp());
        return valMap;
    }

    public static String asciiEncode(String s) {
        return new String(s.getBytes(), StandardCharsets.US_ASCII);
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n		");
    }
}
