/*
 * Binance Spot WebSocket API
 * OpenAPI Specifications for the Binance Spot WebSocket API  API documents:   - [Github web-socket-api documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-api.md)   - [General API information for web-socket-api on website](https://developers.binance.com/docs/binance-spot-api-docs/web-socket-api/general-api-information)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.quarkus.spot.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.vertx.core.json.Json;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.stream.Collectors;

public class OpenOrdersCancelAllResponseResultInner extends BaseDTO {
    public static final String SERIALIZED_NAME_ORDER_LIST_ID = "orderListId";

    @JsonProperty(SERIALIZED_NAME_ORDER_LIST_ID)
    
    private Long orderListId;

    public static final String SERIALIZED_NAME_CONTINGENCY_TYPE = "contingencyType";

    @JsonProperty(SERIALIZED_NAME_CONTINGENCY_TYPE)
    
    private String contingencyType;

    public static final String SERIALIZED_NAME_LIST_STATUS_TYPE = "listStatusType";

    @JsonProperty(SERIALIZED_NAME_LIST_STATUS_TYPE)
    
    private String listStatusType;

    public static final String SERIALIZED_NAME_LIST_ORDER_STATUS = "listOrderStatus";

    @JsonProperty(SERIALIZED_NAME_LIST_ORDER_STATUS)
    
    private String listOrderStatus;

    public static final String SERIALIZED_NAME_LIST_CLIENT_ORDER_ID = "listClientOrderId";

    @JsonProperty(SERIALIZED_NAME_LIST_CLIENT_ORDER_ID)
    
    private String listClientOrderId;

    public static final String SERIALIZED_NAME_TRANSACTION_TIME = "transactionTime";

    @JsonProperty(SERIALIZED_NAME_TRANSACTION_TIME)
    
    private Long transactionTime;

    public static final String SERIALIZED_NAME_SYMBOL = "symbol";

    @JsonProperty(SERIALIZED_NAME_SYMBOL)
    
    private String symbol;

    public static final String SERIALIZED_NAME_ORDERS = "orders";

    @JsonProperty(SERIALIZED_NAME_ORDERS)
    
    private List<OpenOrdersCancelAllResponseResultInnerOrdersInner> orders;

    public static final String SERIALIZED_NAME_ORDER_REPORTS = "orderReports";

    @JsonProperty(SERIALIZED_NAME_ORDER_REPORTS)
    
    private List<OpenOrdersCancelAllResponseResultInnerOrderReportsInner> orderReports;

    public static final String SERIALIZED_NAME_ORIG_CLIENT_ORDER_ID = "origClientOrderId";

    @JsonProperty(SERIALIZED_NAME_ORIG_CLIENT_ORDER_ID)
    
    private String origClientOrderId;

    public static final String SERIALIZED_NAME_ORDER_ID = "orderId";

    @JsonProperty(SERIALIZED_NAME_ORDER_ID)
    
    private Long orderId;

    public static final String SERIALIZED_NAME_CLIENT_ORDER_ID = "clientOrderId";

    @JsonProperty(SERIALIZED_NAME_CLIENT_ORDER_ID)
    
    private String clientOrderId;

    public static final String SERIALIZED_NAME_TRANSACT_TIME = "transactTime";

    @JsonProperty(SERIALIZED_NAME_TRANSACT_TIME)
    
    private Long transactTime;

    public static final String SERIALIZED_NAME_PRICE = "price";

    @JsonProperty(SERIALIZED_NAME_PRICE)
    
    private String price;

    public static final String SERIALIZED_NAME_ORIG_QTY = "origQty";

    @JsonProperty(SERIALIZED_NAME_ORIG_QTY)
    
    private String origQty;

    public static final String SERIALIZED_NAME_EXECUTED_QTY = "executedQty";

    @JsonProperty(SERIALIZED_NAME_EXECUTED_QTY)
    
    private String executedQty;

    public static final String SERIALIZED_NAME_ORIG_QUOTE_ORDER_QTY = "origQuoteOrderQty";

    @JsonProperty(SERIALIZED_NAME_ORIG_QUOTE_ORDER_QTY)
    
    private String origQuoteOrderQty;

    public static final String SERIALIZED_NAME_CUMMULATIVE_QUOTE_QTY = "cummulativeQuoteQty";

    @JsonProperty(SERIALIZED_NAME_CUMMULATIVE_QUOTE_QTY)
    
    private String cummulativeQuoteQty;

    public static final String SERIALIZED_NAME_STATUS = "status";

    @JsonProperty(SERIALIZED_NAME_STATUS)
    
    private String status;

    public static final String SERIALIZED_NAME_TIME_IN_FORCE = "timeInForce";

    @JsonProperty(SERIALIZED_NAME_TIME_IN_FORCE)
    
    private String timeInForce;

    public static final String SERIALIZED_NAME_TYPE = "type";

    @JsonProperty(SERIALIZED_NAME_TYPE)
    
    private String type;

    public static final String SERIALIZED_NAME_SIDE = "side";

    @JsonProperty(SERIALIZED_NAME_SIDE)
    
    private String side;

    public static final String SERIALIZED_NAME_STOP_PRICE = "stopPrice";

    @JsonProperty(SERIALIZED_NAME_STOP_PRICE)
    
    private String stopPrice;

    public static final String SERIALIZED_NAME_TRAILING_DELTA = "trailingDelta";

    @JsonProperty(SERIALIZED_NAME_TRAILING_DELTA)
    
    private Long trailingDelta;

    public static final String SERIALIZED_NAME_TRAILING_TIME = "trailingTime";

    @JsonProperty(SERIALIZED_NAME_TRAILING_TIME)
    
    private Long trailingTime;

    public static final String SERIALIZED_NAME_ICEBERG_QTY = "icebergQty";

    @JsonProperty(SERIALIZED_NAME_ICEBERG_QTY)
    
    private String icebergQty;

    public static final String SERIALIZED_NAME_STRATEGY_ID = "strategyId";

    @JsonProperty(SERIALIZED_NAME_STRATEGY_ID)
    
    private Long strategyId;

    public static final String SERIALIZED_NAME_STRATEGY_TYPE = "strategyType";

    @JsonProperty(SERIALIZED_NAME_STRATEGY_TYPE)
    
    private Long strategyType;

    public static final String SERIALIZED_NAME_SELF_TRADE_PREVENTION_MODE =
            "selfTradePreventionMode";

    @JsonProperty(SERIALIZED_NAME_SELF_TRADE_PREVENTION_MODE)
    
    private String selfTradePreventionMode;

    public OpenOrdersCancelAllResponseResultInner() {}

    public OpenOrdersCancelAllResponseResultInner orderListId(
             Long orderListId) {
        this.orderListId = orderListId;
        return this;
    }

    /**
     * Get orderListId
     *
     * @return orderListId
     */
    
    public Long getOrderListId() {
        return orderListId;
    }

    public void setOrderListId( Long orderListId) {
        this.orderListId = orderListId;
    }

    public OpenOrdersCancelAllResponseResultInner contingencyType(
             String contingencyType) {
        this.contingencyType = contingencyType;
        return this;
    }

    /**
     * Get contingencyType
     *
     * @return contingencyType
     */
    
    public String getContingencyType() {
        return contingencyType;
    }

    public void setContingencyType( String contingencyType) {
        this.contingencyType = contingencyType;
    }

    public OpenOrdersCancelAllResponseResultInner listStatusType(
             String listStatusType) {
        this.listStatusType = listStatusType;
        return this;
    }

    /**
     * Get listStatusType
     *
     * @return listStatusType
     */
    
    public String getListStatusType() {
        return listStatusType;
    }

    public void setListStatusType( String listStatusType) {
        this.listStatusType = listStatusType;
    }

    public OpenOrdersCancelAllResponseResultInner listOrderStatus(
             String listOrderStatus) {
        this.listOrderStatus = listOrderStatus;
        return this;
    }

    /**
     * Get listOrderStatus
     *
     * @return listOrderStatus
     */
    
    public String getListOrderStatus() {
        return listOrderStatus;
    }

    public void setListOrderStatus( String listOrderStatus) {
        this.listOrderStatus = listOrderStatus;
    }

    public OpenOrdersCancelAllResponseResultInner listClientOrderId(
             String listClientOrderId) {
        this.listClientOrderId = listClientOrderId;
        return this;
    }

    /**
     * Get listClientOrderId
     *
     * @return listClientOrderId
     */
    
    public String getListClientOrderId() {
        return listClientOrderId;
    }

    public void setListClientOrderId( String listClientOrderId) {
        this.listClientOrderId = listClientOrderId;
    }

    public OpenOrdersCancelAllResponseResultInner transactionTime(
             Long transactionTime) {
        this.transactionTime = transactionTime;
        return this;
    }

    /**
     * Get transactionTime
     *
     * @return transactionTime
     */
    
    public Long getTransactionTime() {
        return transactionTime;
    }

    public void setTransactionTime( Long transactionTime) {
        this.transactionTime = transactionTime;
    }

    public OpenOrdersCancelAllResponseResultInner symbol(
             String symbol) {
        this.symbol = symbol;
        return this;
    }

    /**
     * Get symbol
     *
     * @return symbol
     */
    
    public String getSymbol() {
        return symbol;
    }

    public void setSymbol( String symbol) {
        this.symbol = symbol;
    }

    public OpenOrdersCancelAllResponseResultInner orders(
            
                    List<OpenOrdersCancelAllResponseResultInnerOrdersInner> orders) {
        this.orders = orders;
        return this;
    }

    public OpenOrdersCancelAllResponseResultInner addOrdersItem(
            OpenOrdersCancelAllResponseResultInnerOrdersInner ordersItem) {
        if (this.orders == null) {
            this.orders = new ArrayList<>();
        }
        this.orders.add(ordersItem);
        return this;
    }

    /**
     * Get orders
     *
     * @return orders
     */
    

    public List<OpenOrdersCancelAllResponseResultInnerOrdersInner> getOrders() {
        return orders;
    }

    public void setOrders(
            
                    List<OpenOrdersCancelAllResponseResultInnerOrdersInner> orders) {
        this.orders = orders;
    }

    public OpenOrdersCancelAllResponseResultInner orderReports(
            
                    List<OpenOrdersCancelAllResponseResultInnerOrderReportsInner>
                            orderReports) {
        this.orderReports = orderReports;
        return this;
    }

    public OpenOrdersCancelAllResponseResultInner addOrderReportsItem(
            OpenOrdersCancelAllResponseResultInnerOrderReportsInner orderReportsItem) {
        if (this.orderReports == null) {
            this.orderReports = new ArrayList<>();
        }
        this.orderReports.add(orderReportsItem);
        return this;
    }

    /**
     * Get orderReports
     *
     * @return orderReports
     */
    

    public List<OpenOrdersCancelAllResponseResultInnerOrderReportsInner> getOrderReports() {
        return orderReports;
    }

    public void setOrderReports(
            
                    List<OpenOrdersCancelAllResponseResultInnerOrderReportsInner>
                            orderReports) {
        this.orderReports = orderReports;
    }

    public OpenOrdersCancelAllResponseResultInner origClientOrderId(
             String origClientOrderId) {
        this.origClientOrderId = origClientOrderId;
        return this;
    }

    /**
     * Get origClientOrderId
     *
     * @return origClientOrderId
     */
    
    public String getOrigClientOrderId() {
        return origClientOrderId;
    }

    public void setOrigClientOrderId( String origClientOrderId) {
        this.origClientOrderId = origClientOrderId;
    }

    public OpenOrdersCancelAllResponseResultInner orderId(
             Long orderId) {
        this.orderId = orderId;
        return this;
    }

    /**
     * Get orderId
     *
     * @return orderId
     */
    
    public Long getOrderId() {
        return orderId;
    }

    public void setOrderId( Long orderId) {
        this.orderId = orderId;
    }

    public OpenOrdersCancelAllResponseResultInner clientOrderId(
             String clientOrderId) {
        this.clientOrderId = clientOrderId;
        return this;
    }

    /**
     * Get clientOrderId
     *
     * @return clientOrderId
     */
    
    public String getClientOrderId() {
        return clientOrderId;
    }

    public void setClientOrderId( String clientOrderId) {
        this.clientOrderId = clientOrderId;
    }

    public OpenOrdersCancelAllResponseResultInner transactTime(
             Long transactTime) {
        this.transactTime = transactTime;
        return this;
    }

    /**
     * Get transactTime
     *
     * @return transactTime
     */
    
    public Long getTransactTime() {
        return transactTime;
    }

    public void setTransactTime( Long transactTime) {
        this.transactTime = transactTime;
    }

    public OpenOrdersCancelAllResponseResultInner price( String price) {
        this.price = price;
        return this;
    }

    /**
     * Get price
     *
     * @return price
     */
    
    public String getPrice() {
        return price;
    }

    public void setPrice( String price) {
        this.price = price;
    }

    public OpenOrdersCancelAllResponseResultInner origQty(
             String origQty) {
        this.origQty = origQty;
        return this;
    }

    /**
     * Get origQty
     *
     * @return origQty
     */
    
    public String getOrigQty() {
        return origQty;
    }

    public void setOrigQty( String origQty) {
        this.origQty = origQty;
    }

    public OpenOrdersCancelAllResponseResultInner executedQty(
             String executedQty) {
        this.executedQty = executedQty;
        return this;
    }

    /**
     * Get executedQty
     *
     * @return executedQty
     */
    
    public String getExecutedQty() {
        return executedQty;
    }

    public void setExecutedQty( String executedQty) {
        this.executedQty = executedQty;
    }

    public OpenOrdersCancelAllResponseResultInner origQuoteOrderQty(
             String origQuoteOrderQty) {
        this.origQuoteOrderQty = origQuoteOrderQty;
        return this;
    }

    /**
     * Get origQuoteOrderQty
     *
     * @return origQuoteOrderQty
     */
    
    public String getOrigQuoteOrderQty() {
        return origQuoteOrderQty;
    }

    public void setOrigQuoteOrderQty( String origQuoteOrderQty) {
        this.origQuoteOrderQty = origQuoteOrderQty;
    }

    public OpenOrdersCancelAllResponseResultInner cummulativeQuoteQty(
             String cummulativeQuoteQty) {
        this.cummulativeQuoteQty = cummulativeQuoteQty;
        return this;
    }

    /**
     * Get cummulativeQuoteQty
     *
     * @return cummulativeQuoteQty
     */
    
    public String getCummulativeQuoteQty() {
        return cummulativeQuoteQty;
    }

    public void setCummulativeQuoteQty( String cummulativeQuoteQty) {
        this.cummulativeQuoteQty = cummulativeQuoteQty;
    }

    public OpenOrdersCancelAllResponseResultInner status(
             String status) {
        this.status = status;
        return this;
    }

    /**
     * Get status
     *
     * @return status
     */
    
    public String getStatus() {
        return status;
    }

    public void setStatus( String status) {
        this.status = status;
    }

    public OpenOrdersCancelAllResponseResultInner timeInForce(
             String timeInForce) {
        this.timeInForce = timeInForce;
        return this;
    }

    /**
     * Get timeInForce
     *
     * @return timeInForce
     */
    
    public String getTimeInForce() {
        return timeInForce;
    }

    public void setTimeInForce( String timeInForce) {
        this.timeInForce = timeInForce;
    }

    public OpenOrdersCancelAllResponseResultInner type( String type) {
        this.type = type;
        return this;
    }

    /**
     * Get type
     *
     * @return type
     */
    
    public String getType() {
        return type;
    }

    public void setType( String type) {
        this.type = type;
    }

    public OpenOrdersCancelAllResponseResultInner side( String side) {
        this.side = side;
        return this;
    }

    /**
     * Get side
     *
     * @return side
     */
    
    public String getSide() {
        return side;
    }

    public void setSide( String side) {
        this.side = side;
    }

    public OpenOrdersCancelAllResponseResultInner stopPrice(
             String stopPrice) {
        this.stopPrice = stopPrice;
        return this;
    }

    /**
     * Get stopPrice
     *
     * @return stopPrice
     */
    
    public String getStopPrice() {
        return stopPrice;
    }

    public void setStopPrice( String stopPrice) {
        this.stopPrice = stopPrice;
    }

    public OpenOrdersCancelAllResponseResultInner trailingDelta(
             Long trailingDelta) {
        this.trailingDelta = trailingDelta;
        return this;
    }

    /**
     * Get trailingDelta
     *
     * @return trailingDelta
     */
    
    public Long getTrailingDelta() {
        return trailingDelta;
    }

    public void setTrailingDelta( Long trailingDelta) {
        this.trailingDelta = trailingDelta;
    }

    public OpenOrdersCancelAllResponseResultInner trailingTime(
             Long trailingTime) {
        this.trailingTime = trailingTime;
        return this;
    }

    /**
     * Get trailingTime
     *
     * @return trailingTime
     */
    
    public Long getTrailingTime() {
        return trailingTime;
    }

    public void setTrailingTime( Long trailingTime) {
        this.trailingTime = trailingTime;
    }

    public OpenOrdersCancelAllResponseResultInner icebergQty(
             String icebergQty) {
        this.icebergQty = icebergQty;
        return this;
    }

    /**
     * Get icebergQty
     *
     * @return icebergQty
     */
    
    public String getIcebergQty() {
        return icebergQty;
    }

    public void setIcebergQty( String icebergQty) {
        this.icebergQty = icebergQty;
    }

    public OpenOrdersCancelAllResponseResultInner strategyId(
             Long strategyId) {
        this.strategyId = strategyId;
        return this;
    }

    /**
     * Get strategyId
     *
     * @return strategyId
     */
    
    public Long getStrategyId() {
        return strategyId;
    }

    public void setStrategyId( Long strategyId) {
        this.strategyId = strategyId;
    }

    public OpenOrdersCancelAllResponseResultInner strategyType(
             Long strategyType) {
        this.strategyType = strategyType;
        return this;
    }

    /**
     * Get strategyType
     *
     * @return strategyType
     */
    
    public Long getStrategyType() {
        return strategyType;
    }

    public void setStrategyType( Long strategyType) {
        this.strategyType = strategyType;
    }

    public OpenOrdersCancelAllResponseResultInner selfTradePreventionMode(
             String selfTradePreventionMode) {
        this.selfTradePreventionMode = selfTradePreventionMode;
        return this;
    }

    /**
     * Get selfTradePreventionMode
     *
     * @return selfTradePreventionMode
     */
    
    public String getSelfTradePreventionMode() {
        return selfTradePreventionMode;
    }

    public void setSelfTradePreventionMode(
             String selfTradePreventionMode) {
        this.selfTradePreventionMode = selfTradePreventionMode;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OpenOrdersCancelAllResponseResultInner openOrdersCancelAllResponseResultInner =
                (OpenOrdersCancelAllResponseResultInner) o;
        return Objects.equals(this.orderListId, openOrdersCancelAllResponseResultInner.orderListId)
                && Objects.equals(
                        this.contingencyType,
                        openOrdersCancelAllResponseResultInner.contingencyType)
                && Objects.equals(
                        this.listStatusType, openOrdersCancelAllResponseResultInner.listStatusType)
                && Objects.equals(
                        this.listOrderStatus,
                        openOrdersCancelAllResponseResultInner.listOrderStatus)
                && Objects.equals(
                        this.listClientOrderId,
                        openOrdersCancelAllResponseResultInner.listClientOrderId)
                && Objects.equals(
                        this.transactionTime,
                        openOrdersCancelAllResponseResultInner.transactionTime)
                && Objects.equals(this.symbol, openOrdersCancelAllResponseResultInner.symbol)
                && Objects.equals(this.orders, openOrdersCancelAllResponseResultInner.orders)
                && Objects.equals(
                        this.orderReports, openOrdersCancelAllResponseResultInner.orderReports)
                && Objects.equals(
                        this.origClientOrderId,
                        openOrdersCancelAllResponseResultInner.origClientOrderId)
                && Objects.equals(this.orderId, openOrdersCancelAllResponseResultInner.orderId)
                && Objects.equals(
                        this.clientOrderId, openOrdersCancelAllResponseResultInner.clientOrderId)
                && Objects.equals(
                        this.transactTime, openOrdersCancelAllResponseResultInner.transactTime)
                && Objects.equals(this.price, openOrdersCancelAllResponseResultInner.price)
                && Objects.equals(this.origQty, openOrdersCancelAllResponseResultInner.origQty)
                && Objects.equals(
                        this.executedQty, openOrdersCancelAllResponseResultInner.executedQty)
                && Objects.equals(
                        this.origQuoteOrderQty,
                        openOrdersCancelAllResponseResultInner.origQuoteOrderQty)
                && Objects.equals(
                        this.cummulativeQuoteQty,
                        openOrdersCancelAllResponseResultInner.cummulativeQuoteQty)
                && Objects.equals(this.status, openOrdersCancelAllResponseResultInner.status)
                && Objects.equals(
                        this.timeInForce, openOrdersCancelAllResponseResultInner.timeInForce)
                && Objects.equals(this.type, openOrdersCancelAllResponseResultInner.type)
                && Objects.equals(this.side, openOrdersCancelAllResponseResultInner.side)
                && Objects.equals(this.stopPrice, openOrdersCancelAllResponseResultInner.stopPrice)
                && Objects.equals(
                        this.trailingDelta, openOrdersCancelAllResponseResultInner.trailingDelta)
                && Objects.equals(
                        this.trailingTime, openOrdersCancelAllResponseResultInner.trailingTime)
                && Objects.equals(
                        this.icebergQty, openOrdersCancelAllResponseResultInner.icebergQty)
                && Objects.equals(
                        this.strategyId, openOrdersCancelAllResponseResultInner.strategyId)
                && Objects.equals(
                        this.strategyType, openOrdersCancelAllResponseResultInner.strategyType)
                && Objects.equals(
                        this.selfTradePreventionMode,
                        openOrdersCancelAllResponseResultInner.selfTradePreventionMode);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                orderListId,
                contingencyType,
                listStatusType,
                listOrderStatus,
                listClientOrderId,
                transactionTime,
                symbol,
                orders,
                orderReports,
                origClientOrderId,
                orderId,
                clientOrderId,
                transactTime,
                price,
                origQty,
                executedQty,
                origQuoteOrderQty,
                cummulativeQuoteQty,
                status,
                timeInForce,
                type,
                side,
                stopPrice,
                trailingDelta,
                trailingTime,
                icebergQty,
                strategyId,
                strategyType,
                selfTradePreventionMode);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class OpenOrdersCancelAllResponseResultInner {\n");
        sb.append("		orderListId: ").append(toIndentedString(orderListId)).append("\n");
        sb.append("		contingencyType: ").append(toIndentedString(contingencyType)).append("\n");
        sb.append("		listStatusType: ").append(toIndentedString(listStatusType)).append("\n");
        sb.append("		listOrderStatus: ").append(toIndentedString(listOrderStatus)).append("\n");
        sb.append("		listClientOrderId: ").append(toIndentedString(listClientOrderId)).append("\n");
        sb.append("		transactionTime: ").append(toIndentedString(transactionTime)).append("\n");
        sb.append("		symbol: ").append(toIndentedString(symbol)).append("\n");
        sb.append("		orders: ").append(toIndentedString(orders)).append("\n");
        sb.append("		orderReports: ").append(toIndentedString(orderReports)).append("\n");
        sb.append("		origClientOrderId: ").append(toIndentedString(origClientOrderId)).append("\n");
        sb.append("		orderId: ").append(toIndentedString(orderId)).append("\n");
        sb.append("		clientOrderId: ").append(toIndentedString(clientOrderId)).append("\n");
        sb.append("		transactTime: ").append(toIndentedString(transactTime)).append("\n");
        sb.append("		price: ").append(toIndentedString(price)).append("\n");
        sb.append("		origQty: ").append(toIndentedString(origQty)).append("\n");
        sb.append("		executedQty: ").append(toIndentedString(executedQty)).append("\n");
        sb.append("		origQuoteOrderQty: ").append(toIndentedString(origQuoteOrderQty)).append("\n");
        sb.append("		cummulativeQuoteQty: ")
                .append(toIndentedString(cummulativeQuoteQty))
                .append("\n");
        sb.append("		status: ").append(toIndentedString(status)).append("\n");
        sb.append("		timeInForce: ").append(toIndentedString(timeInForce)).append("\n");
        sb.append("		type: ").append(toIndentedString(type)).append("\n");
        sb.append("		side: ").append(toIndentedString(side)).append("\n");
        sb.append("		stopPrice: ").append(toIndentedString(stopPrice)).append("\n");
        sb.append("		trailingDelta: ").append(toIndentedString(trailingDelta)).append("\n");
        sb.append("		trailingTime: ").append(toIndentedString(trailingTime)).append("\n");
        sb.append("		icebergQty: ").append(toIndentedString(icebergQty)).append("\n");
        sb.append("		strategyId: ").append(toIndentedString(strategyId)).append("\n");
        sb.append("		strategyType: ").append(toIndentedString(strategyType)).append("\n");
        sb.append("		selfTradePreventionMode: ")
                .append(toIndentedString(selfTradePreventionMode))
                .append("\n");
        sb.append("}");
        return sb.toString();
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();
        Map<String, String> valMap = new TreeMap<String, String>();
        valMap.put("apiKey", getApiKey());
        Long orderListIdValue = getOrderListId();
        if (orderListIdValue != null) {
            String orderListIdValueAsString = orderListIdValue.toString();
            valMap.put("orderListId", orderListIdValueAsString);
        }
        String contingencyTypeValue = getContingencyType();
        if (contingencyTypeValue != null) {
            String contingencyTypeValueAsString = contingencyTypeValue.toString();
            valMap.put("contingencyType", contingencyTypeValueAsString);
        }
        String listStatusTypeValue = getListStatusType();
        if (listStatusTypeValue != null) {
            String listStatusTypeValueAsString = listStatusTypeValue.toString();
            valMap.put("listStatusType", listStatusTypeValueAsString);
        }
        String listOrderStatusValue = getListOrderStatus();
        if (listOrderStatusValue != null) {
            String listOrderStatusValueAsString = listOrderStatusValue.toString();
            valMap.put("listOrderStatus", listOrderStatusValueAsString);
        }
        String listClientOrderIdValue = getListClientOrderId();
        if (listClientOrderIdValue != null) {
            String listClientOrderIdValueAsString = listClientOrderIdValue.toString();
            valMap.put("listClientOrderId", listClientOrderIdValueAsString);
        }
        Long transactionTimeValue = getTransactionTime();
        if (transactionTimeValue != null) {
            String transactionTimeValueAsString = transactionTimeValue.toString();
            valMap.put("transactionTime", transactionTimeValueAsString);
        }
        String symbolValue = getSymbol();
        if (symbolValue != null) {
            String symbolValueAsString = symbolValue.toString();
            valMap.put("symbol", symbolValueAsString);
        }
        List<OpenOrdersCancelAllResponseResultInnerOrdersInner> ordersValue = getOrders();
        if (ordersValue != null) {
            String ordersValueAsString = Json.encode(ordersValue);
            valMap.put("orders", ordersValueAsString);
        }
        List<OpenOrdersCancelAllResponseResultInnerOrderReportsInner> orderReportsValue =
                getOrderReports();
        if (orderReportsValue != null) {
            String orderReportsValueAsString = Json.encode(orderReportsValue);
            valMap.put("orderReports", orderReportsValueAsString);
        }
        String origClientOrderIdValue = getOrigClientOrderId();
        if (origClientOrderIdValue != null) {
            String origClientOrderIdValueAsString = origClientOrderIdValue.toString();
            valMap.put("origClientOrderId", origClientOrderIdValueAsString);
        }
        Long orderIdValue = getOrderId();
        if (orderIdValue != null) {
            String orderIdValueAsString = orderIdValue.toString();
            valMap.put("orderId", orderIdValueAsString);
        }
        String clientOrderIdValue = getClientOrderId();
        if (clientOrderIdValue != null) {
            String clientOrderIdValueAsString = clientOrderIdValue.toString();
            valMap.put("clientOrderId", clientOrderIdValueAsString);
        }
        Long transactTimeValue = getTransactTime();
        if (transactTimeValue != null) {
            String transactTimeValueAsString = transactTimeValue.toString();
            valMap.put("transactTime", transactTimeValueAsString);
        }
        String priceValue = getPrice();
        if (priceValue != null) {
            String priceValueAsString = priceValue.toString();
            valMap.put("price", priceValueAsString);
        }
        String origQtyValue = getOrigQty();
        if (origQtyValue != null) {
            String origQtyValueAsString = origQtyValue.toString();
            valMap.put("origQty", origQtyValueAsString);
        }
        String executedQtyValue = getExecutedQty();
        if (executedQtyValue != null) {
            String executedQtyValueAsString = executedQtyValue.toString();
            valMap.put("executedQty", executedQtyValueAsString);
        }
        String origQuoteOrderQtyValue = getOrigQuoteOrderQty();
        if (origQuoteOrderQtyValue != null) {
            String origQuoteOrderQtyValueAsString = origQuoteOrderQtyValue.toString();
            valMap.put("origQuoteOrderQty", origQuoteOrderQtyValueAsString);
        }
        String cummulativeQuoteQtyValue = getCummulativeQuoteQty();
        if (cummulativeQuoteQtyValue != null) {
            String cummulativeQuoteQtyValueAsString = cummulativeQuoteQtyValue.toString();
            valMap.put("cummulativeQuoteQty", cummulativeQuoteQtyValueAsString);
        }
        String statusValue = getStatus();
        if (statusValue != null) {
            String statusValueAsString = statusValue.toString();
            valMap.put("status", statusValueAsString);
        }
        String timeInForceValue = getTimeInForce();
        if (timeInForceValue != null) {
            String timeInForceValueAsString = timeInForceValue.toString();
            valMap.put("timeInForce", timeInForceValueAsString);
        }
        String typeValue = getType();
        if (typeValue != null) {
            String typeValueAsString = typeValue.toString();
            valMap.put("type", typeValueAsString);
        }
        String sideValue = getSide();
        if (sideValue != null) {
            String sideValueAsString = sideValue.toString();
            valMap.put("side", sideValueAsString);
        }
        String stopPriceValue = getStopPrice();
        if (stopPriceValue != null) {
            String stopPriceValueAsString = stopPriceValue.toString();
            valMap.put("stopPrice", stopPriceValueAsString);
        }
        Long trailingDeltaValue = getTrailingDelta();
        if (trailingDeltaValue != null) {
            String trailingDeltaValueAsString = trailingDeltaValue.toString();
            valMap.put("trailingDelta", trailingDeltaValueAsString);
        }
        Long trailingTimeValue = getTrailingTime();
        if (trailingTimeValue != null) {
            String trailingTimeValueAsString = trailingTimeValue.toString();
            valMap.put("trailingTime", trailingTimeValueAsString);
        }
        String icebergQtyValue = getIcebergQty();
        if (icebergQtyValue != null) {
            String icebergQtyValueAsString = icebergQtyValue.toString();
            valMap.put("icebergQty", icebergQtyValueAsString);
        }
        Long strategyIdValue = getStrategyId();
        if (strategyIdValue != null) {
            String strategyIdValueAsString = strategyIdValue.toString();
            valMap.put("strategyId", strategyIdValueAsString);
        }
        Long strategyTypeValue = getStrategyType();
        if (strategyTypeValue != null) {
            String strategyTypeValueAsString = strategyTypeValue.toString();
            valMap.put("strategyType", strategyTypeValueAsString);
        }
        String selfTradePreventionModeValue = getSelfTradePreventionMode();
        if (selfTradePreventionModeValue != null) {
            String selfTradePreventionModeValueAsString = selfTradePreventionModeValue.toString();
            valMap.put("selfTradePreventionMode", selfTradePreventionModeValueAsString);
        }

        valMap.put("timestamp", getTimestamp());
        return asciiEncode(
                valMap.keySet().stream()
                        .map(key -> key + "=" + valMap.get(key))
                        .collect(Collectors.joining("&")));
    }

    public Map<String, Object> toMap() {
        Map<String, Object> valMap = new TreeMap<String, Object>();
        valMap.put("apiKey", getApiKey());
        Object orderListIdValue = getOrderListId();
        if (orderListIdValue != null) {
            valMap.put("orderListId", orderListIdValue);
        }
        Object contingencyTypeValue = getContingencyType();
        if (contingencyTypeValue != null) {
            valMap.put("contingencyType", contingencyTypeValue);
        }
        Object listStatusTypeValue = getListStatusType();
        if (listStatusTypeValue != null) {
            valMap.put("listStatusType", listStatusTypeValue);
        }
        Object listOrderStatusValue = getListOrderStatus();
        if (listOrderStatusValue != null) {
            valMap.put("listOrderStatus", listOrderStatusValue);
        }
        Object listClientOrderIdValue = getListClientOrderId();
        if (listClientOrderIdValue != null) {
            valMap.put("listClientOrderId", listClientOrderIdValue);
        }
        Object transactionTimeValue = getTransactionTime();
        if (transactionTimeValue != null) {
            valMap.put("transactionTime", transactionTimeValue);
        }
        Object symbolValue = getSymbol();
        if (symbolValue != null) {
            valMap.put("symbol", symbolValue);
        }
        Object ordersValue = getOrders();
        if (ordersValue != null) {
            valMap.put("orders", ordersValue);
        }
        Object orderReportsValue = getOrderReports();
        if (orderReportsValue != null) {
            valMap.put("orderReports", orderReportsValue);
        }
        Object origClientOrderIdValue = getOrigClientOrderId();
        if (origClientOrderIdValue != null) {
            valMap.put("origClientOrderId", origClientOrderIdValue);
        }
        Object orderIdValue = getOrderId();
        if (orderIdValue != null) {
            valMap.put("orderId", orderIdValue);
        }
        Object clientOrderIdValue = getClientOrderId();
        if (clientOrderIdValue != null) {
            valMap.put("clientOrderId", clientOrderIdValue);
        }
        Object transactTimeValue = getTransactTime();
        if (transactTimeValue != null) {
            valMap.put("transactTime", transactTimeValue);
        }
        Object priceValue = getPrice();
        if (priceValue != null) {
            valMap.put("price", priceValue);
        }
        Object origQtyValue = getOrigQty();
        if (origQtyValue != null) {
            valMap.put("origQty", origQtyValue);
        }
        Object executedQtyValue = getExecutedQty();
        if (executedQtyValue != null) {
            valMap.put("executedQty", executedQtyValue);
        }
        Object origQuoteOrderQtyValue = getOrigQuoteOrderQty();
        if (origQuoteOrderQtyValue != null) {
            valMap.put("origQuoteOrderQty", origQuoteOrderQtyValue);
        }
        Object cummulativeQuoteQtyValue = getCummulativeQuoteQty();
        if (cummulativeQuoteQtyValue != null) {
            valMap.put("cummulativeQuoteQty", cummulativeQuoteQtyValue);
        }
        Object statusValue = getStatus();
        if (statusValue != null) {
            valMap.put("status", statusValue);
        }
        Object timeInForceValue = getTimeInForce();
        if (timeInForceValue != null) {
            valMap.put("timeInForce", timeInForceValue);
        }
        Object typeValue = getType();
        if (typeValue != null) {
            valMap.put("type", typeValue);
        }
        Object sideValue = getSide();
        if (sideValue != null) {
            valMap.put("side", sideValue);
        }
        Object stopPriceValue = getStopPrice();
        if (stopPriceValue != null) {
            valMap.put("stopPrice", stopPriceValue);
        }
        Object trailingDeltaValue = getTrailingDelta();
        if (trailingDeltaValue != null) {
            valMap.put("trailingDelta", trailingDeltaValue);
        }
        Object trailingTimeValue = getTrailingTime();
        if (trailingTimeValue != null) {
            valMap.put("trailingTime", trailingTimeValue);
        }
        Object icebergQtyValue = getIcebergQty();
        if (icebergQtyValue != null) {
            valMap.put("icebergQty", icebergQtyValue);
        }
        Object strategyIdValue = getStrategyId();
        if (strategyIdValue != null) {
            valMap.put("strategyId", strategyIdValue);
        }
        Object strategyTypeValue = getStrategyType();
        if (strategyTypeValue != null) {
            valMap.put("strategyType", strategyTypeValue);
        }
        Object selfTradePreventionModeValue = getSelfTradePreventionMode();
        if (selfTradePreventionModeValue != null) {
            valMap.put("selfTradePreventionMode", selfTradePreventionModeValue);
        }

        valMap.put("timestamp", getTimestamp());
        return valMap;
    }

    public static String asciiEncode(String s) {
        return new String(s.getBytes(), StandardCharsets.US_ASCII);
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n		");
    }

}
