/*
 * Binance Spot WebSocket API
 * OpenAPI Specifications for the Binance Spot WebSocket API  API documents:   - [Github web-socket-api documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-api.md)   - [General API information for web-socket-api on website](https://developers.binance.com/docs/binance-spot-api-docs/web-socket-api/general-api-information)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.quarkus.spot.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.stream.Collectors;

public class OrderAmendKeepPriorityResponseResultAmendedOrder extends BaseDTO {
    public static final String SERIALIZED_NAME_SYMBOL = "symbol";

    @JsonProperty(SERIALIZED_NAME_SYMBOL)
    
    private String symbol;

    public static final String SERIALIZED_NAME_ORDER_ID = "orderId";

    @JsonProperty(SERIALIZED_NAME_ORDER_ID)
    
    private Long orderId;

    public static final String SERIALIZED_NAME_ORDER_LIST_ID = "orderListId";

    @JsonProperty(SERIALIZED_NAME_ORDER_LIST_ID)
    
    private Long orderListId;

    public static final String SERIALIZED_NAME_ORIG_CLIENT_ORDER_ID = "origClientOrderId";

    @JsonProperty(SERIALIZED_NAME_ORIG_CLIENT_ORDER_ID)
    
    private String origClientOrderId;

    public static final String SERIALIZED_NAME_CLIENT_ORDER_ID = "clientOrderId";

    @JsonProperty(SERIALIZED_NAME_CLIENT_ORDER_ID)
    
    private String clientOrderId;

    public static final String SERIALIZED_NAME_PRICE = "price";

    @JsonProperty(SERIALIZED_NAME_PRICE)
    
    private String price;

    public static final String SERIALIZED_NAME_QTY = "qty";

    @JsonProperty(SERIALIZED_NAME_QTY)
    
    private String qty;

    public static final String SERIALIZED_NAME_EXECUTED_QTY = "executedQty";

    @JsonProperty(SERIALIZED_NAME_EXECUTED_QTY)
    
    private String executedQty;

    public static final String SERIALIZED_NAME_PREVENTED_QTY = "preventedQty";

    @JsonProperty(SERIALIZED_NAME_PREVENTED_QTY)
    
    private String preventedQty;

    public static final String SERIALIZED_NAME_QUOTE_ORDER_QTY = "quoteOrderQty";

    @JsonProperty(SERIALIZED_NAME_QUOTE_ORDER_QTY)
    
    private String quoteOrderQty;

    public static final String SERIALIZED_NAME_CUMULATIVE_QUOTE_QTY = "cumulativeQuoteQty";

    @JsonProperty(SERIALIZED_NAME_CUMULATIVE_QUOTE_QTY)
    
    private String cumulativeQuoteQty;

    public static final String SERIALIZED_NAME_STATUS = "status";

    @JsonProperty(SERIALIZED_NAME_STATUS)
    
    private String status;

    public static final String SERIALIZED_NAME_TIME_IN_FORCE = "timeInForce";

    @JsonProperty(SERIALIZED_NAME_TIME_IN_FORCE)
    
    private String timeInForce;

    public static final String SERIALIZED_NAME_TYPE = "type";

    @JsonProperty(SERIALIZED_NAME_TYPE)
    
    private String type;

    public static final String SERIALIZED_NAME_SIDE = "side";

    @JsonProperty(SERIALIZED_NAME_SIDE)
    
    private String side;

    public static final String SERIALIZED_NAME_WORKING_TIME = "workingTime";

    @JsonProperty(SERIALIZED_NAME_WORKING_TIME)
    
    private Long workingTime;

    public static final String SERIALIZED_NAME_SELF_TRADE_PREVENTION_MODE =
            "selfTradePreventionMode";

    @JsonProperty(SERIALIZED_NAME_SELF_TRADE_PREVENTION_MODE)
    
    private String selfTradePreventionMode;

    public OrderAmendKeepPriorityResponseResultAmendedOrder() {}

    public OrderAmendKeepPriorityResponseResultAmendedOrder symbol(
             String symbol) {
        this.symbol = symbol;
        return this;
    }

    /**
     * Get symbol
     *
     * @return symbol
     */
    
    public String getSymbol() {
        return symbol;
    }

    public void setSymbol( String symbol) {
        this.symbol = symbol;
    }

    public OrderAmendKeepPriorityResponseResultAmendedOrder orderId(
             Long orderId) {
        this.orderId = orderId;
        return this;
    }

    /**
     * Get orderId
     *
     * @return orderId
     */
    
    public Long getOrderId() {
        return orderId;
    }

    public void setOrderId( Long orderId) {
        this.orderId = orderId;
    }

    public OrderAmendKeepPriorityResponseResultAmendedOrder orderListId(
             Long orderListId) {
        this.orderListId = orderListId;
        return this;
    }

    /**
     * Get orderListId
     *
     * @return orderListId
     */
    
    public Long getOrderListId() {
        return orderListId;
    }

    public void setOrderListId( Long orderListId) {
        this.orderListId = orderListId;
    }

    public OrderAmendKeepPriorityResponseResultAmendedOrder origClientOrderId(
             String origClientOrderId) {
        this.origClientOrderId = origClientOrderId;
        return this;
    }

    /**
     * Get origClientOrderId
     *
     * @return origClientOrderId
     */
    
    public String getOrigClientOrderId() {
        return origClientOrderId;
    }

    public void setOrigClientOrderId( String origClientOrderId) {
        this.origClientOrderId = origClientOrderId;
    }

    public OrderAmendKeepPriorityResponseResultAmendedOrder clientOrderId(
             String clientOrderId) {
        this.clientOrderId = clientOrderId;
        return this;
    }

    /**
     * Get clientOrderId
     *
     * @return clientOrderId
     */
    
    public String getClientOrderId() {
        return clientOrderId;
    }

    public void setClientOrderId( String clientOrderId) {
        this.clientOrderId = clientOrderId;
    }

    public OrderAmendKeepPriorityResponseResultAmendedOrder price(
             String price) {
        this.price = price;
        return this;
    }

    /**
     * Get price
     *
     * @return price
     */
    
    public String getPrice() {
        return price;
    }

    public void setPrice( String price) {
        this.price = price;
    }

    public OrderAmendKeepPriorityResponseResultAmendedOrder qty(
             String qty) {
        this.qty = qty;
        return this;
    }

    /**
     * Get qty
     *
     * @return qty
     */
    
    public String getQty() {
        return qty;
    }

    public void setQty( String qty) {
        this.qty = qty;
    }

    public OrderAmendKeepPriorityResponseResultAmendedOrder executedQty(
             String executedQty) {
        this.executedQty = executedQty;
        return this;
    }

    /**
     * Get executedQty
     *
     * @return executedQty
     */
    
    public String getExecutedQty() {
        return executedQty;
    }

    public void setExecutedQty( String executedQty) {
        this.executedQty = executedQty;
    }

    public OrderAmendKeepPriorityResponseResultAmendedOrder preventedQty(
             String preventedQty) {
        this.preventedQty = preventedQty;
        return this;
    }

    /**
     * Get preventedQty
     *
     * @return preventedQty
     */
    
    public String getPreventedQty() {
        return preventedQty;
    }

    public void setPreventedQty( String preventedQty) {
        this.preventedQty = preventedQty;
    }

    public OrderAmendKeepPriorityResponseResultAmendedOrder quoteOrderQty(
             String quoteOrderQty) {
        this.quoteOrderQty = quoteOrderQty;
        return this;
    }

    /**
     * Get quoteOrderQty
     *
     * @return quoteOrderQty
     */
    
    public String getQuoteOrderQty() {
        return quoteOrderQty;
    }

    public void setQuoteOrderQty( String quoteOrderQty) {
        this.quoteOrderQty = quoteOrderQty;
    }

    public OrderAmendKeepPriorityResponseResultAmendedOrder cumulativeQuoteQty(
             String cumulativeQuoteQty) {
        this.cumulativeQuoteQty = cumulativeQuoteQty;
        return this;
    }

    /**
     * Get cumulativeQuoteQty
     *
     * @return cumulativeQuoteQty
     */
    
    public String getCumulativeQuoteQty() {
        return cumulativeQuoteQty;
    }

    public void setCumulativeQuoteQty( String cumulativeQuoteQty) {
        this.cumulativeQuoteQty = cumulativeQuoteQty;
    }

    public OrderAmendKeepPriorityResponseResultAmendedOrder status(
             String status) {
        this.status = status;
        return this;
    }

    /**
     * Get status
     *
     * @return status
     */
    
    public String getStatus() {
        return status;
    }

    public void setStatus( String status) {
        this.status = status;
    }

    public OrderAmendKeepPriorityResponseResultAmendedOrder timeInForce(
             String timeInForce) {
        this.timeInForce = timeInForce;
        return this;
    }

    /**
     * Get timeInForce
     *
     * @return timeInForce
     */
    
    public String getTimeInForce() {
        return timeInForce;
    }

    public void setTimeInForce( String timeInForce) {
        this.timeInForce = timeInForce;
    }

    public OrderAmendKeepPriorityResponseResultAmendedOrder type(
             String type) {
        this.type = type;
        return this;
    }

    /**
     * Get type
     *
     * @return type
     */
    
    public String getType() {
        return type;
    }

    public void setType( String type) {
        this.type = type;
    }

    public OrderAmendKeepPriorityResponseResultAmendedOrder side(
             String side) {
        this.side = side;
        return this;
    }

    /**
     * Get side
     *
     * @return side
     */
    
    public String getSide() {
        return side;
    }

    public void setSide( String side) {
        this.side = side;
    }

    public OrderAmendKeepPriorityResponseResultAmendedOrder workingTime(
             Long workingTime) {
        this.workingTime = workingTime;
        return this;
    }

    /**
     * Get workingTime
     *
     * @return workingTime
     */
    
    public Long getWorkingTime() {
        return workingTime;
    }

    public void setWorkingTime( Long workingTime) {
        this.workingTime = workingTime;
    }

    public OrderAmendKeepPriorityResponseResultAmendedOrder selfTradePreventionMode(
             String selfTradePreventionMode) {
        this.selfTradePreventionMode = selfTradePreventionMode;
        return this;
    }

    /**
     * Get selfTradePreventionMode
     *
     * @return selfTradePreventionMode
     */
    
    public String getSelfTradePreventionMode() {
        return selfTradePreventionMode;
    }

    public void setSelfTradePreventionMode(
             String selfTradePreventionMode) {
        this.selfTradePreventionMode = selfTradePreventionMode;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OrderAmendKeepPriorityResponseResultAmendedOrder
                orderAmendKeepPriorityResponseResultAmendedOrder =
                        (OrderAmendKeepPriorityResponseResultAmendedOrder) o;
        return Objects.equals(this.symbol, orderAmendKeepPriorityResponseResultAmendedOrder.symbol)
                && Objects.equals(
                        this.orderId, orderAmendKeepPriorityResponseResultAmendedOrder.orderId)
                && Objects.equals(
                        this.orderListId,
                        orderAmendKeepPriorityResponseResultAmendedOrder.orderListId)
                && Objects.equals(
                        this.origClientOrderId,
                        orderAmendKeepPriorityResponseResultAmendedOrder.origClientOrderId)
                && Objects.equals(
                        this.clientOrderId,
                        orderAmendKeepPriorityResponseResultAmendedOrder.clientOrderId)
                && Objects.equals(
                        this.price, orderAmendKeepPriorityResponseResultAmendedOrder.price)
                && Objects.equals(this.qty, orderAmendKeepPriorityResponseResultAmendedOrder.qty)
                && Objects.equals(
                        this.executedQty,
                        orderAmendKeepPriorityResponseResultAmendedOrder.executedQty)
                && Objects.equals(
                        this.preventedQty,
                        orderAmendKeepPriorityResponseResultAmendedOrder.preventedQty)
                && Objects.equals(
                        this.quoteOrderQty,
                        orderAmendKeepPriorityResponseResultAmendedOrder.quoteOrderQty)
                && Objects.equals(
                        this.cumulativeQuoteQty,
                        orderAmendKeepPriorityResponseResultAmendedOrder.cumulativeQuoteQty)
                && Objects.equals(
                        this.status, orderAmendKeepPriorityResponseResultAmendedOrder.status)
                && Objects.equals(
                        this.timeInForce,
                        orderAmendKeepPriorityResponseResultAmendedOrder.timeInForce)
                && Objects.equals(this.type, orderAmendKeepPriorityResponseResultAmendedOrder.type)
                && Objects.equals(this.side, orderAmendKeepPriorityResponseResultAmendedOrder.side)
                && Objects.equals(
                        this.workingTime,
                        orderAmendKeepPriorityResponseResultAmendedOrder.workingTime)
                && Objects.equals(
                        this.selfTradePreventionMode,
                        orderAmendKeepPriorityResponseResultAmendedOrder.selfTradePreventionMode);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                symbol,
                orderId,
                orderListId,
                origClientOrderId,
                clientOrderId,
                price,
                qty,
                executedQty,
                preventedQty,
                quoteOrderQty,
                cumulativeQuoteQty,
                status,
                timeInForce,
                type,
                side,
                workingTime,
                selfTradePreventionMode);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class OrderAmendKeepPriorityResponseResultAmendedOrder {\n");
        sb.append("		symbol: ").append(toIndentedString(symbol)).append("\n");
        sb.append("		orderId: ").append(toIndentedString(orderId)).append("\n");
        sb.append("		orderListId: ").append(toIndentedString(orderListId)).append("\n");
        sb.append("		origClientOrderId: ").append(toIndentedString(origClientOrderId)).append("\n");
        sb.append("		clientOrderId: ").append(toIndentedString(clientOrderId)).append("\n");
        sb.append("		price: ").append(toIndentedString(price)).append("\n");
        sb.append("		qty: ").append(toIndentedString(qty)).append("\n");
        sb.append("		executedQty: ").append(toIndentedString(executedQty)).append("\n");
        sb.append("		preventedQty: ").append(toIndentedString(preventedQty)).append("\n");
        sb.append("		quoteOrderQty: ").append(toIndentedString(quoteOrderQty)).append("\n");
        sb.append("		cumulativeQuoteQty: ")
                .append(toIndentedString(cumulativeQuoteQty))
                .append("\n");
        sb.append("		status: ").append(toIndentedString(status)).append("\n");
        sb.append("		timeInForce: ").append(toIndentedString(timeInForce)).append("\n");
        sb.append("		type: ").append(toIndentedString(type)).append("\n");
        sb.append("		side: ").append(toIndentedString(side)).append("\n");
        sb.append("		workingTime: ").append(toIndentedString(workingTime)).append("\n");
        sb.append("		selfTradePreventionMode: ")
                .append(toIndentedString(selfTradePreventionMode))
                .append("\n");
        sb.append("}");
        return sb.toString();
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();
        Map<String, String> valMap = new TreeMap<String, String>();
        valMap.put("apiKey", getApiKey());
        String symbolValue = getSymbol();
        if (symbolValue != null) {
            String symbolValueAsString = symbolValue.toString();
            valMap.put("symbol", symbolValueAsString);
        }
        Long orderIdValue = getOrderId();
        if (orderIdValue != null) {
            String orderIdValueAsString = orderIdValue.toString();
            valMap.put("orderId", orderIdValueAsString);
        }
        Long orderListIdValue = getOrderListId();
        if (orderListIdValue != null) {
            String orderListIdValueAsString = orderListIdValue.toString();
            valMap.put("orderListId", orderListIdValueAsString);
        }
        String origClientOrderIdValue = getOrigClientOrderId();
        if (origClientOrderIdValue != null) {
            String origClientOrderIdValueAsString = origClientOrderIdValue.toString();
            valMap.put("origClientOrderId", origClientOrderIdValueAsString);
        }
        String clientOrderIdValue = getClientOrderId();
        if (clientOrderIdValue != null) {
            String clientOrderIdValueAsString = clientOrderIdValue.toString();
            valMap.put("clientOrderId", clientOrderIdValueAsString);
        }
        String priceValue = getPrice();
        if (priceValue != null) {
            String priceValueAsString = priceValue.toString();
            valMap.put("price", priceValueAsString);
        }
        String qtyValue = getQty();
        if (qtyValue != null) {
            String qtyValueAsString = qtyValue.toString();
            valMap.put("qty", qtyValueAsString);
        }
        String executedQtyValue = getExecutedQty();
        if (executedQtyValue != null) {
            String executedQtyValueAsString = executedQtyValue.toString();
            valMap.put("executedQty", executedQtyValueAsString);
        }
        String preventedQtyValue = getPreventedQty();
        if (preventedQtyValue != null) {
            String preventedQtyValueAsString = preventedQtyValue.toString();
            valMap.put("preventedQty", preventedQtyValueAsString);
        }
        String quoteOrderQtyValue = getQuoteOrderQty();
        if (quoteOrderQtyValue != null) {
            String quoteOrderQtyValueAsString = quoteOrderQtyValue.toString();
            valMap.put("quoteOrderQty", quoteOrderQtyValueAsString);
        }
        String cumulativeQuoteQtyValue = getCumulativeQuoteQty();
        if (cumulativeQuoteQtyValue != null) {
            String cumulativeQuoteQtyValueAsString = cumulativeQuoteQtyValue.toString();
            valMap.put("cumulativeQuoteQty", cumulativeQuoteQtyValueAsString);
        }
        String statusValue = getStatus();
        if (statusValue != null) {
            String statusValueAsString = statusValue.toString();
            valMap.put("status", statusValueAsString);
        }
        String timeInForceValue = getTimeInForce();
        if (timeInForceValue != null) {
            String timeInForceValueAsString = timeInForceValue.toString();
            valMap.put("timeInForce", timeInForceValueAsString);
        }
        String typeValue = getType();
        if (typeValue != null) {
            String typeValueAsString = typeValue.toString();
            valMap.put("type", typeValueAsString);
        }
        String sideValue = getSide();
        if (sideValue != null) {
            String sideValueAsString = sideValue.toString();
            valMap.put("side", sideValueAsString);
        }
        Long workingTimeValue = getWorkingTime();
        if (workingTimeValue != null) {
            String workingTimeValueAsString = workingTimeValue.toString();
            valMap.put("workingTime", workingTimeValueAsString);
        }
        String selfTradePreventionModeValue = getSelfTradePreventionMode();
        if (selfTradePreventionModeValue != null) {
            String selfTradePreventionModeValueAsString = selfTradePreventionModeValue.toString();
            valMap.put("selfTradePreventionMode", selfTradePreventionModeValueAsString);
        }

        valMap.put("timestamp", getTimestamp());
        return asciiEncode(
                valMap.keySet().stream()
                        .map(key -> key + "=" + valMap.get(key))
                        .collect(Collectors.joining("&")));
    }

    public Map<String, Object> toMap() {
        Map<String, Object> valMap = new TreeMap<String, Object>();
        valMap.put("apiKey", getApiKey());
        Object symbolValue = getSymbol();
        if (symbolValue != null) {
            valMap.put("symbol", symbolValue);
        }
        Object orderIdValue = getOrderId();
        if (orderIdValue != null) {
            valMap.put("orderId", orderIdValue);
        }
        Object orderListIdValue = getOrderListId();
        if (orderListIdValue != null) {
            valMap.put("orderListId", orderListIdValue);
        }
        Object origClientOrderIdValue = getOrigClientOrderId();
        if (origClientOrderIdValue != null) {
            valMap.put("origClientOrderId", origClientOrderIdValue);
        }
        Object clientOrderIdValue = getClientOrderId();
        if (clientOrderIdValue != null) {
            valMap.put("clientOrderId", clientOrderIdValue);
        }
        Object priceValue = getPrice();
        if (priceValue != null) {
            valMap.put("price", priceValue);
        }
        Object qtyValue = getQty();
        if (qtyValue != null) {
            valMap.put("qty", qtyValue);
        }
        Object executedQtyValue = getExecutedQty();
        if (executedQtyValue != null) {
            valMap.put("executedQty", executedQtyValue);
        }
        Object preventedQtyValue = getPreventedQty();
        if (preventedQtyValue != null) {
            valMap.put("preventedQty", preventedQtyValue);
        }
        Object quoteOrderQtyValue = getQuoteOrderQty();
        if (quoteOrderQtyValue != null) {
            valMap.put("quoteOrderQty", quoteOrderQtyValue);
        }
        Object cumulativeQuoteQtyValue = getCumulativeQuoteQty();
        if (cumulativeQuoteQtyValue != null) {
            valMap.put("cumulativeQuoteQty", cumulativeQuoteQtyValue);
        }
        Object statusValue = getStatus();
        if (statusValue != null) {
            valMap.put("status", statusValue);
        }
        Object timeInForceValue = getTimeInForce();
        if (timeInForceValue != null) {
            valMap.put("timeInForce", timeInForceValue);
        }
        Object typeValue = getType();
        if (typeValue != null) {
            valMap.put("type", typeValue);
        }
        Object sideValue = getSide();
        if (sideValue != null) {
            valMap.put("side", sideValue);
        }
        Object workingTimeValue = getWorkingTime();
        if (workingTimeValue != null) {
            valMap.put("workingTime", workingTimeValue);
        }
        Object selfTradePreventionModeValue = getSelfTradePreventionMode();
        if (selfTradePreventionModeValue != null) {
            valMap.put("selfTradePreventionMode", selfTradePreventionModeValue);
        }

        valMap.put("timestamp", getTimestamp());
        return valMap;
    }

    public static String asciiEncode(String s) {
        return new String(s.getBytes(), StandardCharsets.US_ASCII);
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n		");
    }

}
