/*
 * Binance Spot WebSocket API
 * OpenAPI Specifications for the Binance Spot WebSocket API  API documents:   - [Github web-socket-api documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-api.md)   - [General API information for web-socket-api on website](https://developers.binance.com/docs/binance-spot-api-docs/web-socket-api/general-api-information)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.quarkus.spot.model;

import com.binance.connector.client.common.DecimalFormatter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.stream.Collectors;


/** OrderCancelRequest */
@JsonInclude(JsonInclude.Include.NON_NULL)
public class OrderCancelRequest extends BaseDTO {
    public static final String SERIALIZED_NAME_SYMBOL = "symbol";

    @JsonProperty(SERIALIZED_NAME_SYMBOL)

    private String symbol;

    public static final String SERIALIZED_NAME_ORDER_ID = "orderId";

    @JsonProperty(SERIALIZED_NAME_ORDER_ID)
    
    private Long orderId;

    public static final String SERIALIZED_NAME_ORIG_CLIENT_ORDER_ID = "origClientOrderId";

    @JsonProperty(SERIALIZED_NAME_ORIG_CLIENT_ORDER_ID)
    
    private String origClientOrderId;

    public static final String SERIALIZED_NAME_NEW_CLIENT_ORDER_ID = "newClientOrderId";

    @JsonProperty(SERIALIZED_NAME_NEW_CLIENT_ORDER_ID)
    
    private String newClientOrderId;

    public static final String SERIALIZED_NAME_CANCEL_RESTRICTIONS = "cancelRestrictions";

    @JsonProperty(SERIALIZED_NAME_CANCEL_RESTRICTIONS)
    
    private CancelRestrictions cancelRestrictions;

    public static final String SERIALIZED_NAME_RECV_WINDOW = "recvWindow";

    @JsonProperty(SERIALIZED_NAME_RECV_WINDOW)
    
    private Long recvWindow;

    public OrderCancelRequest() {}

    public OrderCancelRequest symbol( String symbol) {
        this.symbol = symbol;
        return this;
    }

    /**
     * Get symbol
     *
     * @return symbol
     */

    
    public String getSymbol() {
        return symbol;
    }

    public void setSymbol( String symbol) {
        this.symbol = symbol;
    }

    public OrderCancelRequest orderId( Long orderId) {
        this.orderId = orderId;
        return this;
    }

    /**
     * Get orderId
     *
     * @return orderId
     */
    
    public Long getOrderId() {
        return orderId;
    }

    public void setOrderId( Long orderId) {
        this.orderId = orderId;
    }

    public OrderCancelRequest origClientOrderId(
             String origClientOrderId) {
        this.origClientOrderId = origClientOrderId;
        return this;
    }

    /**
     * Get origClientOrderId
     *
     * @return origClientOrderId
     */
    
    public String getOrigClientOrderId() {
        return origClientOrderId;
    }

    public void setOrigClientOrderId( String origClientOrderId) {
        this.origClientOrderId = origClientOrderId;
    }

    public OrderCancelRequest newClientOrderId(
             String newClientOrderId) {
        this.newClientOrderId = newClientOrderId;
        return this;
    }

    /**
     * Get newClientOrderId
     *
     * @return newClientOrderId
     */
    
    public String getNewClientOrderId() {
        return newClientOrderId;
    }

    public void setNewClientOrderId( String newClientOrderId) {
        this.newClientOrderId = newClientOrderId;
    }

    public OrderCancelRequest cancelRestrictions(
             CancelRestrictions cancelRestrictions) {
        this.cancelRestrictions = cancelRestrictions;
        return this;
    }

    /**
     * Get cancelRestrictions
     *
     * @return cancelRestrictions
     */
    
    
    public CancelRestrictions getCancelRestrictions() {
        return cancelRestrictions;
    }

    public void setCancelRestrictions(
             CancelRestrictions cancelRestrictions) {
        this.cancelRestrictions = cancelRestrictions;
    }

    public OrderCancelRequest recvWindow( Long recvWindow) {
        this.recvWindow = recvWindow;
        return this;
    }

    /**
     * Get recvWindow
     *
     * @return recvWindow
     */
    
    
    public Long getRecvWindow() {
        return recvWindow;
    }

    public void setRecvWindow( Long recvWindow) {
        this.recvWindow = recvWindow;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OrderCancelRequest orderCancelRequest = (OrderCancelRequest) o;
        return Objects.equals(this.symbol, orderCancelRequest.symbol)
                && Objects.equals(this.orderId, orderCancelRequest.orderId)
                && Objects.equals(this.origClientOrderId, orderCancelRequest.origClientOrderId)
                && Objects.equals(this.newClientOrderId, orderCancelRequest.newClientOrderId)
                && Objects.equals(this.cancelRestrictions, orderCancelRequest.cancelRestrictions)
                && Objects.equals(this.recvWindow, orderCancelRequest.recvWindow);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                symbol,
                orderId,
                origClientOrderId,
                newClientOrderId,
                cancelRestrictions,
                recvWindow);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class OrderCancelRequest {\n");
        sb.append("		symbol: ").append(toIndentedString(symbol)).append("\n");
        sb.append("		orderId: ").append(toIndentedString(orderId)).append("\n");
        sb.append("		origClientOrderId: ").append(toIndentedString(origClientOrderId)).append("\n");
        sb.append("		newClientOrderId: ").append(toIndentedString(newClientOrderId)).append("\n");
        sb.append("		cancelRestrictions: ")
                .append(toIndentedString(cancelRestrictions))
                .append("\n");
        sb.append("		recvWindow: ").append(toIndentedString(recvWindow)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();
        Map<String, String> valMap = new TreeMap<String, String>();
        valMap.put("apiKey", getApiKey());
        String symbolValue = getSymbol();
        if (symbolValue != null) {
            String symbolValueAsString = symbolValue.toString();
            valMap.put("symbol", symbolValueAsString);
        }
        Long orderIdValue = getOrderId();
        if (orderIdValue != null) {
            String orderIdValueAsString = orderIdValue.toString();
            valMap.put("orderId", orderIdValueAsString);
        }
        String origClientOrderIdValue = getOrigClientOrderId();
        if (origClientOrderIdValue != null) {
            String origClientOrderIdValueAsString = origClientOrderIdValue.toString();
            valMap.put("origClientOrderId", origClientOrderIdValueAsString);
        }
        String newClientOrderIdValue = getNewClientOrderId();
        if (newClientOrderIdValue != null) {
            String newClientOrderIdValueAsString = newClientOrderIdValue.toString();
            valMap.put("newClientOrderId", newClientOrderIdValueAsString);
        }
        CancelRestrictions cancelRestrictionsValue = getCancelRestrictions();
        if (cancelRestrictionsValue != null) {
            String cancelRestrictionsValueAsString = cancelRestrictionsValue.toString();
            valMap.put("cancelRestrictions", cancelRestrictionsValueAsString);
        }
        Long recvWindowValue = getRecvWindow();
        if (recvWindowValue != null) {
            String recvWindowValueAsString =
                    DecimalFormatter.getFormatter().format(recvWindowValue);
            valMap.put("recvWindow", recvWindowValueAsString);
        }

        valMap.put("timestamp", getTimestamp());
        return asciiEncode(
                valMap.keySet().stream()
                        .map(key -> key + "=" + valMap.get(key))
                        .collect(Collectors.joining("&")));
    }

    public Map<String, Object> toMap() {
        Map<String, Object> valMap = new TreeMap<String, Object>();
        valMap.put("apiKey", getApiKey());
        Object symbolValue = getSymbol();
        if (symbolValue != null) {
            valMap.put("symbol", symbolValue);
        }
        Object orderIdValue = getOrderId();
        if (orderIdValue != null) {
            valMap.put("orderId", orderIdValue);
        }
        Object origClientOrderIdValue = getOrigClientOrderId();
        if (origClientOrderIdValue != null) {
            valMap.put("origClientOrderId", origClientOrderIdValue);
        }
        Object newClientOrderIdValue = getNewClientOrderId();
        if (newClientOrderIdValue != null) {
            valMap.put("newClientOrderId", newClientOrderIdValue);
        }
        Object cancelRestrictionsValue = getCancelRestrictions();
        if (cancelRestrictionsValue != null) {
            valMap.put("cancelRestrictions", cancelRestrictionsValue);
        }
        Object recvWindowValue = getRecvWindow();
        if (recvWindowValue != null) {
            valMap.put("recvWindow", recvWindowValue);
        }

        valMap.put("timestamp", getTimestamp());
        return valMap;
    }

    public static String asciiEncode(String s) {
        return new String(s.getBytes(), StandardCharsets.US_ASCII);
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n		");
    }

}
