/*
 * Binance Spot WebSocket API
 * OpenAPI Specifications for the Binance Spot WebSocket API  API documents:   - [Github web-socket-api documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-api.md)   - [General API information for web-socket-api on website](https://developers.binance.com/docs/binance-spot-api-docs/web-socket-api/general-api-information)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.quarkus.spot.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.stream.Collectors;

public class OrderTestResponseResultDiscount extends BaseDTO {
    public static final String SERIALIZED_NAME_ENABLED_FOR_ACCOUNT = "enabledForAccount";

    @JsonProperty(SERIALIZED_NAME_ENABLED_FOR_ACCOUNT)
    
    private Boolean enabledForAccount;

    public static final String SERIALIZED_NAME_ENABLED_FOR_SYMBOL = "enabledForSymbol";

    @JsonProperty(SERIALIZED_NAME_ENABLED_FOR_SYMBOL)
    
    private Boolean enabledForSymbol;

    public static final String SERIALIZED_NAME_DISCOUNT_ASSET = "discountAsset";

    @JsonProperty(SERIALIZED_NAME_DISCOUNT_ASSET)
    
    private String discountAsset;

    public static final String SERIALIZED_NAME_DISCOUNT = "discount";

    @JsonProperty(SERIALIZED_NAME_DISCOUNT)
    
    private String discount;

    public OrderTestResponseResultDiscount() {}

    public OrderTestResponseResultDiscount enabledForAccount(
             Boolean enabledForAccount) {
        this.enabledForAccount = enabledForAccount;
        return this;
    }

    /**
     * Get enabledForAccount
     *
     * @return enabledForAccount
     */
    
    public Boolean getEnabledForAccount() {
        return enabledForAccount;
    }

    public void setEnabledForAccount( Boolean enabledForAccount) {
        this.enabledForAccount = enabledForAccount;
    }

    public OrderTestResponseResultDiscount enabledForSymbol(
             Boolean enabledForSymbol) {
        this.enabledForSymbol = enabledForSymbol;
        return this;
    }

    /**
     * Get enabledForSymbol
     *
     * @return enabledForSymbol
     */
    
    public Boolean getEnabledForSymbol() {
        return enabledForSymbol;
    }

    public void setEnabledForSymbol( Boolean enabledForSymbol) {
        this.enabledForSymbol = enabledForSymbol;
    }

    public OrderTestResponseResultDiscount discountAsset(
             String discountAsset) {
        this.discountAsset = discountAsset;
        return this;
    }

    /**
     * Get discountAsset
     *
     * @return discountAsset
     */
    
    public String getDiscountAsset() {
        return discountAsset;
    }

    public void setDiscountAsset( String discountAsset) {
        this.discountAsset = discountAsset;
    }

    public OrderTestResponseResultDiscount discount( String discount) {
        this.discount = discount;
        return this;
    }

    /**
     * Get discount
     *
     * @return discount
     */
    
    public String getDiscount() {
        return discount;
    }

    public void setDiscount( String discount) {
        this.discount = discount;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OrderTestResponseResultDiscount orderTestResponseResultDiscount =
                (OrderTestResponseResultDiscount) o;
        return Objects.equals(
                        this.enabledForAccount, orderTestResponseResultDiscount.enabledForAccount)
                && Objects.equals(
                        this.enabledForSymbol, orderTestResponseResultDiscount.enabledForSymbol)
                && Objects.equals(this.discountAsset, orderTestResponseResultDiscount.discountAsset)
                && Objects.equals(this.discount, orderTestResponseResultDiscount.discount);
    }

    @Override
    public int hashCode() {
        return Objects.hash(enabledForAccount, enabledForSymbol, discountAsset, discount);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class OrderTestResponseResultDiscount {\n");
        sb.append("		enabledForAccount: ").append(toIndentedString(enabledForAccount)).append("\n");
        sb.append("		enabledForSymbol: ").append(toIndentedString(enabledForSymbol)).append("\n");
        sb.append("		discountAsset: ").append(toIndentedString(discountAsset)).append("\n");
        sb.append("		discount: ").append(toIndentedString(discount)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();
        Map<String, String> valMap = new TreeMap<String, String>();
        valMap.put("apiKey", getApiKey());
        Boolean enabledForAccountValue = getEnabledForAccount();
        if (enabledForAccountValue != null) {
            String enabledForAccountValueAsString = enabledForAccountValue.toString();
            valMap.put("enabledForAccount", enabledForAccountValueAsString);
        }
        Boolean enabledForSymbolValue = getEnabledForSymbol();
        if (enabledForSymbolValue != null) {
            String enabledForSymbolValueAsString = enabledForSymbolValue.toString();
            valMap.put("enabledForSymbol", enabledForSymbolValueAsString);
        }
        String discountAssetValue = getDiscountAsset();
        if (discountAssetValue != null) {
            String discountAssetValueAsString = discountAssetValue.toString();
            valMap.put("discountAsset", discountAssetValueAsString);
        }
        String discountValue = getDiscount();
        if (discountValue != null) {
            String discountValueAsString = discountValue.toString();
            valMap.put("discount", discountValueAsString);
        }

        valMap.put("timestamp", getTimestamp());
        return asciiEncode(
                valMap.keySet().stream()
                        .map(key -> key + "=" + valMap.get(key))
                        .collect(Collectors.joining("&")));
    }

    public Map<String, Object> toMap() {
        Map<String, Object> valMap = new TreeMap<String, Object>();
        valMap.put("apiKey", getApiKey());
        Object enabledForAccountValue = getEnabledForAccount();
        if (enabledForAccountValue != null) {
            valMap.put("enabledForAccount", enabledForAccountValue);
        }
        Object enabledForSymbolValue = getEnabledForSymbol();
        if (enabledForSymbolValue != null) {
            valMap.put("enabledForSymbol", enabledForSymbolValue);
        }
        Object discountAssetValue = getDiscountAsset();
        if (discountAssetValue != null) {
            valMap.put("discountAsset", discountAssetValue);
        }
        Object discountValue = getDiscount();
        if (discountValue != null) {
            valMap.put("discount", discountValue);
        }

        valMap.put("timestamp", getTimestamp());
        return valMap;
    }

    public static String asciiEncode(String s) {
        return new String(s.getBytes(), StandardCharsets.US_ASCII);
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n		");
    }

}
