/*
 * Binance Spot WebSocket API
 * OpenAPI Specifications for the Binance Spot WebSocket API  API documents:   - [Github web-socket-api documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-api.md)   - [General API information for web-socket-api on website](https://developers.binance.com/docs/binance-spot-api-docs/web-socket-api/general-api-information)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.quarkus.spot.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.vertx.core.json.Json;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.stream.Collectors;

public class OrderAmendKeepPriorityResponseResult extends BaseDTO {
    public static final String SERIALIZED_NAME_TRANSACT_TIME = "transactTime";

    @JsonProperty(SERIALIZED_NAME_TRANSACT_TIME)
    
    private Long transactTime;

    public static final String SERIALIZED_NAME_EXECUTION_ID = "executionId";

    @JsonProperty(SERIALIZED_NAME_EXECUTION_ID)
    
    private Long executionId;

    public static final String SERIALIZED_NAME_AMENDED_ORDER = "amendedOrder";

    @JsonProperty(SERIALIZED_NAME_AMENDED_ORDER)
    
    private OrderAmendKeepPriorityResponseResultAmendedOrder amendedOrder;

    public static final String SERIALIZED_NAME_LIST_STATUS = "listStatus";

    @JsonProperty(SERIALIZED_NAME_LIST_STATUS)
    
    private OrderAmendKeepPriorityResponseResultListStatus listStatus;

    public OrderAmendKeepPriorityResponseResult() {}

    public OrderAmendKeepPriorityResponseResult transactTime(
             Long transactTime) {
        this.transactTime = transactTime;
        return this;
    }

    /**
     * Get transactTime
     *
     * @return transactTime
     */
    
    public Long getTransactTime() {
        return transactTime;
    }

    public void setTransactTime( Long transactTime) {
        this.transactTime = transactTime;
    }

    public OrderAmendKeepPriorityResponseResult executionId(
             Long executionId) {
        this.executionId = executionId;
        return this;
    }

    /**
     * Get executionId
     *
     * @return executionId
     */
    
    public Long getExecutionId() {
        return executionId;
    }

    public void setExecutionId( Long executionId) {
        this.executionId = executionId;
    }

    public OrderAmendKeepPriorityResponseResult amendedOrder(
            
            OrderAmendKeepPriorityResponseResultAmendedOrder amendedOrder) {
        this.amendedOrder = amendedOrder;
        return this;
    }

    /**
     * Get amendedOrder
     *
     * @return amendedOrder
     */
    

    public OrderAmendKeepPriorityResponseResultAmendedOrder getAmendedOrder() {
        return amendedOrder;
    }

    public void setAmendedOrder(
            
            OrderAmendKeepPriorityResponseResultAmendedOrder amendedOrder) {
        this.amendedOrder = amendedOrder;
    }

    public OrderAmendKeepPriorityResponseResult listStatus(
            
            OrderAmendKeepPriorityResponseResultListStatus listStatus) {
        this.listStatus = listStatus;
        return this;
    }

    /**
     * Get listStatus
     *
     * @return listStatus
     */
    

    public OrderAmendKeepPriorityResponseResultListStatus getListStatus() {
        return listStatus;
    }

    public void setListStatus(
            
            OrderAmendKeepPriorityResponseResultListStatus listStatus) {
        this.listStatus = listStatus;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OrderAmendKeepPriorityResponseResult orderAmendKeepPriorityResponseResult =
                (OrderAmendKeepPriorityResponseResult) o;
        return Objects.equals(this.transactTime, orderAmendKeepPriorityResponseResult.transactTime)
                && Objects.equals(
                        this.executionId, orderAmendKeepPriorityResponseResult.executionId)
                && Objects.equals(
                        this.amendedOrder, orderAmendKeepPriorityResponseResult.amendedOrder)
                && Objects.equals(this.listStatus, orderAmendKeepPriorityResponseResult.listStatus);
    }

    @Override
    public int hashCode() {
        return Objects.hash(transactTime, executionId, amendedOrder, listStatus);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class OrderAmendKeepPriorityResponseResult {\n");
        sb.append("		transactTime: ").append(toIndentedString(transactTime)).append("\n");
        sb.append("		executionId: ").append(toIndentedString(executionId)).append("\n");
        sb.append("		amendedOrder: ").append(toIndentedString(amendedOrder)).append("\n");
        sb.append("		listStatus: ").append(toIndentedString(listStatus)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();
        Map<String, String> valMap = new TreeMap<String, String>();
        valMap.put("apiKey", getApiKey());
        Long transactTimeValue = getTransactTime();
        if (transactTimeValue != null) {
            String transactTimeValueAsString = transactTimeValue.toString();
            valMap.put("transactTime", transactTimeValueAsString);
        }
        Long executionIdValue = getExecutionId();
        if (executionIdValue != null) {
            String executionIdValueAsString = executionIdValue.toString();
            valMap.put("executionId", executionIdValueAsString);
        }
        OrderAmendKeepPriorityResponseResultAmendedOrder amendedOrderValue = getAmendedOrder();
        if (amendedOrderValue != null) {
            String amendedOrderValueAsString = Json.encode(amendedOrderValue);
            valMap.put("amendedOrder", amendedOrderValueAsString);
        }
        OrderAmendKeepPriorityResponseResultListStatus listStatusValue = getListStatus();
        if (listStatusValue != null) {
            String listStatusValueAsString = Json.encode(listStatusValue);
            valMap.put("listStatus", listStatusValueAsString);
        }

        valMap.put("timestamp", getTimestamp());
        return asciiEncode(
                valMap.keySet().stream()
                        .map(key -> key + "=" + valMap.get(key))
                        .collect(Collectors.joining("&")));
    }

    public Map<String, Object> toMap() {
        Map<String, Object> valMap = new TreeMap<String, Object>();
        valMap.put("apiKey", getApiKey());
        Object transactTimeValue = getTransactTime();
        if (transactTimeValue != null) {
            valMap.put("transactTime", transactTimeValue);
        }
        Object executionIdValue = getExecutionId();
        if (executionIdValue != null) {
            valMap.put("executionId", executionIdValue);
        }
        Object amendedOrderValue = getAmendedOrder();
        if (amendedOrderValue != null) {
            valMap.put("amendedOrder", amendedOrderValue);
        }
        Object listStatusValue = getListStatus();
        if (listStatusValue != null) {
            valMap.put("listStatus", listStatusValue);
        }

        valMap.put("timestamp", getTimestamp());
        return valMap;
    }

    public static String asciiEncode(String s) {
        return new String(s.getBytes(), StandardCharsets.US_ASCII);
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n		");
    }
}
