/*
 * Binance Spot WebSocket API
 * OpenAPI Specifications for the Binance Spot WebSocket API  API documents:   - [Github web-socket-api documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-api.md)   - [General API information for web-socket-api on website](https://developers.binance.com/docs/binance-spot-api-docs/web-socket-api/general-api-information)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.quarkus.spot.model;

import com.binance.connector.client.common.DecimalFormatter;
import com.fasterxml.jackson.annotation.JsonProperty;


import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.stream.Collectors;

public class OrderListPlaceOtoRequest extends BaseDTO {
    public static final String SERIALIZED_NAME_SYMBOL = "symbol";

    @JsonProperty(SERIALIZED_NAME_SYMBOL)

    private String symbol;

    public static final String SERIALIZED_NAME_LIST_CLIENT_ORDER_ID = "listClientOrderId";

    @JsonProperty(SERIALIZED_NAME_LIST_CLIENT_ORDER_ID)
    
    private String listClientOrderId;

    public static final String SERIALIZED_NAME_NEW_ORDER_RESP_TYPE = "newOrderRespType";

    @JsonProperty(SERIALIZED_NAME_NEW_ORDER_RESP_TYPE)
    
    private NewOrderRespType newOrderRespType;

    public static final String SERIALIZED_NAME_SELF_TRADE_PREVENTION_MODE =
            "selfTradePreventionMode";

    @JsonProperty(SERIALIZED_NAME_SELF_TRADE_PREVENTION_MODE)
    
    private SelfTradePreventionMode selfTradePreventionMode;

    public static final String SERIALIZED_NAME_WORKING_TYPE = "workingType";

    @JsonProperty(SERIALIZED_NAME_WORKING_TYPE)

    private WorkingType workingType;

    public static final String SERIALIZED_NAME_WORKING_SIDE = "workingSide";

    @JsonProperty(SERIALIZED_NAME_WORKING_SIDE)

    private WorkingSide workingSide;

    public static final String SERIALIZED_NAME_WORKING_CLIENT_ORDER_ID = "workingClientOrderId";

    @JsonProperty(SERIALIZED_NAME_WORKING_CLIENT_ORDER_ID)
    
    private String workingClientOrderId;

    public static final String SERIALIZED_NAME_WORKING_PRICE = "workingPrice";

    @JsonProperty(SERIALIZED_NAME_WORKING_PRICE)

    private Double workingPrice;

    public static final String SERIALIZED_NAME_WORKING_QUANTITY = "workingQuantity";

    @JsonProperty(SERIALIZED_NAME_WORKING_QUANTITY)

    private Double workingQuantity;

    public static final String SERIALIZED_NAME_WORKING_ICEBERG_QTY = "workingIcebergQty";

    @JsonProperty(SERIALIZED_NAME_WORKING_ICEBERG_QTY)
    
    private Double workingIcebergQty;

    public static final String SERIALIZED_NAME_WORKING_TIME_IN_FORCE = "workingTimeInForce";

    @JsonProperty(SERIALIZED_NAME_WORKING_TIME_IN_FORCE)
    
    private WorkingTimeInForce workingTimeInForce;

    public static final String SERIALIZED_NAME_WORKING_STRATEGY_ID = "workingStrategyId";

    @JsonProperty(SERIALIZED_NAME_WORKING_STRATEGY_ID)
    
    private Long workingStrategyId;

    public static final String SERIALIZED_NAME_WORKING_STRATEGY_TYPE = "workingStrategyType";

    @JsonProperty(SERIALIZED_NAME_WORKING_STRATEGY_TYPE)
    
    private Integer workingStrategyType;

    public static final String SERIALIZED_NAME_WORKING_PEG_PRICE_TYPE = "workingPegPriceType";

    @JsonProperty(SERIALIZED_NAME_WORKING_PEG_PRICE_TYPE)
    
    private WorkingPegPriceType workingPegPriceType;

    public static final String SERIALIZED_NAME_WORKING_PEG_OFFSET_TYPE = "workingPegOffsetType";

    @JsonProperty(SERIALIZED_NAME_WORKING_PEG_OFFSET_TYPE)
    
    private WorkingPegOffsetType workingPegOffsetType;

    public static final String SERIALIZED_NAME_WORKING_PEG_OFFSET_VALUE = "workingPegOffsetValue";

    @JsonProperty(SERIALIZED_NAME_WORKING_PEG_OFFSET_VALUE)
    
    private Integer workingPegOffsetValue;

    public static final String SERIALIZED_NAME_PENDING_TYPE = "pendingType";

    @JsonProperty(SERIALIZED_NAME_PENDING_TYPE)
    
    private PendingType pendingType;

    public static final String SERIALIZED_NAME_PENDING_SIDE = "pendingSide";

    @JsonProperty(SERIALIZED_NAME_PENDING_SIDE)

    private PendingSide pendingSide;

    public static final String SERIALIZED_NAME_PENDING_CLIENT_ORDER_ID = "pendingClientOrderId";

    @JsonProperty(SERIALIZED_NAME_PENDING_CLIENT_ORDER_ID)
    
    private String pendingClientOrderId;

    public static final String SERIALIZED_NAME_PENDING_PRICE = "pendingPrice";

    @JsonProperty(SERIALIZED_NAME_PENDING_PRICE)
    
    private Double pendingPrice;

    public static final String SERIALIZED_NAME_PENDING_STOP_PRICE = "pendingStopPrice";

    @JsonProperty(SERIALIZED_NAME_PENDING_STOP_PRICE)
    
    private Double pendingStopPrice;

    public static final String SERIALIZED_NAME_PENDING_TRAILING_DELTA = "pendingTrailingDelta";

    @JsonProperty(SERIALIZED_NAME_PENDING_TRAILING_DELTA)
    
    private Double pendingTrailingDelta;

    public static final String SERIALIZED_NAME_PENDING_QUANTITY = "pendingQuantity";

    @JsonProperty(SERIALIZED_NAME_PENDING_QUANTITY)

    private Double pendingQuantity;

    public static final String SERIALIZED_NAME_PENDING_ICEBERG_QTY = "pendingIcebergQty";

    @JsonProperty(SERIALIZED_NAME_PENDING_ICEBERG_QTY)
    
    private Double pendingIcebergQty;

    public static final String SERIALIZED_NAME_PENDING_TIME_IN_FORCE = "pendingTimeInForce";

    @JsonProperty(SERIALIZED_NAME_PENDING_TIME_IN_FORCE)
    
    private PendingTimeInForce pendingTimeInForce;

    public static final String SERIALIZED_NAME_PENDING_STRATEGY_ID = "pendingStrategyId";

    @JsonProperty(SERIALIZED_NAME_PENDING_STRATEGY_ID)
    
    private Long pendingStrategyId;

    public static final String SERIALIZED_NAME_PENDING_STRATEGY_TYPE = "pendingStrategyType";

    @JsonProperty(SERIALIZED_NAME_PENDING_STRATEGY_TYPE)
    
    private Integer pendingStrategyType;

    public static final String SERIALIZED_NAME_PENDING_PEG_OFFSET_TYPE = "pendingPegOffsetType";

    @JsonProperty(SERIALIZED_NAME_PENDING_PEG_OFFSET_TYPE)
    
    private PendingPegOffsetType pendingPegOffsetType;

    public static final String SERIALIZED_NAME_PENDING_PEG_PRICE_TYPE = "pendingPegPriceType";

    @JsonProperty(SERIALIZED_NAME_PENDING_PEG_PRICE_TYPE)
    
    private PendingPegPriceType pendingPegPriceType;

    public static final String SERIALIZED_NAME_PENDING_PEG_OFFSET_VALUE = "pendingPegOffsetValue";

    @JsonProperty(SERIALIZED_NAME_PENDING_PEG_OFFSET_VALUE)
    
    private Integer pendingPegOffsetValue;

    public static final String SERIALIZED_NAME_RECV_WINDOW = "recvWindow";

    @JsonProperty(SERIALIZED_NAME_RECV_WINDOW)
    
    private Double recvWindow;

    public OrderListPlaceOtoRequest() {}

    public OrderListPlaceOtoRequest symbol( String symbol) {
        this.symbol = symbol;
        return this;
    }

    /**
     * Get symbol
     *
     * @return symbol
     */


    public String getSymbol() {
        return symbol;
    }

    public void setSymbol( String symbol) {
        this.symbol = symbol;
    }

    public OrderListPlaceOtoRequest listClientOrderId(
             String listClientOrderId) {
        this.listClientOrderId = listClientOrderId;
        return this;
    }

    /**
     * Get listClientOrderId
     *
     * @return listClientOrderId
     */
    
    public String getListClientOrderId() {
        return listClientOrderId;
    }

    public void setListClientOrderId( String listClientOrderId) {
        this.listClientOrderId = listClientOrderId;
    }

    public OrderListPlaceOtoRequest newOrderRespType(
             NewOrderRespType newOrderRespType) {
        this.newOrderRespType = newOrderRespType;
        return this;
    }

    /**
     * Get newOrderRespType
     *
     * @return newOrderRespType
     */
    
    
    public NewOrderRespType getNewOrderRespType() {
        return newOrderRespType;
    }

    public void setNewOrderRespType(
             NewOrderRespType newOrderRespType) {
        this.newOrderRespType = newOrderRespType;
    }

    public OrderListPlaceOtoRequest selfTradePreventionMode(
             SelfTradePreventionMode selfTradePreventionMode) {
        this.selfTradePreventionMode = selfTradePreventionMode;
        return this;
    }

    /**
     * Get selfTradePreventionMode
     *
     * @return selfTradePreventionMode
     */
    
    
    public SelfTradePreventionMode getSelfTradePreventionMode() {
        return selfTradePreventionMode;
    }

    public void setSelfTradePreventionMode(
             SelfTradePreventionMode selfTradePreventionMode) {
        this.selfTradePreventionMode = selfTradePreventionMode;
    }

    public OrderListPlaceOtoRequest workingType(
             WorkingType workingType) {
        this.workingType = workingType;
        return this;
    }

    /**
     * Get workingType
     *
     * @return workingType
     */

    
    
    public WorkingType getWorkingType() {
        return workingType;
    }

    public void setWorkingType( WorkingType workingType) {
        this.workingType = workingType;
    }

    public OrderListPlaceOtoRequest workingSide(
             WorkingSide workingSide) {
        this.workingSide = workingSide;
        return this;
    }

    /**
     * Get workingSide
     *
     * @return workingSide
     */

    
    
    public WorkingSide getWorkingSide() {
        return workingSide;
    }

    public void setWorkingSide( WorkingSide workingSide) {
        this.workingSide = workingSide;
    }

    public OrderListPlaceOtoRequest workingClientOrderId(
             String workingClientOrderId) {
        this.workingClientOrderId = workingClientOrderId;
        return this;
    }

    /**
     * Get workingClientOrderId
     *
     * @return workingClientOrderId
     */
    
    public String getWorkingClientOrderId() {
        return workingClientOrderId;
    }

    public void setWorkingClientOrderId( String workingClientOrderId) {
        this.workingClientOrderId = workingClientOrderId;
    }

    public OrderListPlaceOtoRequest workingPrice( Double workingPrice) {
        this.workingPrice = workingPrice;
        return this;
    }

    /**
     * Get workingPrice
     *
     * @return workingPrice
     */

    
    
    public Double getWorkingPrice() {
        return workingPrice;
    }

    public void setWorkingPrice( Double workingPrice) {
        this.workingPrice = workingPrice;
    }

    public OrderListPlaceOtoRequest workingQuantity(
             Double workingQuantity) {
        this.workingQuantity = workingQuantity;
        return this;
    }

    /**
     * Get workingQuantity
     *
     * @return workingQuantity
     */

    
    
    public Double getWorkingQuantity() {
        return workingQuantity;
    }

    public void setWorkingQuantity( Double workingQuantity) {
        this.workingQuantity = workingQuantity;
    }

    public OrderListPlaceOtoRequest workingIcebergQty(
             Double workingIcebergQty) {
        this.workingIcebergQty = workingIcebergQty;
        return this;
    }

    /**
     * Get workingIcebergQty
     *
     * @return workingIcebergQty
     */
    
    
    public Double getWorkingIcebergQty() {
        return workingIcebergQty;
    }

    public void setWorkingIcebergQty( Double workingIcebergQty) {
        this.workingIcebergQty = workingIcebergQty;
    }

    public OrderListPlaceOtoRequest workingTimeInForce(
             WorkingTimeInForce workingTimeInForce) {
        this.workingTimeInForce = workingTimeInForce;
        return this;
    }

    /**
     * Get workingTimeInForce
     *
     * @return workingTimeInForce
     */
    
    
    public WorkingTimeInForce getWorkingTimeInForce() {
        return workingTimeInForce;
    }

    public void setWorkingTimeInForce(
             WorkingTimeInForce workingTimeInForce) {
        this.workingTimeInForce = workingTimeInForce;
    }

    public OrderListPlaceOtoRequest workingStrategyId(
             Long workingStrategyId) {
        this.workingStrategyId = workingStrategyId;
        return this;
    }

    /**
     * Get workingStrategyId
     *
     * @return workingStrategyId
     */
    
    public Long getWorkingStrategyId() {
        return workingStrategyId;
    }

    public void setWorkingStrategyId( Long workingStrategyId) {
        this.workingStrategyId = workingStrategyId;
    }

    public OrderListPlaceOtoRequest workingStrategyType(
             Integer workingStrategyType) {
        this.workingStrategyType = workingStrategyType;
        return this;
    }

    /**
     * Get workingStrategyType
     *
     * @return workingStrategyType
     */
    
    public Integer getWorkingStrategyType() {
        return workingStrategyType;
    }

    public void setWorkingStrategyType( Integer workingStrategyType) {
        this.workingStrategyType = workingStrategyType;
    }

    public OrderListPlaceOtoRequest workingPegPriceType(
             WorkingPegPriceType workingPegPriceType) {
        this.workingPegPriceType = workingPegPriceType;
        return this;
    }

    /**
     * Get workingPegPriceType
     *
     * @return workingPegPriceType
     */
    
    
    public WorkingPegPriceType getWorkingPegPriceType() {
        return workingPegPriceType;
    }

    public void setWorkingPegPriceType(
             WorkingPegPriceType workingPegPriceType) {
        this.workingPegPriceType = workingPegPriceType;
    }

    public OrderListPlaceOtoRequest workingPegOffsetType(
             WorkingPegOffsetType workingPegOffsetType) {
        this.workingPegOffsetType = workingPegOffsetType;
        return this;
    }

    /**
     * Get workingPegOffsetType
     *
     * @return workingPegOffsetType
     */
    
    
    public WorkingPegOffsetType getWorkingPegOffsetType() {
        return workingPegOffsetType;
    }

    public void setWorkingPegOffsetType(
             WorkingPegOffsetType workingPegOffsetType) {
        this.workingPegOffsetType = workingPegOffsetType;
    }

    public OrderListPlaceOtoRequest workingPegOffsetValue(
             Integer workingPegOffsetValue) {
        this.workingPegOffsetValue = workingPegOffsetValue;
        return this;
    }

    /**
     * Get workingPegOffsetValue
     *
     * @return workingPegOffsetValue
     */
    
    public Integer getWorkingPegOffsetValue() {
        return workingPegOffsetValue;
    }

    public void setWorkingPegOffsetValue(
             Integer workingPegOffsetValue) {
        this.workingPegOffsetValue = workingPegOffsetValue;
    }

    public OrderListPlaceOtoRequest pendingType(
             PendingType pendingType) {
        this.pendingType = pendingType;
        return this;
    }

    /**
     * Get pendingType
     *
     * @return pendingType
     */

    
    
    public PendingType getPendingType() {
        return pendingType;
    }

    public void setPendingType( PendingType pendingType) {
        this.pendingType = pendingType;
    }

    public OrderListPlaceOtoRequest pendingSide(
             PendingSide pendingSide) {
        this.pendingSide = pendingSide;
        return this;
    }

    /**
     * Get pendingSide
     *
     * @return pendingSide
     */

    
    
    public PendingSide getPendingSide() {
        return pendingSide;
    }

    public void setPendingSide( PendingSide pendingSide) {
        this.pendingSide = pendingSide;
    }

    public OrderListPlaceOtoRequest pendingClientOrderId(
             String pendingClientOrderId) {
        this.pendingClientOrderId = pendingClientOrderId;
        return this;
    }

    /**
     * Get pendingClientOrderId
     *
     * @return pendingClientOrderId
     */
    
    public String getPendingClientOrderId() {
        return pendingClientOrderId;
    }

    public void setPendingClientOrderId( String pendingClientOrderId) {
        this.pendingClientOrderId = pendingClientOrderId;
    }

    public OrderListPlaceOtoRequest pendingPrice( Double pendingPrice) {
        this.pendingPrice = pendingPrice;
        return this;
    }

    /**
     * Get pendingPrice
     *
     * @return pendingPrice
     */
    
    
    public Double getPendingPrice() {
        return pendingPrice;
    }

    public void setPendingPrice( Double pendingPrice) {
        this.pendingPrice = pendingPrice;
    }

    public OrderListPlaceOtoRequest pendingStopPrice(
             Double pendingStopPrice) {
        this.pendingStopPrice = pendingStopPrice;
        return this;
    }

    /**
     * Get pendingStopPrice
     *
     * @return pendingStopPrice
     */
    
    
    public Double getPendingStopPrice() {
        return pendingStopPrice;
    }

    public void setPendingStopPrice( Double pendingStopPrice) {
        this.pendingStopPrice = pendingStopPrice;
    }

    public OrderListPlaceOtoRequest pendingTrailingDelta(
             Double pendingTrailingDelta) {
        this.pendingTrailingDelta = pendingTrailingDelta;
        return this;
    }

    /**
     * Get pendingTrailingDelta
     *
     * @return pendingTrailingDelta
     */
    
    
    public Double getPendingTrailingDelta() {
        return pendingTrailingDelta;
    }

    public void setPendingTrailingDelta( Double pendingTrailingDelta) {
        this.pendingTrailingDelta = pendingTrailingDelta;
    }

    public OrderListPlaceOtoRequest pendingQuantity(
             Double pendingQuantity) {
        this.pendingQuantity = pendingQuantity;
        return this;
    }

    /**
     * Get pendingQuantity
     *
     * @return pendingQuantity
     */

    
    
    public Double getPendingQuantity() {
        return pendingQuantity;
    }

    public void setPendingQuantity( Double pendingQuantity) {
        this.pendingQuantity = pendingQuantity;
    }

    public OrderListPlaceOtoRequest pendingIcebergQty(
             Double pendingIcebergQty) {
        this.pendingIcebergQty = pendingIcebergQty;
        return this;
    }

    /**
     * Get pendingIcebergQty
     *
     * @return pendingIcebergQty
     */
    
    
    public Double getPendingIcebergQty() {
        return pendingIcebergQty;
    }

    public void setPendingIcebergQty( Double pendingIcebergQty) {
        this.pendingIcebergQty = pendingIcebergQty;
    }

    public OrderListPlaceOtoRequest pendingTimeInForce(
             PendingTimeInForce pendingTimeInForce) {
        this.pendingTimeInForce = pendingTimeInForce;
        return this;
    }

    /**
     * Get pendingTimeInForce
     *
     * @return pendingTimeInForce
     */
    
    
    public PendingTimeInForce getPendingTimeInForce() {
        return pendingTimeInForce;
    }

    public void setPendingTimeInForce(
             PendingTimeInForce pendingTimeInForce) {
        this.pendingTimeInForce = pendingTimeInForce;
    }

    public OrderListPlaceOtoRequest pendingStrategyId(
             Long pendingStrategyId) {
        this.pendingStrategyId = pendingStrategyId;
        return this;
    }

    /**
     * Get pendingStrategyId
     *
     * @return pendingStrategyId
     */
    
    public Long getPendingStrategyId() {
        return pendingStrategyId;
    }

    public void setPendingStrategyId( Long pendingStrategyId) {
        this.pendingStrategyId = pendingStrategyId;
    }

    public OrderListPlaceOtoRequest pendingStrategyType(
             Integer pendingStrategyType) {
        this.pendingStrategyType = pendingStrategyType;
        return this;
    }

    /**
     * Get pendingStrategyType
     *
     * @return pendingStrategyType
     */
    
    public Integer getPendingStrategyType() {
        return pendingStrategyType;
    }

    public void setPendingStrategyType( Integer pendingStrategyType) {
        this.pendingStrategyType = pendingStrategyType;
    }

    public OrderListPlaceOtoRequest pendingPegOffsetType(
             PendingPegOffsetType pendingPegOffsetType) {
        this.pendingPegOffsetType = pendingPegOffsetType;
        return this;
    }

    /**
     * Get pendingPegOffsetType
     *
     * @return pendingPegOffsetType
     */
    
    
    public PendingPegOffsetType getPendingPegOffsetType() {
        return pendingPegOffsetType;
    }

    public void setPendingPegOffsetType(
             PendingPegOffsetType pendingPegOffsetType) {
        this.pendingPegOffsetType = pendingPegOffsetType;
    }

    public OrderListPlaceOtoRequest pendingPegPriceType(
             PendingPegPriceType pendingPegPriceType) {
        this.pendingPegPriceType = pendingPegPriceType;
        return this;
    }

    /**
     * Get pendingPegPriceType
     *
     * @return pendingPegPriceType
     */
    
    
    public PendingPegPriceType getPendingPegPriceType() {
        return pendingPegPriceType;
    }

    public void setPendingPegPriceType(
             PendingPegPriceType pendingPegPriceType) {
        this.pendingPegPriceType = pendingPegPriceType;
    }

    public OrderListPlaceOtoRequest pendingPegOffsetValue(
             Integer pendingPegOffsetValue) {
        this.pendingPegOffsetValue = pendingPegOffsetValue;
        return this;
    }

    /**
     * Get pendingPegOffsetValue
     *
     * @return pendingPegOffsetValue
     */
    
    public Integer getPendingPegOffsetValue() {
        return pendingPegOffsetValue;
    }

    public void setPendingPegOffsetValue(
             Integer pendingPegOffsetValue) {
        this.pendingPegOffsetValue = pendingPegOffsetValue;
    }

    public OrderListPlaceOtoRequest recvWindow( Double recvWindow) {
        this.recvWindow = recvWindow;
        return this;
    }

    /**
     * Get recvWindow
     *
     * @return recvWindow
     */
    
    
    public Double getRecvWindow() {
        return recvWindow;
    }

    public void setRecvWindow( Double recvWindow) {
        this.recvWindow = recvWindow;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OrderListPlaceOtoRequest orderListPlaceOtoRequest = (OrderListPlaceOtoRequest) o;
        return Objects.equals(this.symbol, orderListPlaceOtoRequest.symbol)
                && Objects.equals(
                        this.listClientOrderId, orderListPlaceOtoRequest.listClientOrderId)
                && Objects.equals(this.newOrderRespType, orderListPlaceOtoRequest.newOrderRespType)
                && Objects.equals(
                        this.selfTradePreventionMode,
                        orderListPlaceOtoRequest.selfTradePreventionMode)
                && Objects.equals(this.workingType, orderListPlaceOtoRequest.workingType)
                && Objects.equals(this.workingSide, orderListPlaceOtoRequest.workingSide)
                && Objects.equals(
                        this.workingClientOrderId, orderListPlaceOtoRequest.workingClientOrderId)
                && Objects.equals(this.workingPrice, orderListPlaceOtoRequest.workingPrice)
                && Objects.equals(this.workingQuantity, orderListPlaceOtoRequest.workingQuantity)
                && Objects.equals(
                        this.workingIcebergQty, orderListPlaceOtoRequest.workingIcebergQty)
                && Objects.equals(
                        this.workingTimeInForce, orderListPlaceOtoRequest.workingTimeInForce)
                && Objects.equals(
                        this.workingStrategyId, orderListPlaceOtoRequest.workingStrategyId)
                && Objects.equals(
                        this.workingStrategyType, orderListPlaceOtoRequest.workingStrategyType)
                && Objects.equals(
                        this.workingPegPriceType, orderListPlaceOtoRequest.workingPegPriceType)
                && Objects.equals(
                        this.workingPegOffsetType, orderListPlaceOtoRequest.workingPegOffsetType)
                && Objects.equals(
                        this.workingPegOffsetValue, orderListPlaceOtoRequest.workingPegOffsetValue)
                && Objects.equals(this.pendingType, orderListPlaceOtoRequest.pendingType)
                && Objects.equals(this.pendingSide, orderListPlaceOtoRequest.pendingSide)
                && Objects.equals(
                        this.pendingClientOrderId, orderListPlaceOtoRequest.pendingClientOrderId)
                && Objects.equals(this.pendingPrice, orderListPlaceOtoRequest.pendingPrice)
                && Objects.equals(this.pendingStopPrice, orderListPlaceOtoRequest.pendingStopPrice)
                && Objects.equals(
                        this.pendingTrailingDelta, orderListPlaceOtoRequest.pendingTrailingDelta)
                && Objects.equals(this.pendingQuantity, orderListPlaceOtoRequest.pendingQuantity)
                && Objects.equals(
                        this.pendingIcebergQty, orderListPlaceOtoRequest.pendingIcebergQty)
                && Objects.equals(
                        this.pendingTimeInForce, orderListPlaceOtoRequest.pendingTimeInForce)
                && Objects.equals(
                        this.pendingStrategyId, orderListPlaceOtoRequest.pendingStrategyId)
                && Objects.equals(
                        this.pendingStrategyType, orderListPlaceOtoRequest.pendingStrategyType)
                && Objects.equals(
                        this.pendingPegOffsetType, orderListPlaceOtoRequest.pendingPegOffsetType)
                && Objects.equals(
                        this.pendingPegPriceType, orderListPlaceOtoRequest.pendingPegPriceType)
                && Objects.equals(
                        this.pendingPegOffsetValue, orderListPlaceOtoRequest.pendingPegOffsetValue)
                && Objects.equals(this.recvWindow, orderListPlaceOtoRequest.recvWindow);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                symbol,
                listClientOrderId,
                newOrderRespType,
                selfTradePreventionMode,
                workingType,
                workingSide,
                workingClientOrderId,
                workingPrice,
                workingQuantity,
                workingIcebergQty,
                workingTimeInForce,
                workingStrategyId,
                workingStrategyType,
                workingPegPriceType,
                workingPegOffsetType,
                workingPegOffsetValue,
                pendingType,
                pendingSide,
                pendingClientOrderId,
                pendingPrice,
                pendingStopPrice,
                pendingTrailingDelta,
                pendingQuantity,
                pendingIcebergQty,
                pendingTimeInForce,
                pendingStrategyId,
                pendingStrategyType,
                pendingPegOffsetType,
                pendingPegPriceType,
                pendingPegOffsetValue,
                recvWindow);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class OrderListPlaceOtoRequest {\n");
        sb.append("		symbol: ").append(toIndentedString(symbol)).append("\n");
        sb.append("		listClientOrderId: ").append(toIndentedString(listClientOrderId)).append("\n");
        sb.append("		newOrderRespType: ").append(toIndentedString(newOrderRespType)).append("\n");
        sb.append("		selfTradePreventionMode: ")
                .append(toIndentedString(selfTradePreventionMode))
                .append("\n");
        sb.append("		workingType: ").append(toIndentedString(workingType)).append("\n");
        sb.append("		workingSide: ").append(toIndentedString(workingSide)).append("\n");
        sb.append("		workingClientOrderId: ")
                .append(toIndentedString(workingClientOrderId))
                .append("\n");
        sb.append("		workingPrice: ").append(toIndentedString(workingPrice)).append("\n");
        sb.append("		workingQuantity: ").append(toIndentedString(workingQuantity)).append("\n");
        sb.append("		workingIcebergQty: ").append(toIndentedString(workingIcebergQty)).append("\n");
        sb.append("		workingTimeInForce: ")
                .append(toIndentedString(workingTimeInForce))
                .append("\n");
        sb.append("		workingStrategyId: ").append(toIndentedString(workingStrategyId)).append("\n");
        sb.append("		workingStrategyType: ")
                .append(toIndentedString(workingStrategyType))
                .append("\n");
        sb.append("		workingPegPriceType: ")
                .append(toIndentedString(workingPegPriceType))
                .append("\n");
        sb.append("		workingPegOffsetType: ")
                .append(toIndentedString(workingPegOffsetType))
                .append("\n");
        sb.append("		workingPegOffsetValue: ")
                .append(toIndentedString(workingPegOffsetValue))
                .append("\n");
        sb.append("		pendingType: ").append(toIndentedString(pendingType)).append("\n");
        sb.append("		pendingSide: ").append(toIndentedString(pendingSide)).append("\n");
        sb.append("		pendingClientOrderId: ")
                .append(toIndentedString(pendingClientOrderId))
                .append("\n");
        sb.append("		pendingPrice: ").append(toIndentedString(pendingPrice)).append("\n");
        sb.append("		pendingStopPrice: ").append(toIndentedString(pendingStopPrice)).append("\n");
        sb.append("		pendingTrailingDelta: ")
                .append(toIndentedString(pendingTrailingDelta))
                .append("\n");
        sb.append("		pendingQuantity: ").append(toIndentedString(pendingQuantity)).append("\n");
        sb.append("		pendingIcebergQty: ").append(toIndentedString(pendingIcebergQty)).append("\n");
        sb.append("		pendingTimeInForce: ")
                .append(toIndentedString(pendingTimeInForce))
                .append("\n");
        sb.append("		pendingStrategyId: ").append(toIndentedString(pendingStrategyId)).append("\n");
        sb.append("		pendingStrategyType: ")
                .append(toIndentedString(pendingStrategyType))
                .append("\n");
        sb.append("		pendingPegOffsetType: ")
                .append(toIndentedString(pendingPegOffsetType))
                .append("\n");
        sb.append("		pendingPegPriceType: ")
                .append(toIndentedString(pendingPegPriceType))
                .append("\n");
        sb.append("		pendingPegOffsetValue: ")
                .append(toIndentedString(pendingPegOffsetValue))
                .append("\n");
        sb.append("		recvWindow: ").append(toIndentedString(recvWindow)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();
        Map<String, String> valMap = new TreeMap<String, String>();
        valMap.put("apiKey", getApiKey());
        String symbolValue = getSymbol();
        if (symbolValue != null) {
            String symbolValueAsString = symbolValue.toString();
            valMap.put("symbol", symbolValueAsString);
        }
        String listClientOrderIdValue = getListClientOrderId();
        if (listClientOrderIdValue != null) {
            String listClientOrderIdValueAsString = listClientOrderIdValue.toString();
            valMap.put("listClientOrderId", listClientOrderIdValueAsString);
        }
        NewOrderRespType newOrderRespTypeValue = getNewOrderRespType();
        if (newOrderRespTypeValue != null) {
            String newOrderRespTypeValueAsString = newOrderRespTypeValue.toString();
            valMap.put("newOrderRespType", newOrderRespTypeValueAsString);
        }
        SelfTradePreventionMode selfTradePreventionModeValue = getSelfTradePreventionMode();
        if (selfTradePreventionModeValue != null) {
            String selfTradePreventionModeValueAsString = selfTradePreventionModeValue.toString();
            valMap.put("selfTradePreventionMode", selfTradePreventionModeValueAsString);
        }
        WorkingType workingTypeValue = getWorkingType();
        if (workingTypeValue != null) {
            String workingTypeValueAsString = workingTypeValue.toString();
            valMap.put("workingType", workingTypeValueAsString);
        }
        WorkingSide workingSideValue = getWorkingSide();
        if (workingSideValue != null) {
            String workingSideValueAsString = workingSideValue.toString();
            valMap.put("workingSide", workingSideValueAsString);
        }
        String workingClientOrderIdValue = getWorkingClientOrderId();
        if (workingClientOrderIdValue != null) {
            String workingClientOrderIdValueAsString = workingClientOrderIdValue.toString();
            valMap.put("workingClientOrderId", workingClientOrderIdValueAsString);
        }
        Double workingPriceValue = getWorkingPrice();
        if (workingPriceValue != null) {
            String workingPriceValueAsString =
                    DecimalFormatter.getFormatter().format(workingPriceValue);
            valMap.put("workingPrice", workingPriceValueAsString);
        }
        Double workingQuantityValue = getWorkingQuantity();
        if (workingQuantityValue != null) {
            String workingQuantityValueAsString =
                    DecimalFormatter.getFormatter().format(workingQuantityValue);
            valMap.put("workingQuantity", workingQuantityValueAsString);
        }
        Double workingIcebergQtyValue = getWorkingIcebergQty();
        if (workingIcebergQtyValue != null) {
            String workingIcebergQtyValueAsString =
                    DecimalFormatter.getFormatter().format(workingIcebergQtyValue);
            valMap.put("workingIcebergQty", workingIcebergQtyValueAsString);
        }
        WorkingTimeInForce workingTimeInForceValue = getWorkingTimeInForce();
        if (workingTimeInForceValue != null) {
            String workingTimeInForceValueAsString = workingTimeInForceValue.toString();
            valMap.put("workingTimeInForce", workingTimeInForceValueAsString);
        }
        Long workingStrategyIdValue = getWorkingStrategyId();
        if (workingStrategyIdValue != null) {
            String workingStrategyIdValueAsString = workingStrategyIdValue.toString();
            valMap.put("workingStrategyId", workingStrategyIdValueAsString);
        }
        Integer workingStrategyTypeValue = getWorkingStrategyType();
        if (workingStrategyTypeValue != null) {
            String workingStrategyTypeValueAsString = workingStrategyTypeValue.toString();
            valMap.put("workingStrategyType", workingStrategyTypeValueAsString);
        }
        WorkingPegPriceType workingPegPriceTypeValue = getWorkingPegPriceType();
        if (workingPegPriceTypeValue != null) {
            String workingPegPriceTypeValueAsString = workingPegPriceTypeValue.toString();
            valMap.put("workingPegPriceType", workingPegPriceTypeValueAsString);
        }
        WorkingPegOffsetType workingPegOffsetTypeValue = getWorkingPegOffsetType();
        if (workingPegOffsetTypeValue != null) {
            String workingPegOffsetTypeValueAsString = workingPegOffsetTypeValue.toString();
            valMap.put("workingPegOffsetType", workingPegOffsetTypeValueAsString);
        }
        Integer workingPegOffsetValueValue = getWorkingPegOffsetValue();
        if (workingPegOffsetValueValue != null) {
            String workingPegOffsetValueValueAsString = workingPegOffsetValueValue.toString();
            valMap.put("workingPegOffsetValue", workingPegOffsetValueValueAsString);
        }
        PendingType pendingTypeValue = getPendingType();
        if (pendingTypeValue != null) {
            String pendingTypeValueAsString = pendingTypeValue.toString();
            valMap.put("pendingType", pendingTypeValueAsString);
        }
        PendingSide pendingSideValue = getPendingSide();
        if (pendingSideValue != null) {
            String pendingSideValueAsString = pendingSideValue.toString();
            valMap.put("pendingSide", pendingSideValueAsString);
        }
        String pendingClientOrderIdValue = getPendingClientOrderId();
        if (pendingClientOrderIdValue != null) {
            String pendingClientOrderIdValueAsString = pendingClientOrderIdValue.toString();
            valMap.put("pendingClientOrderId", pendingClientOrderIdValueAsString);
        }
        Double pendingPriceValue = getPendingPrice();
        if (pendingPriceValue != null) {
            String pendingPriceValueAsString =
                    DecimalFormatter.getFormatter().format(pendingPriceValue);
            valMap.put("pendingPrice", pendingPriceValueAsString);
        }
        Double pendingStopPriceValue = getPendingStopPrice();
        if (pendingStopPriceValue != null) {
            String pendingStopPriceValueAsString =
                    DecimalFormatter.getFormatter().format(pendingStopPriceValue);
            valMap.put("pendingStopPrice", pendingStopPriceValueAsString);
        }
        Double pendingTrailingDeltaValue = getPendingTrailingDelta();
        if (pendingTrailingDeltaValue != null) {
            String pendingTrailingDeltaValueAsString =
                    DecimalFormatter.getFormatter().format(pendingTrailingDeltaValue);
            valMap.put("pendingTrailingDelta", pendingTrailingDeltaValueAsString);
        }
        Double pendingQuantityValue = getPendingQuantity();
        if (pendingQuantityValue != null) {
            String pendingQuantityValueAsString =
                    DecimalFormatter.getFormatter().format(pendingQuantityValue);
            valMap.put("pendingQuantity", pendingQuantityValueAsString);
        }
        Double pendingIcebergQtyValue = getPendingIcebergQty();
        if (pendingIcebergQtyValue != null) {
            String pendingIcebergQtyValueAsString =
                    DecimalFormatter.getFormatter().format(pendingIcebergQtyValue);
            valMap.put("pendingIcebergQty", pendingIcebergQtyValueAsString);
        }
        PendingTimeInForce pendingTimeInForceValue = getPendingTimeInForce();
        if (pendingTimeInForceValue != null) {
            String pendingTimeInForceValueAsString = pendingTimeInForceValue.toString();
            valMap.put("pendingTimeInForce", pendingTimeInForceValueAsString);
        }
        Long pendingStrategyIdValue = getPendingStrategyId();
        if (pendingStrategyIdValue != null) {
            String pendingStrategyIdValueAsString = pendingStrategyIdValue.toString();
            valMap.put("pendingStrategyId", pendingStrategyIdValueAsString);
        }
        Integer pendingStrategyTypeValue = getPendingStrategyType();
        if (pendingStrategyTypeValue != null) {
            String pendingStrategyTypeValueAsString = pendingStrategyTypeValue.toString();
            valMap.put("pendingStrategyType", pendingStrategyTypeValueAsString);
        }
        PendingPegOffsetType pendingPegOffsetTypeValue = getPendingPegOffsetType();
        if (pendingPegOffsetTypeValue != null) {
            String pendingPegOffsetTypeValueAsString = pendingPegOffsetTypeValue.toString();
            valMap.put("pendingPegOffsetType", pendingPegOffsetTypeValueAsString);
        }
        PendingPegPriceType pendingPegPriceTypeValue = getPendingPegPriceType();
        if (pendingPegPriceTypeValue != null) {
            String pendingPegPriceTypeValueAsString = pendingPegPriceTypeValue.toString();
            valMap.put("pendingPegPriceType", pendingPegPriceTypeValueAsString);
        }
        Integer pendingPegOffsetValueValue = getPendingPegOffsetValue();
        if (pendingPegOffsetValueValue != null) {
            String pendingPegOffsetValueValueAsString = pendingPegOffsetValueValue.toString();
            valMap.put("pendingPegOffsetValue", pendingPegOffsetValueValueAsString);
        }
        Double recvWindowValue = getRecvWindow();
        if (recvWindowValue != null) {
            String recvWindowValueAsString =
                    DecimalFormatter.getFormatter().format(recvWindowValue);
            valMap.put("recvWindow", recvWindowValueAsString);
        }

        valMap.put("timestamp", getTimestamp());
        return asciiEncode(
                valMap.keySet().stream()
                        .map(key -> key + "=" + valMap.get(key))
                        .collect(Collectors.joining("&")));
    }

    public Map<String, Object> toMap() {
        Map<String, Object> valMap = new TreeMap<String, Object>();
        valMap.put("apiKey", getApiKey());
        Object symbolValue = getSymbol();
        if (symbolValue != null) {
            valMap.put("symbol", symbolValue);
        }
        Object listClientOrderIdValue = getListClientOrderId();
        if (listClientOrderIdValue != null) {
            valMap.put("listClientOrderId", listClientOrderIdValue);
        }
        Object newOrderRespTypeValue = getNewOrderRespType();
        if (newOrderRespTypeValue != null) {
            valMap.put("newOrderRespType", newOrderRespTypeValue);
        }
        Object selfTradePreventionModeValue = getSelfTradePreventionMode();
        if (selfTradePreventionModeValue != null) {
            valMap.put("selfTradePreventionMode", selfTradePreventionModeValue);
        }
        Object workingTypeValue = getWorkingType();
        if (workingTypeValue != null) {
            valMap.put("workingType", workingTypeValue);
        }
        Object workingSideValue = getWorkingSide();
        if (workingSideValue != null) {
            valMap.put("workingSide", workingSideValue);
        }
        Object workingClientOrderIdValue = getWorkingClientOrderId();
        if (workingClientOrderIdValue != null) {
            valMap.put("workingClientOrderId", workingClientOrderIdValue);
        }
        Object workingPriceValue = getWorkingPrice();
        if (workingPriceValue != null) {
            valMap.put("workingPrice", workingPriceValue);
        }
        Object workingQuantityValue = getWorkingQuantity();
        if (workingQuantityValue != null) {
            valMap.put("workingQuantity", workingQuantityValue);
        }
        Object workingIcebergQtyValue = getWorkingIcebergQty();
        if (workingIcebergQtyValue != null) {
            valMap.put("workingIcebergQty", workingIcebergQtyValue);
        }
        Object workingTimeInForceValue = getWorkingTimeInForce();
        if (workingTimeInForceValue != null) {
            valMap.put("workingTimeInForce", workingTimeInForceValue);
        }
        Object workingStrategyIdValue = getWorkingStrategyId();
        if (workingStrategyIdValue != null) {
            valMap.put("workingStrategyId", workingStrategyIdValue);
        }
        Object workingStrategyTypeValue = getWorkingStrategyType();
        if (workingStrategyTypeValue != null) {
            valMap.put("workingStrategyType", workingStrategyTypeValue);
        }
        Object workingPegPriceTypeValue = getWorkingPegPriceType();
        if (workingPegPriceTypeValue != null) {
            valMap.put("workingPegPriceType", workingPegPriceTypeValue);
        }
        Object workingPegOffsetTypeValue = getWorkingPegOffsetType();
        if (workingPegOffsetTypeValue != null) {
            valMap.put("workingPegOffsetType", workingPegOffsetTypeValue);
        }
        Object workingPegOffsetValueValue = getWorkingPegOffsetValue();
        if (workingPegOffsetValueValue != null) {
            valMap.put("workingPegOffsetValue", workingPegOffsetValueValue);
        }
        Object pendingTypeValue = getPendingType();
        if (pendingTypeValue != null) {
            valMap.put("pendingType", pendingTypeValue);
        }
        Object pendingSideValue = getPendingSide();
        if (pendingSideValue != null) {
            valMap.put("pendingSide", pendingSideValue);
        }
        Object pendingClientOrderIdValue = getPendingClientOrderId();
        if (pendingClientOrderIdValue != null) {
            valMap.put("pendingClientOrderId", pendingClientOrderIdValue);
        }
        Object pendingPriceValue = getPendingPrice();
        if (pendingPriceValue != null) {
            valMap.put("pendingPrice", pendingPriceValue);
        }
        Object pendingStopPriceValue = getPendingStopPrice();
        if (pendingStopPriceValue != null) {
            valMap.put("pendingStopPrice", pendingStopPriceValue);
        }
        Object pendingTrailingDeltaValue = getPendingTrailingDelta();
        if (pendingTrailingDeltaValue != null) {
            valMap.put("pendingTrailingDelta", pendingTrailingDeltaValue);
        }
        Object pendingQuantityValue = getPendingQuantity();
        if (pendingQuantityValue != null) {
            valMap.put("pendingQuantity", pendingQuantityValue);
        }
        Object pendingIcebergQtyValue = getPendingIcebergQty();
        if (pendingIcebergQtyValue != null) {
            valMap.put("pendingIcebergQty", pendingIcebergQtyValue);
        }
        Object pendingTimeInForceValue = getPendingTimeInForce();
        if (pendingTimeInForceValue != null) {
            valMap.put("pendingTimeInForce", pendingTimeInForceValue);
        }
        Object pendingStrategyIdValue = getPendingStrategyId();
        if (pendingStrategyIdValue != null) {
            valMap.put("pendingStrategyId", pendingStrategyIdValue);
        }
        Object pendingStrategyTypeValue = getPendingStrategyType();
        if (pendingStrategyTypeValue != null) {
            valMap.put("pendingStrategyType", pendingStrategyTypeValue);
        }
        Object pendingPegOffsetTypeValue = getPendingPegOffsetType();
        if (pendingPegOffsetTypeValue != null) {
            valMap.put("pendingPegOffsetType", pendingPegOffsetTypeValue);
        }
        Object pendingPegPriceTypeValue = getPendingPegPriceType();
        if (pendingPegPriceTypeValue != null) {
            valMap.put("pendingPegPriceType", pendingPegPriceTypeValue);
        }
        Object pendingPegOffsetValueValue = getPendingPegOffsetValue();
        if (pendingPegOffsetValueValue != null) {
            valMap.put("pendingPegOffsetValue", pendingPegOffsetValueValue);
        }
        Object recvWindowValue = getRecvWindow();
        if (recvWindowValue != null) {
            valMap.put("recvWindow", recvWindowValue);
        }

        valMap.put("timestamp", getTimestamp());
        return valMap;
    }

    public static String asciiEncode(String s) {
        return new String(s.getBytes(), StandardCharsets.US_ASCII);
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n		");
    }
}
