/*
 * Binance Spot WebSocket API
 * OpenAPI Specifications for the Binance Spot WebSocket API  API documents:   - [Github web-socket-api documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-api.md)   - [General API information for web-socket-api on website](https://developers.binance.com/docs/binance-spot-api-docs/web-socket-api/general-api-information)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.quarkus.spot.model;

import com.binance.connector.client.common.DecimalFormatter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


import java.io.IOException;
import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.stream.Collectors;

@JsonInclude(JsonInclude.Include.NON_NULL)
public class OrderListPlaceRequest extends BaseDTO {
    public static final String SERIALIZED_NAME_SYMBOL = "symbol";

    @JsonProperty(SERIALIZED_NAME_SYMBOL)

    private String symbol;

    public static final String SERIALIZED_NAME_SIDE = "side";

    @JsonProperty(SERIALIZED_NAME_SIDE)

    private Side side;

    public static final String SERIALIZED_NAME_PRICE = "price";

    @JsonProperty(SERIALIZED_NAME_PRICE)

    private BigDecimal price;

    public static final String SERIALIZED_NAME_QUANTITY = "quantity";

    @JsonProperty(SERIALIZED_NAME_QUANTITY)

    private BigDecimal quantity;

    public static final String SERIALIZED_NAME_LIST_CLIENT_ORDER_ID = "listClientOrderId";

    @JsonProperty(SERIALIZED_NAME_LIST_CLIENT_ORDER_ID)
    
    private String listClientOrderId;

    public static final String SERIALIZED_NAME_LIMIT_CLIENT_ORDER_ID = "limitClientOrderId";

    @JsonProperty(SERIALIZED_NAME_LIMIT_CLIENT_ORDER_ID)
    
    private String limitClientOrderId;

    public static final String SERIALIZED_NAME_LIMIT_ICEBERG_QTY = "limitIcebergQty";

    @JsonProperty(SERIALIZED_NAME_LIMIT_ICEBERG_QTY)
    
    private BigDecimal limitIcebergQty;

    public static final String SERIALIZED_NAME_LIMIT_STRATEGY_ID = "limitStrategyId";

    @JsonProperty(SERIALIZED_NAME_LIMIT_STRATEGY_ID)
    
    private Long limitStrategyId;

    public static final String SERIALIZED_NAME_LIMIT_STRATEGY_TYPE = "limitStrategyType";

    @JsonProperty(SERIALIZED_NAME_LIMIT_STRATEGY_TYPE)
    
    private Integer limitStrategyType;

    public static final String SERIALIZED_NAME_STOP_PRICE = "stopPrice";

    @JsonProperty(SERIALIZED_NAME_STOP_PRICE)
    
    private BigDecimal stopPrice;

    public static final String SERIALIZED_NAME_TRAILING_DELTA = "trailingDelta";

    @JsonProperty(SERIALIZED_NAME_TRAILING_DELTA)
    
    private Integer trailingDelta;

    public static final String SERIALIZED_NAME_STOP_CLIENT_ORDER_ID = "stopClientOrderId";

    @JsonProperty(SERIALIZED_NAME_STOP_CLIENT_ORDER_ID)
    
    private String stopClientOrderId;

    public static final String SERIALIZED_NAME_STOP_LIMIT_PRICE = "stopLimitPrice";

    @JsonProperty(SERIALIZED_NAME_STOP_LIMIT_PRICE)
    
    private BigDecimal stopLimitPrice;

    public static final String SERIALIZED_NAME_STOP_LIMIT_TIME_IN_FORCE = "stopLimitTimeInForce";

    @JsonProperty(SERIALIZED_NAME_STOP_LIMIT_TIME_IN_FORCE)
    
    private StopLimitTimeInForce stopLimitTimeInForce;

    public static final String SERIALIZED_NAME_STOP_ICEBERG_QTY = "stopIcebergQty";

    @JsonProperty(SERIALIZED_NAME_STOP_ICEBERG_QTY)
    
    private BigDecimal stopIcebergQty;

    public static final String SERIALIZED_NAME_STOP_STRATEGY_ID = "stopStrategyId";

    @JsonProperty(SERIALIZED_NAME_STOP_STRATEGY_ID)
    
    private Long stopStrategyId;

    public static final String SERIALIZED_NAME_STOP_STRATEGY_TYPE = "stopStrategyType";

    @JsonProperty(SERIALIZED_NAME_STOP_STRATEGY_TYPE)
    
    private Integer stopStrategyType;

    public static final String SERIALIZED_NAME_NEW_ORDER_RESP_TYPE = "newOrderRespType";

    @JsonProperty(SERIALIZED_NAME_NEW_ORDER_RESP_TYPE)
    
    private NewOrderRespType newOrderRespType;

    public static final String SERIALIZED_NAME_SELF_TRADE_PREVENTION_MODE =
            "selfTradePreventionMode";

    @JsonProperty(SERIALIZED_NAME_SELF_TRADE_PREVENTION_MODE)
    
    private SelfTradePreventionMode selfTradePreventionMode;

    public static final String SERIALIZED_NAME_RECV_WINDOW = "recvWindow";

    @JsonProperty(SERIALIZED_NAME_RECV_WINDOW)
    
    private Long recvWindow;

    public OrderListPlaceRequest() {}

    public OrderListPlaceRequest symbol( String symbol) {
        this.symbol = symbol;
        return this;
    }

    /**
     * Get symbol
     *
     * @return symbol
     */

    
    public String getSymbol() {
        return symbol;
    }

    public void setSymbol( String symbol) {
        this.symbol = symbol;
    }

    public OrderListPlaceRequest side( Side side) {
        this.side = side;
        return this;
    }

    /**
     * Get side
     *
     * @return side
     */

    
    
    public Side getSide() {
        return side;
    }

    public void setSide( Side side) {
        this.side = side;
    }

    public OrderListPlaceRequest price( Double price) {
        this.price = BinanceUtils.asBigDecimal(price);
        return this;
    }

    /**
     * Get price
     *
     * @return price
     */

    
    
    public BigDecimal getPrice() {
        return price;
    }

    public void setPrice( Double price) {
        this.price = BinanceUtils.asBigDecimal(price);
    }

    public OrderListPlaceRequest quantity( Double quantity) {
        this.quantity = BinanceUtils.asBigDecimal(quantity);
        return this;
    }

    /**
     * Get quantity
     *
     * @return quantity
     */

    
    
    public BigDecimal getQuantity() {
        return quantity;
    }

    public void setQuantity( Double quantity) {
        this.quantity = BinanceUtils.asBigDecimal(quantity);
    }

    public OrderListPlaceRequest listClientOrderId(
             String listClientOrderId) {
        this.listClientOrderId = listClientOrderId;
        return this;
    }

    /**
     * Get listClientOrderId
     *
     * @return listClientOrderId
     */
    
    public String getListClientOrderId() {
        return listClientOrderId;
    }

    public void setListClientOrderId( String listClientOrderId) {
        this.listClientOrderId = listClientOrderId;
    }

    public OrderListPlaceRequest limitClientOrderId(
             String limitClientOrderId) {
        this.limitClientOrderId = limitClientOrderId;
        return this;
    }

    /**
     * Get limitClientOrderId
     *
     * @return limitClientOrderId
     */
    
    public String getLimitClientOrderId() {
        return limitClientOrderId;
    }

    public void setLimitClientOrderId( String limitClientOrderId) {
        this.limitClientOrderId = limitClientOrderId;
    }

    public OrderListPlaceRequest limitIcebergQty(
             Double limitIcebergQty) {
        this.limitIcebergQty = BinanceUtils.asBigDecimal(limitIcebergQty);
        return this;
    }

    /**
     * Get limitIcebergQty
     *
     * @return limitIcebergQty
     */
    
    
    public BigDecimal getLimitIcebergQty() {
        return limitIcebergQty;
    }

    public void setLimitIcebergQty( Double limitIcebergQty) {
        this.limitIcebergQty = BinanceUtils.asBigDecimal(limitIcebergQty);
    }

    public OrderListPlaceRequest limitStrategyId(
             Long limitStrategyId) {
        this.limitStrategyId = limitStrategyId;
        return this;
    }

    /**
     * Get limitStrategyId
     *
     * @return limitStrategyId
     */
    
    public Long getLimitStrategyId() {
        return limitStrategyId;
    }

    public void setLimitStrategyId( Long limitStrategyId) {
        this.limitStrategyId = limitStrategyId;
    }

    public OrderListPlaceRequest limitStrategyType(
             Integer limitStrategyType) {
        this.limitStrategyType = limitStrategyType;
        return this;
    }

    /**
     * Get limitStrategyType
     *
     * @return limitStrategyType
     */
    
    public Integer getLimitStrategyType() {
        return limitStrategyType;
    }

    public void setLimitStrategyType( Integer limitStrategyType) {
        this.limitStrategyType = limitStrategyType;
    }

    public OrderListPlaceRequest stopPrice( Double stopPrice) {
        this.stopPrice = BinanceUtils.asBigDecimal(stopPrice);
        return this;
    }

    /**
     * Get stopPrice
     *
     * @return stopPrice
     */
    
    
    public BigDecimal getStopPrice() {
        return stopPrice;
    }

    public void setStopPrice( Double stopPrice) {
        this.stopPrice = BinanceUtils.asBigDecimal(stopPrice);
    }

    public OrderListPlaceRequest trailingDelta( Integer trailingDelta) {
        this.trailingDelta = trailingDelta;
        return this;
    }

    /**
     * Get trailingDelta
     *
     * @return trailingDelta
     */
    
    public Integer getTrailingDelta() {
        return trailingDelta;
    }

    public void setTrailingDelta( Integer trailingDelta) {
        this.trailingDelta = trailingDelta;
    }

    public OrderListPlaceRequest stopClientOrderId(
             String stopClientOrderId) {
        this.stopClientOrderId = stopClientOrderId;
        return this;
    }

    /**
     * Get stopClientOrderId
     *
     * @return stopClientOrderId
     */
    
    public String getStopClientOrderId() {
        return stopClientOrderId;
    }

    public void setStopClientOrderId( String stopClientOrderId) {
        this.stopClientOrderId = stopClientOrderId;
    }

    public OrderListPlaceRequest stopLimitPrice(
             Double stopLimitPrice) {
        this.stopLimitPrice = BinanceUtils.asBigDecimal(stopLimitPrice);
        return this;
    }

    /**
     * Get stopLimitPrice
     *
     * @return stopLimitPrice
     */
    
    
    public BigDecimal getStopLimitPrice() {
        return stopLimitPrice;
    }

    public void setStopLimitPrice( Double stopLimitPrice) {
        this.stopLimitPrice = BinanceUtils.asBigDecimal(stopLimitPrice);
    }

    public OrderListPlaceRequest stopLimitTimeInForce(
             StopLimitTimeInForce stopLimitTimeInForce) {
        this.stopLimitTimeInForce = stopLimitTimeInForce;
        return this;
    }

    /**
     * Get stopLimitTimeInForce
     *
     * @return stopLimitTimeInForce
     */
    
    
    public StopLimitTimeInForce getStopLimitTimeInForce() {
        return stopLimitTimeInForce;
    }

    public void setStopLimitTimeInForce(
             StopLimitTimeInForce stopLimitTimeInForce) {
        this.stopLimitTimeInForce = stopLimitTimeInForce;
    }

    public OrderListPlaceRequest stopIcebergQty(
             Double stopIcebergQty) {
        this.stopIcebergQty = BinanceUtils.asBigDecimal(stopIcebergQty);
        return this;
    }

    /**
     * Get stopIcebergQty
     *
     * @return stopIcebergQty
     */
    
    
    public BigDecimal getStopIcebergQty() {
        return stopIcebergQty;
    }

    public void setStopIcebergQty( Double stopIcebergQty) {
        this.stopIcebergQty = BinanceUtils.asBigDecimal(stopIcebergQty);
    }

    public OrderListPlaceRequest stopStrategyId( Long stopStrategyId) {
        this.stopStrategyId = stopStrategyId;
        return this;
    }

    /**
     * Get stopStrategyId
     *
     * @return stopStrategyId
     */
    
    public Long getStopStrategyId() {
        return stopStrategyId;
    }

    public void setStopStrategyId( Long stopStrategyId) {
        this.stopStrategyId = stopStrategyId;
    }

    public OrderListPlaceRequest stopStrategyType(
             Integer stopStrategyType) {
        this.stopStrategyType = stopStrategyType;
        return this;
    }

    /**
     * Get stopStrategyType
     *
     * @return stopStrategyType
     */
    
    public Integer getStopStrategyType() {
        return stopStrategyType;
    }

    public void setStopStrategyType( Integer stopStrategyType) {
        this.stopStrategyType = stopStrategyType;
    }

    public OrderListPlaceRequest newOrderRespType(
             NewOrderRespType newOrderRespType) {
        this.newOrderRespType = newOrderRespType;
        return this;
    }

    /**
     * Get newOrderRespType
     *
     * @return newOrderRespType
     */
    
    
    public NewOrderRespType getNewOrderRespType() {
        return newOrderRespType;
    }

    public void setNewOrderRespType(
             NewOrderRespType newOrderRespType) {
        this.newOrderRespType = newOrderRespType;
    }

    public OrderListPlaceRequest selfTradePreventionMode(
             SelfTradePreventionMode selfTradePreventionMode) {
        this.selfTradePreventionMode = selfTradePreventionMode;
        return this;
    }

    /**
     * Get selfTradePreventionMode
     *
     * @return selfTradePreventionMode
     */
    
    
    public SelfTradePreventionMode getSelfTradePreventionMode() {
        return selfTradePreventionMode;
    }

    public void setSelfTradePreventionMode(
             SelfTradePreventionMode selfTradePreventionMode) {
        this.selfTradePreventionMode = selfTradePreventionMode;
    }

    public OrderListPlaceRequest recvWindow( Long recvWindow) {
        this.recvWindow = recvWindow;
        return this;
    }

    /**
     * Get recvWindow
     *
     * @return recvWindow
     */
    
    
    public Long getRecvWindow() {
        return recvWindow;
    }

    public void setRecvWindow( Long recvWindow) {
        this.recvWindow = recvWindow;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OrderListPlaceRequest orderListPlaceRequest = (OrderListPlaceRequest) o;
        return Objects.equals(this.symbol, orderListPlaceRequest.symbol)
                && Objects.equals(this.side, orderListPlaceRequest.side)
                && Objects.equals(this.price, orderListPlaceRequest.price)
                && Objects.equals(this.quantity, orderListPlaceRequest.quantity)
                && Objects.equals(this.listClientOrderId, orderListPlaceRequest.listClientOrderId)
                && Objects.equals(this.limitClientOrderId, orderListPlaceRequest.limitClientOrderId)
                && Objects.equals(this.limitIcebergQty, orderListPlaceRequest.limitIcebergQty)
                && Objects.equals(this.limitStrategyId, orderListPlaceRequest.limitStrategyId)
                && Objects.equals(this.limitStrategyType, orderListPlaceRequest.limitStrategyType)
                && Objects.equals(this.stopPrice, orderListPlaceRequest.stopPrice)
                && Objects.equals(this.trailingDelta, orderListPlaceRequest.trailingDelta)
                && Objects.equals(this.stopClientOrderId, orderListPlaceRequest.stopClientOrderId)
                && Objects.equals(this.stopLimitPrice, orderListPlaceRequest.stopLimitPrice)
                && Objects.equals(
                        this.stopLimitTimeInForce, orderListPlaceRequest.stopLimitTimeInForce)
                && Objects.equals(this.stopIcebergQty, orderListPlaceRequest.stopIcebergQty)
                && Objects.equals(this.stopStrategyId, orderListPlaceRequest.stopStrategyId)
                && Objects.equals(this.stopStrategyType, orderListPlaceRequest.stopStrategyType)
                && Objects.equals(this.newOrderRespType, orderListPlaceRequest.newOrderRespType)
                && Objects.equals(
                        this.selfTradePreventionMode, orderListPlaceRequest.selfTradePreventionMode)
                && Objects.equals(this.recvWindow, orderListPlaceRequest.recvWindow);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                symbol,
                side,
                price,
                quantity,
                listClientOrderId,
                limitClientOrderId,
                limitIcebergQty,
                limitStrategyId,
                limitStrategyType,
                stopPrice,
                trailingDelta,
                stopClientOrderId,
                stopLimitPrice,
                stopLimitTimeInForce,
                stopIcebergQty,
                stopStrategyId,
                stopStrategyType,
                newOrderRespType,
                selfTradePreventionMode,
                recvWindow);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class OrderListPlaceRequest {\n");
        sb.append("		symbol: ").append(toIndentedString(symbol)).append("\n");
        sb.append("		side: ").append(toIndentedString(side)).append("\n");
        sb.append("		price: ").append(toIndentedString(price)).append("\n");
        sb.append("		quantity: ").append(toIndentedString(quantity)).append("\n");
        sb.append("		listClientOrderId: ").append(toIndentedString(listClientOrderId)).append("\n");
        sb.append("		limitClientOrderId: ")
                .append(toIndentedString(limitClientOrderId))
                .append("\n");
        sb.append("		limitIcebergQty: ").append(toIndentedString(limitIcebergQty)).append("\n");
        sb.append("		limitStrategyId: ").append(toIndentedString(limitStrategyId)).append("\n");
        sb.append("		limitStrategyType: ").append(toIndentedString(limitStrategyType)).append("\n");
        sb.append("		stopPrice: ").append(toIndentedString(stopPrice)).append("\n");
        sb.append("		trailingDelta: ").append(toIndentedString(trailingDelta)).append("\n");
        sb.append("		stopClientOrderId: ").append(toIndentedString(stopClientOrderId)).append("\n");
        sb.append("		stopLimitPrice: ").append(toIndentedString(stopLimitPrice)).append("\n");
        sb.append("		stopLimitTimeInForce: ")
                .append(toIndentedString(stopLimitTimeInForce))
                .append("\n");
        sb.append("		stopIcebergQty: ").append(toIndentedString(stopIcebergQty)).append("\n");
        sb.append("		stopStrategyId: ").append(toIndentedString(stopStrategyId)).append("\n");
        sb.append("		stopStrategyType: ").append(toIndentedString(stopStrategyType)).append("\n");
        sb.append("		newOrderRespType: ").append(toIndentedString(newOrderRespType)).append("\n");
        sb.append("		selfTradePreventionMode: ")
                .append(toIndentedString(selfTradePreventionMode))
                .append("\n");
        sb.append("		recvWindow: ").append(toIndentedString(recvWindow)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();
        Map<String, String> valMap = new TreeMap<String, String>();
        valMap.put("apiKey", getApiKey());
        String symbolValue = getSymbol();
        if (symbolValue != null) {
            String symbolValueAsString = symbolValue.toString();
            valMap.put("symbol", symbolValueAsString);
        }
        Side sideValue = getSide();
        if (sideValue != null) {
            String sideValueAsString = sideValue.toString();
            valMap.put("side", sideValueAsString);
        }
        BigDecimal priceValue = getPrice();
        if (priceValue != null) {
            String priceValueAsString = DecimalFormatter.getFormatter().format(priceValue);
            valMap.put("price", priceValueAsString);
        }
        BigDecimal quantityValue = getQuantity();
        if (quantityValue != null) {
            String quantityValueAsString = DecimalFormatter.getFormatter().format(quantityValue);
            valMap.put("quantity", quantityValueAsString);
        }
        String listClientOrderIdValue = getListClientOrderId();
        if (listClientOrderIdValue != null) {
            String listClientOrderIdValueAsString = listClientOrderIdValue.toString();
            valMap.put("listClientOrderId", listClientOrderIdValueAsString);
        }
        String limitClientOrderIdValue = getLimitClientOrderId();
        if (limitClientOrderIdValue != null) {
            String limitClientOrderIdValueAsString = limitClientOrderIdValue.toString();
            valMap.put("limitClientOrderId", limitClientOrderIdValueAsString);
        }
        BigDecimal limitIcebergQtyValue = getLimitIcebergQty();
        if (limitIcebergQtyValue != null) {
            String limitIcebergQtyValueAsString =
                    DecimalFormatter.getFormatter().format(limitIcebergQtyValue);
            valMap.put("limitIcebergQty", limitIcebergQtyValueAsString);
        }
        Long limitStrategyIdValue = getLimitStrategyId();
        if (limitStrategyIdValue != null) {
            String limitStrategyIdValueAsString = limitStrategyIdValue.toString();
            valMap.put("limitStrategyId", limitStrategyIdValueAsString);
        }
        Integer limitStrategyTypeValue = getLimitStrategyType();
        if (limitStrategyTypeValue != null) {
            String limitStrategyTypeValueAsString = limitStrategyTypeValue.toString();
            valMap.put("limitStrategyType", limitStrategyTypeValueAsString);
        }
        BigDecimal stopPriceValue = getStopPrice();
        if (stopPriceValue != null) {
            String stopPriceValueAsString = DecimalFormatter.getFormatter().format(stopPriceValue);
            valMap.put("stopPrice", stopPriceValueAsString);
        }
        Integer trailingDeltaValue = getTrailingDelta();
        if (trailingDeltaValue != null) {
            String trailingDeltaValueAsString = trailingDeltaValue.toString();
            valMap.put("trailingDelta", trailingDeltaValueAsString);
        }
        String stopClientOrderIdValue = getStopClientOrderId();
        if (stopClientOrderIdValue != null) {
            String stopClientOrderIdValueAsString = stopClientOrderIdValue.toString();
            valMap.put("stopClientOrderId", stopClientOrderIdValueAsString);
        }
        BigDecimal stopLimitPriceValue = getStopLimitPrice();
        if (stopLimitPriceValue != null) {
            String stopLimitPriceValueAsString =
                    DecimalFormatter.getFormatter().format(stopLimitPriceValue);
            valMap.put("stopLimitPrice", stopLimitPriceValueAsString);
        }
        StopLimitTimeInForce stopLimitTimeInForceValue = getStopLimitTimeInForce();
        if (stopLimitTimeInForceValue != null) {
            String stopLimitTimeInForceValueAsString = stopLimitTimeInForceValue.toString();
            valMap.put("stopLimitTimeInForce", stopLimitTimeInForceValueAsString);
        }
        BigDecimal stopIcebergQtyValue = getStopIcebergQty();
        if (stopIcebergQtyValue != null) {
            String stopIcebergQtyValueAsString =
                    DecimalFormatter.getFormatter().format(stopIcebergQtyValue);
            valMap.put("stopIcebergQty", stopIcebergQtyValueAsString);
        }
        Long stopStrategyIdValue = getStopStrategyId();
        if (stopStrategyIdValue != null) {
            String stopStrategyIdValueAsString = stopStrategyIdValue.toString();
            valMap.put("stopStrategyId", stopStrategyIdValueAsString);
        }
        Integer stopStrategyTypeValue = getStopStrategyType();
        if (stopStrategyTypeValue != null) {
            String stopStrategyTypeValueAsString = stopStrategyTypeValue.toString();
            valMap.put("stopStrategyType", stopStrategyTypeValueAsString);
        }
        NewOrderRespType newOrderRespTypeValue = getNewOrderRespType();
        if (newOrderRespTypeValue != null) {
            String newOrderRespTypeValueAsString = newOrderRespTypeValue.toString();
            valMap.put("newOrderRespType", newOrderRespTypeValueAsString);
        }
        SelfTradePreventionMode selfTradePreventionModeValue = getSelfTradePreventionMode();
        if (selfTradePreventionModeValue != null) {
            String selfTradePreventionModeValueAsString = selfTradePreventionModeValue.toString();
            valMap.put("selfTradePreventionMode", selfTradePreventionModeValueAsString);
        }
        Long recvWindowValue = getRecvWindow();
        if (recvWindowValue != null) {
            String recvWindowValueAsString =
                    DecimalFormatter.getFormatter().format(recvWindowValue);
            valMap.put("recvWindow", recvWindowValueAsString);
        }

        valMap.put("timestamp", getTimestamp());
        return asciiEncode(
                valMap.keySet().stream()
                        .map(key -> key + "=" + valMap.get(key))
                        .collect(Collectors.joining("&")));
    }

    public Map<String, Object> toMap() {
        Map<String, Object> valMap = new TreeMap<String, Object>();
        valMap.put("apiKey", getApiKey());
        Object symbolValue = getSymbol();
        if (symbolValue != null) {
            valMap.put("symbol", symbolValue);
        }
        Object sideValue = getSide();
        if (sideValue != null) {
            valMap.put("side", sideValue);
        }
        Object priceValue = getPrice();
        if (priceValue != null) {
            valMap.put("price", priceValue);
        }
        Object quantityValue = getQuantity();
        if (quantityValue != null) {
            valMap.put("quantity", quantityValue);
        }
        Object listClientOrderIdValue = getListClientOrderId();
        if (listClientOrderIdValue != null) {
            valMap.put("listClientOrderId", listClientOrderIdValue);
        }
        Object limitClientOrderIdValue = getLimitClientOrderId();
        if (limitClientOrderIdValue != null) {
            valMap.put("limitClientOrderId", limitClientOrderIdValue);
        }
        Object limitIcebergQtyValue = getLimitIcebergQty();
        if (limitIcebergQtyValue != null) {
            valMap.put("limitIcebergQty", limitIcebergQtyValue);
        }
        Object limitStrategyIdValue = getLimitStrategyId();
        if (limitStrategyIdValue != null) {
            valMap.put("limitStrategyId", limitStrategyIdValue);
        }
        Object limitStrategyTypeValue = getLimitStrategyType();
        if (limitStrategyTypeValue != null) {
            valMap.put("limitStrategyType", limitStrategyTypeValue);
        }
        Object stopPriceValue = getStopPrice();
        if (stopPriceValue != null) {
            valMap.put("stopPrice", stopPriceValue);
        }
        Object trailingDeltaValue = getTrailingDelta();
        if (trailingDeltaValue != null) {
            valMap.put("trailingDelta", trailingDeltaValue);
        }
        Object stopClientOrderIdValue = getStopClientOrderId();
        if (stopClientOrderIdValue != null) {
            valMap.put("stopClientOrderId", stopClientOrderIdValue);
        }
        Object stopLimitPriceValue = getStopLimitPrice();
        if (stopLimitPriceValue != null) {
            valMap.put("stopLimitPrice", stopLimitPriceValue);
        }
        Object stopLimitTimeInForceValue = getStopLimitTimeInForce();
        if (stopLimitTimeInForceValue != null) {
            valMap.put("stopLimitTimeInForce", stopLimitTimeInForceValue);
        }
        Object stopIcebergQtyValue = getStopIcebergQty();
        if (stopIcebergQtyValue != null) {
            valMap.put("stopIcebergQty", stopIcebergQtyValue);
        }
        Object stopStrategyIdValue = getStopStrategyId();
        if (stopStrategyIdValue != null) {
            valMap.put("stopStrategyId", stopStrategyIdValue);
        }
        Object stopStrategyTypeValue = getStopStrategyType();
        if (stopStrategyTypeValue != null) {
            valMap.put("stopStrategyType", stopStrategyTypeValue);
        }
        Object newOrderRespTypeValue = getNewOrderRespType();
        if (newOrderRespTypeValue != null) {
            valMap.put("newOrderRespType", newOrderRespTypeValue);
        }
        Object selfTradePreventionModeValue = getSelfTradePreventionMode();
        if (selfTradePreventionModeValue != null) {
            valMap.put("selfTradePreventionMode", selfTradePreventionModeValue);
        }
        Object recvWindowValue = getRecvWindow();
        if (recvWindowValue != null) {
            valMap.put("recvWindow", recvWindowValue);
        }

        valMap.put("timestamp", getTimestamp());
        return valMap;
    }

    public static String asciiEncode(String s) {
        return new String(s.getBytes(), StandardCharsets.US_ASCII);
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n		");
    }
}
