/*
 * Binance Spot WebSocket API
 * OpenAPI Specifications for the Binance Spot WebSocket API  API documents:   - [Github web-socket-api documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-api.md)   - [General API information for web-socket-api on website](https://developers.binance.com/docs/binance-spot-api-docs/web-socket-api/general-api-information)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.quarkus.spot.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.vertx.core.json.Json;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.stream.Collectors;

public class OrderListPlaceOcoResponseResult extends BaseDTO {
    public static final String SERIALIZED_NAME_ORDER_LIST_ID = "orderListId";

    @JsonProperty(SERIALIZED_NAME_ORDER_LIST_ID)
    
    private Long orderListId;

    public static final String SERIALIZED_NAME_CONTINGENCY_TYPE = "contingencyType";

    @JsonProperty(SERIALIZED_NAME_CONTINGENCY_TYPE)
    
    private String contingencyType;

    public static final String SERIALIZED_NAME_LIST_STATUS_TYPE = "listStatusType";

    @JsonProperty(SERIALIZED_NAME_LIST_STATUS_TYPE)
    
    private String listStatusType;

    public static final String SERIALIZED_NAME_LIST_ORDER_STATUS = "listOrderStatus";

    @JsonProperty(SERIALIZED_NAME_LIST_ORDER_STATUS)
    
    private String listOrderStatus;

    public static final String SERIALIZED_NAME_LIST_CLIENT_ORDER_ID = "listClientOrderId";

    @JsonProperty(SERIALIZED_NAME_LIST_CLIENT_ORDER_ID)
    
    private String listClientOrderId;

    public static final String SERIALIZED_NAME_TRANSACTION_TIME = "transactionTime";

    @JsonProperty(SERIALIZED_NAME_TRANSACTION_TIME)
    
    private Long transactionTime;

    public static final String SERIALIZED_NAME_SYMBOL = "symbol";

    @JsonProperty(SERIALIZED_NAME_SYMBOL)
    
    private String symbol;

    public static final String SERIALIZED_NAME_ORDERS = "orders";

    @JsonProperty(SERIALIZED_NAME_ORDERS)
    
    private List<OrderListPlaceOcoResponseResultOrdersInner> orders;

    public static final String SERIALIZED_NAME_ORDER_REPORTS = "orderReports";

    @JsonProperty(SERIALIZED_NAME_ORDER_REPORTS)
    
    private List<OrderListPlaceOcoResponseResultOrderReportsInner> orderReports;

    public OrderListPlaceOcoResponseResult() {}

    public OrderListPlaceOcoResponseResult orderListId(
             Long orderListId) {
        this.orderListId = orderListId;
        return this;
    }

    /**
     * Get orderListId
     *
     * @return orderListId
     */
    
    public Long getOrderListId() {
        return orderListId;
    }

    public void setOrderListId( Long orderListId) {
        this.orderListId = orderListId;
    }

    public OrderListPlaceOcoResponseResult contingencyType(
             String contingencyType) {
        this.contingencyType = contingencyType;
        return this;
    }

    /**
     * Get contingencyType
     *
     * @return contingencyType
     */
    
    public String getContingencyType() {
        return contingencyType;
    }

    public void setContingencyType( String contingencyType) {
        this.contingencyType = contingencyType;
    }

    public OrderListPlaceOcoResponseResult listStatusType(
             String listStatusType) {
        this.listStatusType = listStatusType;
        return this;
    }

    /**
     * Get listStatusType
     *
     * @return listStatusType
     */
    
    public String getListStatusType() {
        return listStatusType;
    }

    public void setListStatusType( String listStatusType) {
        this.listStatusType = listStatusType;
    }

    public OrderListPlaceOcoResponseResult listOrderStatus(
             String listOrderStatus) {
        this.listOrderStatus = listOrderStatus;
        return this;
    }

    /**
     * Get listOrderStatus
     *
     * @return listOrderStatus
     */
    
    public String getListOrderStatus() {
        return listOrderStatus;
    }

    public void setListOrderStatus( String listOrderStatus) {
        this.listOrderStatus = listOrderStatus;
    }

    public OrderListPlaceOcoResponseResult listClientOrderId(
             String listClientOrderId) {
        this.listClientOrderId = listClientOrderId;
        return this;
    }

    /**
     * Get listClientOrderId
     *
     * @return listClientOrderId
     */
    
    public String getListClientOrderId() {
        return listClientOrderId;
    }

    public void setListClientOrderId( String listClientOrderId) {
        this.listClientOrderId = listClientOrderId;
    }

    public OrderListPlaceOcoResponseResult transactionTime(
             Long transactionTime) {
        this.transactionTime = transactionTime;
        return this;
    }

    /**
     * Get transactionTime
     *
     * @return transactionTime
     */
    
    public Long getTransactionTime() {
        return transactionTime;
    }

    public void setTransactionTime( Long transactionTime) {
        this.transactionTime = transactionTime;
    }

    public OrderListPlaceOcoResponseResult symbol( String symbol) {
        this.symbol = symbol;
        return this;
    }

    /**
     * Get symbol
     *
     * @return symbol
     */
    
    public String getSymbol() {
        return symbol;
    }

    public void setSymbol( String symbol) {
        this.symbol = symbol;
    }

    public OrderListPlaceOcoResponseResult orders(
            
                    List<OrderListPlaceOcoResponseResultOrdersInner> orders) {
        this.orders = orders;
        return this;
    }

    public OrderListPlaceOcoResponseResult addOrdersItem(
            OrderListPlaceOcoResponseResultOrdersInner ordersItem) {
        if (this.orders == null) {
            this.orders = new ArrayList<>();
        }
        this.orders.add(ordersItem);
        return this;
    }

    /**
     * Get orders
     *
     * @return orders
     */
    
    
    public List<OrderListPlaceOcoResponseResultOrdersInner> getOrders() {
        return orders;
    }

    public void setOrders(
            
                    List<OrderListPlaceOcoResponseResultOrdersInner> orders) {
        this.orders = orders;
    }

    public OrderListPlaceOcoResponseResult orderReports(
            
                    List<OrderListPlaceOcoResponseResultOrderReportsInner> orderReports) {
        this.orderReports = orderReports;
        return this;
    }

    public OrderListPlaceOcoResponseResult addOrderReportsItem(
            OrderListPlaceOcoResponseResultOrderReportsInner orderReportsItem) {
        if (this.orderReports == null) {
            this.orderReports = new ArrayList<>();
        }
        this.orderReports.add(orderReportsItem);
        return this;
    }

    /**
     * Get orderReports
     *
     * @return orderReports
     */
    
    
    public List<OrderListPlaceOcoResponseResultOrderReportsInner> getOrderReports() {
        return orderReports;
    }

    public void setOrderReports(
            
                    List<OrderListPlaceOcoResponseResultOrderReportsInner> orderReports) {
        this.orderReports = orderReports;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OrderListPlaceOcoResponseResult orderListPlaceOcoResponseResult =
                (OrderListPlaceOcoResponseResult) o;
        return Objects.equals(this.orderListId, orderListPlaceOcoResponseResult.orderListId)
                && Objects.equals(
                        this.contingencyType, orderListPlaceOcoResponseResult.contingencyType)
                && Objects.equals(
                        this.listStatusType, orderListPlaceOcoResponseResult.listStatusType)
                && Objects.equals(
                        this.listOrderStatus, orderListPlaceOcoResponseResult.listOrderStatus)
                && Objects.equals(
                        this.listClientOrderId, orderListPlaceOcoResponseResult.listClientOrderId)
                && Objects.equals(
                        this.transactionTime, orderListPlaceOcoResponseResult.transactionTime)
                && Objects.equals(this.symbol, orderListPlaceOcoResponseResult.symbol)
                && Objects.equals(this.orders, orderListPlaceOcoResponseResult.orders)
                && Objects.equals(this.orderReports, orderListPlaceOcoResponseResult.orderReports);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                orderListId,
                contingencyType,
                listStatusType,
                listOrderStatus,
                listClientOrderId,
                transactionTime,
                symbol,
                orders,
                orderReports);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class OrderListPlaceOcoResponseResult {\n");
        sb.append("		orderListId: ").append(toIndentedString(orderListId)).append("\n");
        sb.append("		contingencyType: ").append(toIndentedString(contingencyType)).append("\n");
        sb.append("		listStatusType: ").append(toIndentedString(listStatusType)).append("\n");
        sb.append("		listOrderStatus: ").append(toIndentedString(listOrderStatus)).append("\n");
        sb.append("		listClientOrderId: ").append(toIndentedString(listClientOrderId)).append("\n");
        sb.append("		transactionTime: ").append(toIndentedString(transactionTime)).append("\n");
        sb.append("		symbol: ").append(toIndentedString(symbol)).append("\n");
        sb.append("		orders: ").append(toIndentedString(orders)).append("\n");
        sb.append("		orderReports: ").append(toIndentedString(orderReports)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();
        Map<String, String> valMap = new TreeMap<String, String>();
        valMap.put("apiKey", getApiKey());
        Long orderListIdValue = getOrderListId();
        if (orderListIdValue != null) {
            String orderListIdValueAsString = orderListIdValue.toString();
            valMap.put("orderListId", orderListIdValueAsString);
        }
        String contingencyTypeValue = getContingencyType();
        if (contingencyTypeValue != null) {
            String contingencyTypeValueAsString = contingencyTypeValue.toString();
            valMap.put("contingencyType", contingencyTypeValueAsString);
        }
        String listStatusTypeValue = getListStatusType();
        if (listStatusTypeValue != null) {
            String listStatusTypeValueAsString = listStatusTypeValue.toString();
            valMap.put("listStatusType", listStatusTypeValueAsString);
        }
        String listOrderStatusValue = getListOrderStatus();
        if (listOrderStatusValue != null) {
            String listOrderStatusValueAsString = listOrderStatusValue.toString();
            valMap.put("listOrderStatus", listOrderStatusValueAsString);
        }
        String listClientOrderIdValue = getListClientOrderId();
        if (listClientOrderIdValue != null) {
            String listClientOrderIdValueAsString = listClientOrderIdValue.toString();
            valMap.put("listClientOrderId", listClientOrderIdValueAsString);
        }
        Long transactionTimeValue = getTransactionTime();
        if (transactionTimeValue != null) {
            String transactionTimeValueAsString = transactionTimeValue.toString();
            valMap.put("transactionTime", transactionTimeValueAsString);
        }
        String symbolValue = getSymbol();
        if (symbolValue != null) {
            String symbolValueAsString = symbolValue.toString();
            valMap.put("symbol", symbolValueAsString);
        }
        List<OrderListPlaceOcoResponseResultOrdersInner> ordersValue = getOrders();
        if (ordersValue != null) {
            String ordersValueAsString = Json.encode(ordersValue);
            valMap.put("orders", ordersValueAsString);
        }
        List<OrderListPlaceOcoResponseResultOrderReportsInner> orderReportsValue =
                getOrderReports();
        if (orderReportsValue != null) {
            String orderReportsValueAsString = Json.encode(orderReportsValue);
            valMap.put("orderReports", orderReportsValueAsString);
        }

        valMap.put("timestamp", getTimestamp());
        return asciiEncode(
                valMap.keySet().stream()
                        .map(key -> key + "=" + valMap.get(key))
                        .collect(Collectors.joining("&")));
    }

    public Map<String, Object> toMap() {
        Map<String, Object> valMap = new TreeMap<String, Object>();
        valMap.put("apiKey", getApiKey());
        Object orderListIdValue = getOrderListId();
        if (orderListIdValue != null) {
            valMap.put("orderListId", orderListIdValue);
        }
        Object contingencyTypeValue = getContingencyType();
        if (contingencyTypeValue != null) {
            valMap.put("contingencyType", contingencyTypeValue);
        }
        Object listStatusTypeValue = getListStatusType();
        if (listStatusTypeValue != null) {
            valMap.put("listStatusType", listStatusTypeValue);
        }
        Object listOrderStatusValue = getListOrderStatus();
        if (listOrderStatusValue != null) {
            valMap.put("listOrderStatus", listOrderStatusValue);
        }
        Object listClientOrderIdValue = getListClientOrderId();
        if (listClientOrderIdValue != null) {
            valMap.put("listClientOrderId", listClientOrderIdValue);
        }
        Object transactionTimeValue = getTransactionTime();
        if (transactionTimeValue != null) {
            valMap.put("transactionTime", transactionTimeValue);
        }
        Object symbolValue = getSymbol();
        if (symbolValue != null) {
            valMap.put("symbol", symbolValue);
        }
        Object ordersValue = getOrders();
        if (ordersValue != null) {
            valMap.put("orders", ordersValue);
        }
        Object orderReportsValue = getOrderReports();
        if (orderReportsValue != null) {
            valMap.put("orderReports", orderReportsValue);
        }

        valMap.put("timestamp", getTimestamp());
        return valMap;
    }

    public static String asciiEncode(String s) {
        return new String(s.getBytes(), StandardCharsets.US_ASCII);
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n		");
    }
}
