/*
 * Binance Spot WebSocket API
 * OpenAPI Specifications for the Binance Spot WebSocket API  API documents:   - [Github web-socket-api documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-api.md)   - [General API information for web-socket-api on website](https://developers.binance.com/docs/binance-spot-api-docs/web-socket-api/general-api-information)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.quarkus.spot.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.stream.Collectors;

public class OutboundAccountPositionBInner {
    public static final String SERIALIZED_NAME_A_LOWER_CASE = "a";

    @JsonProperty(SERIALIZED_NAME_A_LOWER_CASE)
    
    private String aLowerCase;

    public static final String SERIALIZED_NAME_F_LOWER_CASE = "f";

    @JsonProperty(SERIALIZED_NAME_F_LOWER_CASE)
    
    private String fLowerCase;

    public static final String SERIALIZED_NAME_L_LOWER_CASE = "l";

    @JsonProperty(SERIALIZED_NAME_L_LOWER_CASE)
    
    private String lLowerCase;
    /**
     * Get aLowerCase
     *
     * @return aLowerCase
     */
    
    public String getaLowerCase() {
        return aLowerCase;
    }

    public void setaLowerCase( String aLowerCase) {
        this.aLowerCase = aLowerCase;
    }
    /**
     * Get fLowerCase
     *
     * @return fLowerCase
     */
    
    public String getfLowerCase() {
        return fLowerCase;
    }

    public void setfLowerCase( String fLowerCase) {
        this.fLowerCase = fLowerCase;
    }

    /**
     * Get lLowerCase
     *
     * @return lLowerCase
     */
    
    public String getlLowerCase() {
        return lLowerCase;
    }

    public void setlLowerCase( String lLowerCase) {
        this.lLowerCase = lLowerCase;
    }
}
