/*
 * Binance Spot WebSocket Streams
 * OpenAPI Specifications for the Binance Spot WebSocket Streams  API documents:   - [Github web-socket-streams documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-streams.md)   - [General API information for web-socket-streams on website](https://developers.binance.com/docs/binance-spot-api-docs/web-socket-streams)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.quarkus.spot.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.stream.Collectors;

@JsonInclude(JsonInclude.Include.NON_NULL)
public class PartialBookDepthRequest extends BaseDTO {
    public static final String SERIALIZED_NAME_SYMBOL = "symbol";

    @JsonProperty(SERIALIZED_NAME_SYMBOL)

    private String symbol;

    public static final String SERIALIZED_NAME_LEVELS = "levels";

    @JsonProperty(SERIALIZED_NAME_LEVELS)

    private Levels levels;

    public static final String SERIALIZED_NAME_UPDATE_SPEED = "updateSpeed";

    @JsonProperty(SERIALIZED_NAME_UPDATE_SPEED)
    
    private String updateSpeed;

    public PartialBookDepthRequest() {}

    public PartialBookDepthRequest symbol( String symbol) {
        this.symbol = symbol;
        return this;
    }

    /**
     * Get symbol
     *
     * @return symbol
     */

    
    public String getSymbol() {
        return symbol;
    }

    public void setSymbol( String symbol) {
        this.symbol = symbol;
    }

    public PartialBookDepthRequest levels( Levels levels) {
        this.levels = levels;
        return this;
    }

    /**
     * Get levels
     *
     * @return levels
     */

    
    
    public Levels getLevels() {
        return levels;
    }

    public void setLevels( Levels levels) {
        this.levels = levels;
    }

    public PartialBookDepthRequest updateSpeed( String updateSpeed) {
        this.updateSpeed = updateSpeed;
        return this;
    }

    /**
     * Get updateSpeed
     *
     * @return updateSpeed
     */
    
    public String getUpdateSpeed() {
        return updateSpeed;
    }

    public void setUpdateSpeed( String updateSpeed) {
        this.updateSpeed = updateSpeed;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PartialBookDepthRequest partialBookDepthRequest = (PartialBookDepthRequest) o;
        return Objects.equals(this.symbol, partialBookDepthRequest.symbol)
                && Objects.equals(this.levels, partialBookDepthRequest.levels)
                && Objects.equals(this.updateSpeed, partialBookDepthRequest.updateSpeed);
    }

    @Override
    public int hashCode() {
        return Objects.hash(symbol, levels, updateSpeed);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PartialBookDepthRequest {\n");
        sb.append("		symbol: ").append(toIndentedString(symbol)).append("\n");
        sb.append("		levels: ").append(toIndentedString(levels)).append("\n");
        sb.append("		updateSpeed: ").append(toIndentedString(updateSpeed)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();
        Map<String, String> valMap = new TreeMap<String, String>();
        valMap.put("apiKey", getApiKey());
        String symbolValue = getSymbol();
        if (symbolValue != null) {
            String symbolValueAsString = symbolValue.toString();
            valMap.put("symbol", symbolValueAsString);
        }
        Levels levelsValue = getLevels();
        if (levelsValue != null) {
            String levelsValueAsString = levelsValue.toString();
            valMap.put("levels", levelsValueAsString);
        }
        String updateSpeedValue = getUpdateSpeed();
        if (updateSpeedValue != null) {
            String updateSpeedValueAsString = updateSpeedValue.toString();
            valMap.put("updateSpeed", updateSpeedValueAsString);
        }

        valMap.put("timestamp", getTimestamp());
        return asciiEncode(
                valMap.keySet().stream()
                        .map(key -> key + "=" + valMap.get(key))
                        .collect(Collectors.joining("&")));
    }

    public Map<String, Object> toMap() {
        Map<String, Object> valMap = new TreeMap<String, Object>();
        valMap.put("apiKey", getApiKey());
        Object symbolValue = getSymbol();
        if (symbolValue != null) {
            valMap.put("symbol", symbolValue);
        }
        Object levelsValue = getLevels();
        if (levelsValue != null) {
            valMap.put("levels", levelsValue);
        }
        Object updateSpeedValue = getUpdateSpeed();
        if (updateSpeedValue != null) {
            valMap.put("updateSpeed", updateSpeedValue);
        }

        valMap.put("timestamp", getTimestamp());
        return valMap;
    }

    public static String asciiEncode(String s) {
        return new String(s.getBytes(), StandardCharsets.US_ASCII);
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n		");
    }

}
