/*
 * Binance Spot WebSocket API
 * OpenAPI Specifications for the Binance Spot WebSocket API  API documents:   - [Github web-socket-api documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-api.md)   - [General API information for web-socket-api on website](https://developers.binance.com/docs/binance-spot-api-docs/web-socket-api/general-api-information)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.quarkus.spot.model;

import com.binance.connector.client.common.AbstractOpenApiSchema;








import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Ticker24hrResponse extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(Ticker24hrResponse.class.getName());

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public Ticker24hrResponse() {
        super("oneOf", Boolean.FALSE);
    }

    public Ticker24hrResponse(Object o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("Ticker24hrResponse1", Ticker24hrResponse1.class);
        schemas.put("Ticker24hrResponse2", Ticker24hrResponse2.class);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return Ticker24hrResponse.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check the instance parameter is valid
     * against the oneOf child schemas: Ticker24hrResponse1, Ticker24hrResponse2
     *
     * <p>It could be an instance of the 'oneOf' schemas.
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof Ticker24hrResponse1) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof Ticker24hrResponse2) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException(
                "Invalid instance type. Must be Ticker24hrResponse1, Ticker24hrResponse2");
    }

    /**
     * Get the actual instance, which can be the following: Ticker24hrResponse1, Ticker24hrResponse2
     *
     * @return The actual instance (Ticker24hrResponse1, Ticker24hrResponse2)
     */
    @SuppressWarnings("unchecked")
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `Ticker24hrResponse1`. If the actual instance is not
     * `Ticker24hrResponse1`, the ClassCastException will be thrown.
     *
     * @return The actual instance of `Ticker24hrResponse1`
     * @throws ClassCastException if the instance is not `Ticker24hrResponse1`
     */
    public Ticker24hrResponse1 getTicker24hrResponse1() throws ClassCastException {
        return (Ticker24hrResponse1) super.getActualInstance();
    }

    /**
     * Get the actual instance of `Ticker24hrResponse2`. If the actual instance is not
     * `Ticker24hrResponse2`, the ClassCastException will be thrown.
     *
     * @return The actual instance of `Ticker24hrResponse2`
     * @throws ClassCastException if the instance is not `Ticker24hrResponse2`
     */
    public Ticker24hrResponse2 getTicker24hrResponse2() throws ClassCastException {
        return (Ticker24hrResponse2) super.getActualInstance();
    }

}
