/*
 * Binance Spot WebSocket API
 * OpenAPI Specifications for the Binance Spot WebSocket API  API documents:   - [Github web-socket-api documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-api.md)   - [General API information for web-socket-api on website](https://developers.binance.com/docs/binance-spot-api-docs/web-socket-api/general-api-information)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.quarkus.spot.model;

import com.binance.connector.client.common.AbstractOpenApiSchema;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;


public class TickerBookResponse extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(TickerBookResponse.class.getName());

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public TickerBookResponse() {
        super("oneOf", Boolean.FALSE);
    }

    public TickerBookResponse(Object o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("TickerBookResponse1", TickerBookResponse1.class);
        schemas.put("TickerBookResponse2", TickerBookResponse2.class);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return TickerBookResponse.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check the instance parameter is valid
     * against the oneOf child schemas: TickerBookResponse1, TickerBookResponse2
     *
     * <p>It could be an instance of the 'oneOf' schemas.
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof TickerBookResponse1) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof TickerBookResponse2) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException(
                "Invalid instance type. Must be TickerBookResponse1, TickerBookResponse2");
    }

    /**
     * Get the actual instance, which can be the following: TickerBookResponse1, TickerBookResponse2
     *
     * @return The actual instance (TickerBookResponse1, TickerBookResponse2)
     */
    @SuppressWarnings("unchecked")
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `TickerBookResponse1`. If the actual instance is not
     * `TickerBookResponse1`, the ClassCastException will be thrown.
     *
     * @return The actual instance of `TickerBookResponse1`
     * @throws ClassCastException if the instance is not `TickerBookResponse1`
     */
    public TickerBookResponse1 getTickerBookResponse1() throws ClassCastException {
        return (TickerBookResponse1) super.getActualInstance();
    }

    /**
     * Get the actual instance of `TickerBookResponse2`. If the actual instance is not
     * `TickerBookResponse2`, the ClassCastException will be thrown.
     *
     * @return The actual instance of `TickerBookResponse2`
     * @throws ClassCastException if the instance is not `TickerBookResponse2`
     */
    public TickerBookResponse2 getTickerBookResponse2() throws ClassCastException {
        return (TickerBookResponse2) super.getActualInstance();
    }
}
