/*
 * Binance Spot WebSocket API
 * OpenAPI Specifications for the Binance Spot WebSocket API  API documents:   - [Github web-socket-api documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-api.md)   - [General API information for web-socket-api on website](https://developers.binance.com/docs/binance-spot-api-docs/web-socket-api/general-api-information)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.quarkus.spot.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.stream.Collectors;

public class TradesHistoricalResponseResultInner extends BaseDTO {
    public static final String SERIALIZED_NAME_ID = "id";

    @JsonProperty(SERIALIZED_NAME_ID)
    
    private Long id;

    public static final String SERIALIZED_NAME_PRICE = "price";

    @JsonProperty(SERIALIZED_NAME_PRICE)
    
    private String price;

    public static final String SERIALIZED_NAME_QTY = "qty";

    @JsonProperty(SERIALIZED_NAME_QTY)
    
    private String qty;

    public static final String SERIALIZED_NAME_QUOTE_QTY = "quoteQty";

    @JsonProperty(SERIALIZED_NAME_QUOTE_QTY)
    
    private String quoteQty;

    public static final String SERIALIZED_NAME_TIME = "time";

    @JsonProperty(SERIALIZED_NAME_TIME)
    
    private Long time;

    public static final String SERIALIZED_NAME_IS_BUYER_MAKER = "isBuyerMaker";

    @JsonProperty(SERIALIZED_NAME_IS_BUYER_MAKER)
    
    private Boolean isBuyerMaker;

    public static final String SERIALIZED_NAME_IS_BEST_MATCH = "isBestMatch";

    @JsonProperty(SERIALIZED_NAME_IS_BEST_MATCH)
    
    private Boolean isBestMatch;

    public TradesHistoricalResponseResultInner() {}

    public TradesHistoricalResponseResultInner id( Long id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     */
    
    public Long getId() {
        return id;
    }

    public void setId( Long id) {
        this.id = id;
    }

    public TradesHistoricalResponseResultInner price( String price) {
        this.price = price;
        return this;
    }

    /**
     * Get price
     *
     * @return price
     */
    
    public String getPrice() {
        return price;
    }

    public void setPrice( String price) {
        this.price = price;
    }

    public TradesHistoricalResponseResultInner qty( String qty) {
        this.qty = qty;
        return this;
    }

    /**
     * Get qty
     *
     * @return qty
     */
    
    public String getQty() {
        return qty;
    }

    public void setQty( String qty) {
        this.qty = qty;
    }

    public TradesHistoricalResponseResultInner quoteQty(
             String quoteQty) {
        this.quoteQty = quoteQty;
        return this;
    }

    /**
     * Get quoteQty
     *
     * @return quoteQty
     */
    
    public String getQuoteQty() {
        return quoteQty;
    }

    public void setQuoteQty( String quoteQty) {
        this.quoteQty = quoteQty;
    }

    public TradesHistoricalResponseResultInner time( Long time) {
        this.time = time;
        return this;
    }

    /**
     * Get time
     *
     * @return time
     */
    
    public Long getTime() {
        return time;
    }

    public void setTime( Long time) {
        this.time = time;
    }

    public TradesHistoricalResponseResultInner isBuyerMaker(
             Boolean isBuyerMaker) {
        this.isBuyerMaker = isBuyerMaker;
        return this;
    }

    /**
     * Get isBuyerMaker
     *
     * @return isBuyerMaker
     */
    
    public Boolean getIsBuyerMaker() {
        return isBuyerMaker;
    }

    public void setIsBuyerMaker( Boolean isBuyerMaker) {
        this.isBuyerMaker = isBuyerMaker;
    }

    public TradesHistoricalResponseResultInner isBestMatch(
             Boolean isBestMatch) {
        this.isBestMatch = isBestMatch;
        return this;
    }

    /**
     * Get isBestMatch
     *
     * @return isBestMatch
     */
    
    public Boolean getIsBestMatch() {
        return isBestMatch;
    }

    public void setIsBestMatch( Boolean isBestMatch) {
        this.isBestMatch = isBestMatch;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TradesHistoricalResponseResultInner tradesHistoricalResponseResultInner =
                (TradesHistoricalResponseResultInner) o;
        return Objects.equals(this.id, tradesHistoricalResponseResultInner.id)
                && Objects.equals(this.price, tradesHistoricalResponseResultInner.price)
                && Objects.equals(this.qty, tradesHistoricalResponseResultInner.qty)
                && Objects.equals(this.quoteQty, tradesHistoricalResponseResultInner.quoteQty)
                && Objects.equals(this.time, tradesHistoricalResponseResultInner.time)
                && Objects.equals(
                        this.isBuyerMaker, tradesHistoricalResponseResultInner.isBuyerMaker)
                && Objects.equals(
                        this.isBestMatch, tradesHistoricalResponseResultInner.isBestMatch);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, price, qty, quoteQty, time, isBuyerMaker, isBestMatch);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class TradesHistoricalResponseResultInner {\n");
        sb.append("		id: ").append(toIndentedString(id)).append("\n");
        sb.append("		price: ").append(toIndentedString(price)).append("\n");
        sb.append("		qty: ").append(toIndentedString(qty)).append("\n");
        sb.append("		quoteQty: ").append(toIndentedString(quoteQty)).append("\n");
        sb.append("		time: ").append(toIndentedString(time)).append("\n");
        sb.append("		isBuyerMaker: ").append(toIndentedString(isBuyerMaker)).append("\n");
        sb.append("		isBestMatch: ").append(toIndentedString(isBestMatch)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();
        Map<String, String> valMap = new TreeMap<String, String>();
        valMap.put("apiKey", getApiKey());
        Long idValue = getId();
        if (idValue != null) {
            String idValueAsString = idValue.toString();
            valMap.put("id", idValueAsString);
        }
        String priceValue = getPrice();
        if (priceValue != null) {
            String priceValueAsString = priceValue.toString();
            valMap.put("price", priceValueAsString);
        }
        String qtyValue = getQty();
        if (qtyValue != null) {
            String qtyValueAsString = qtyValue.toString();
            valMap.put("qty", qtyValueAsString);
        }
        String quoteQtyValue = getQuoteQty();
        if (quoteQtyValue != null) {
            String quoteQtyValueAsString = quoteQtyValue.toString();
            valMap.put("quoteQty", quoteQtyValueAsString);
        }
        Long timeValue = getTime();
        if (timeValue != null) {
            String timeValueAsString = timeValue.toString();
            valMap.put("time", timeValueAsString);
        }
        Boolean isBuyerMakerValue = getIsBuyerMaker();
        if (isBuyerMakerValue != null) {
            String isBuyerMakerValueAsString = isBuyerMakerValue.toString();
            valMap.put("isBuyerMaker", isBuyerMakerValueAsString);
        }
        Boolean isBestMatchValue = getIsBestMatch();
        if (isBestMatchValue != null) {
            String isBestMatchValueAsString = isBestMatchValue.toString();
            valMap.put("isBestMatch", isBestMatchValueAsString);
        }

        valMap.put("timestamp", getTimestamp());
        return asciiEncode(
                valMap.keySet().stream()
                        .map(key -> key + "=" + valMap.get(key))
                        .collect(Collectors.joining("&")));
    }

    public Map<String, Object> toMap() {
        Map<String, Object> valMap = new TreeMap<String, Object>();
        valMap.put("apiKey", getApiKey());
        Object idValue = getId();
        if (idValue != null) {
            valMap.put("id", idValue);
        }
        Object priceValue = getPrice();
        if (priceValue != null) {
            valMap.put("price", priceValue);
        }
        Object qtyValue = getQty();
        if (qtyValue != null) {
            valMap.put("qty", qtyValue);
        }
        Object quoteQtyValue = getQuoteQty();
        if (quoteQtyValue != null) {
            valMap.put("quoteQty", quoteQtyValue);
        }
        Object timeValue = getTime();
        if (timeValue != null) {
            valMap.put("time", timeValue);
        }
        Object isBuyerMakerValue = getIsBuyerMaker();
        if (isBuyerMakerValue != null) {
            valMap.put("isBuyerMaker", isBuyerMakerValue);
        }
        Object isBestMatchValue = getIsBestMatch();
        if (isBestMatchValue != null) {
            valMap.put("isBestMatch", isBestMatchValue);
        }

        valMap.put("timestamp", getTimestamp());
        return valMap;
    }

    public static String asciiEncode(String s) {
        return new String(s.getBytes(), StandardCharsets.US_ASCII);
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n		");
    }

}
