/*
 * Binance Spot WebSocket API
 * OpenAPI Specifications for the Binance Spot WebSocket API  API documents:   - [Github web-socket-api documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-api.md)   - [General API information for web-socket-api on website](https://developers.binance.com/docs/binance-spot-api-docs/web-socket-api/general-api-information)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.quarkus.spot.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.stream.Collectors;

public class TradesAggregateRequest extends BaseDTO {
    public static final String SERIALIZED_NAME_SYMBOL = "symbol";

    @JsonProperty(SERIALIZED_NAME_SYMBOL)
    
    private String symbol;

    public static final String SERIALIZED_NAME_FROM_ID = "fromId";

    @JsonProperty(SERIALIZED_NAME_FROM_ID)
    
    private Integer fromId;

    public static final String SERIALIZED_NAME_START_TIME = "startTime";

    @JsonProperty(SERIALIZED_NAME_START_TIME)
    
    private Long startTime;

    public static final String SERIALIZED_NAME_END_TIME = "endTime";

    @JsonProperty(SERIALIZED_NAME_END_TIME)
    
    private Long endTime;

    public static final String SERIALIZED_NAME_LIMIT = "limit";

    @JsonProperty(SERIALIZED_NAME_LIMIT)
    
    private Integer limit;

    public TradesAggregateRequest() {}

    public TradesAggregateRequest symbol( String symbol) {
        this.symbol = symbol;
        return this;
    }

    /**
     * Get symbol
     *
     * @return symbol
     */
    
    
    public String getSymbol() {
        return symbol;
    }

    public void setSymbol( String symbol) {
        this.symbol = symbol;
    }

    public TradesAggregateRequest fromId( Integer fromId) {
        this.fromId = fromId;
        return this;
    }

    /**
     * Get fromId
     *
     * @return fromId
     */
    
    public Integer getFromId() {
        return fromId;
    }

    public void setFromId( Integer fromId) {
        this.fromId = fromId;
    }

    public TradesAggregateRequest startTime( Long startTime) {
        this.startTime = startTime;
        return this;
    }

    /**
     * Get startTime
     *
     * @return startTime
     */
    
    public Long getStartTime() {
        return startTime;
    }

    public void setStartTime( Long startTime) {
        this.startTime = startTime;
    }

    public TradesAggregateRequest endTime( Long endTime) {
        this.endTime = endTime;
        return this;
    }

    /**
     * Get endTime
     *
     * @return endTime
     */
    
    public Long getEndTime() {
        return endTime;
    }

    public void setEndTime( Long endTime) {
        this.endTime = endTime;
    }

    public TradesAggregateRequest limit( Integer limit) {
        this.limit = limit;
        return this;
    }

    /**
     * Get limit
     *
     * @return limit
     */
    
    public Integer getLimit() {
        return limit;
    }

    public void setLimit( Integer limit) {
        this.limit = limit;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TradesAggregateRequest tradesAggregateRequest = (TradesAggregateRequest) o;
        return Objects.equals(this.symbol, tradesAggregateRequest.symbol)
                && Objects.equals(this.fromId, tradesAggregateRequest.fromId)
                && Objects.equals(this.startTime, tradesAggregateRequest.startTime)
                && Objects.equals(this.endTime, tradesAggregateRequest.endTime)
                && Objects.equals(this.limit, tradesAggregateRequest.limit);
    }

    @Override
    public int hashCode() {
        return Objects.hash(symbol, fromId, startTime, endTime, limit);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class TradesAggregateRequest {\n");
        sb.append("		symbol: ").append(toIndentedString(symbol)).append("\n");
        sb.append("		fromId: ").append(toIndentedString(fromId)).append("\n");
        sb.append("		startTime: ").append(toIndentedString(startTime)).append("\n");
        sb.append("		endTime: ").append(toIndentedString(endTime)).append("\n");
        sb.append("		limit: ").append(toIndentedString(limit)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();
        Map<String, String> valMap = new TreeMap<String, String>();
        valMap.put("apiKey", getApiKey());
        String symbolValue = getSymbol();
        if (symbolValue != null) {
            String symbolValueAsString = symbolValue.toString();
            valMap.put("symbol", symbolValueAsString);
        }
        Integer fromIdValue = getFromId();
        if (fromIdValue != null) {
            String fromIdValueAsString = fromIdValue.toString();
            valMap.put("fromId", fromIdValueAsString);
        }
        Long startTimeValue = getStartTime();
        if (startTimeValue != null) {
            String startTimeValueAsString = startTimeValue.toString();
            valMap.put("startTime", startTimeValueAsString);
        }
        Long endTimeValue = getEndTime();
        if (endTimeValue != null) {
            String endTimeValueAsString = endTimeValue.toString();
            valMap.put("endTime", endTimeValueAsString);
        }
        Integer limitValue = getLimit();
        if (limitValue != null) {
            String limitValueAsString = limitValue.toString();
            valMap.put("limit", limitValueAsString);
        }

        valMap.put("timestamp", getTimestamp());
        return asciiEncode(
                valMap.keySet().stream()
                        .map(key -> key + "=" + valMap.get(key))
                        .collect(Collectors.joining("&")));
    }

    public Map<String, Object> toMap() {
        Map<String, Object> valMap = new TreeMap<String, Object>();
        valMap.put("apiKey", getApiKey());
        Object symbolValue = getSymbol();
        if (symbolValue != null) {
            valMap.put("symbol", symbolValue);
        }
        Object fromIdValue = getFromId();
        if (fromIdValue != null) {
            valMap.put("fromId", fromIdValue);
        }
        Object startTimeValue = getStartTime();
        if (startTimeValue != null) {
            valMap.put("startTime", startTimeValue);
        }
        Object endTimeValue = getEndTime();
        if (endTimeValue != null) {
            valMap.put("endTime", endTimeValue);
        }
        Object limitValue = getLimit();
        if (limitValue != null) {
            valMap.put("limit", limitValue);
        }

        valMap.put("timestamp", getTimestamp());
        return valMap;
    }

    public static String asciiEncode(String s) {
        return new String(s.getBytes(), StandardCharsets.US_ASCII);
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n		");
    }

}
