/*
 * Binance Spot WebSocket API
 * OpenAPI Specifications for the Binance Spot WebSocket API  API documents:   - [Github web-socket-api documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-api.md)   - [General API information for web-socket-api on website](https://developers.binance.com/docs/binance-spot-api-docs/web-socket-api/general-api-information)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.quarkus.spot.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.stream.Collectors;

public class TrailingDeltaFilter extends BaseDTO {
    public static final String SERIALIZED_NAME_FILTER_TYPE = "filterType";

    @JsonProperty(SERIALIZED_NAME_FILTER_TYPE)
    
    private String filterType;

    public static final String SERIALIZED_NAME_MIN_TRAILING_ABOVE_DELTA = "minTrailingAboveDelta";

    @JsonProperty(SERIALIZED_NAME_MIN_TRAILING_ABOVE_DELTA)
    
    private Long minTrailingAboveDelta;

    public static final String SERIALIZED_NAME_MAX_TRAILING_ABOVE_DELTA = "maxTrailingAboveDelta";

    @JsonProperty(SERIALIZED_NAME_MAX_TRAILING_ABOVE_DELTA)
    
    private Long maxTrailingAboveDelta;

    public static final String SERIALIZED_NAME_MIN_TRAILING_BELOW_DELTA = "minTrailingBelowDelta";

    @JsonProperty(SERIALIZED_NAME_MIN_TRAILING_BELOW_DELTA)
    
    private Long minTrailingBelowDelta;

    public static final String SERIALIZED_NAME_MAX_TRAILING_BELOW_DELTA = "maxTrailingBelowDelta";

    @JsonProperty(SERIALIZED_NAME_MAX_TRAILING_BELOW_DELTA)
    
    private Long maxTrailingBelowDelta;

    public TrailingDeltaFilter() {}

    public TrailingDeltaFilter filterType( String filterType) {
        this.filterType = filterType;
        return this;
    }

    /**
     * Get filterType
     *
     * @return filterType
     */
    
    public String getFilterType() {
        return filterType;
    }

    public void setFilterType( String filterType) {
        this.filterType = filterType;
    }

    public TrailingDeltaFilter minTrailingAboveDelta(
             Long minTrailingAboveDelta) {
        this.minTrailingAboveDelta = minTrailingAboveDelta;
        return this;
    }

    /**
     * Get minTrailingAboveDelta
     *
     * @return minTrailingAboveDelta
     */
    
    public Long getMinTrailingAboveDelta() {
        return minTrailingAboveDelta;
    }

    public void setMinTrailingAboveDelta( Long minTrailingAboveDelta) {
        this.minTrailingAboveDelta = minTrailingAboveDelta;
    }

    public TrailingDeltaFilter maxTrailingAboveDelta(
             Long maxTrailingAboveDelta) {
        this.maxTrailingAboveDelta = maxTrailingAboveDelta;
        return this;
    }

    /**
     * Get maxTrailingAboveDelta
     *
     * @return maxTrailingAboveDelta
     */
    
    public Long getMaxTrailingAboveDelta() {
        return maxTrailingAboveDelta;
    }

    public void setMaxTrailingAboveDelta( Long maxTrailingAboveDelta) {
        this.maxTrailingAboveDelta = maxTrailingAboveDelta;
    }

    public TrailingDeltaFilter minTrailingBelowDelta(
             Long minTrailingBelowDelta) {
        this.minTrailingBelowDelta = minTrailingBelowDelta;
        return this;
    }

    /**
     * Get minTrailingBelowDelta
     *
     * @return minTrailingBelowDelta
     */
    
    public Long getMinTrailingBelowDelta() {
        return minTrailingBelowDelta;
    }

    public void setMinTrailingBelowDelta( Long minTrailingBelowDelta) {
        this.minTrailingBelowDelta = minTrailingBelowDelta;
    }

    public TrailingDeltaFilter maxTrailingBelowDelta(
             Long maxTrailingBelowDelta) {
        this.maxTrailingBelowDelta = maxTrailingBelowDelta;
        return this;
    }

    /**
     * Get maxTrailingBelowDelta
     *
     * @return maxTrailingBelowDelta
     */
    
    public Long getMaxTrailingBelowDelta() {
        return maxTrailingBelowDelta;
    }

    public void setMaxTrailingBelowDelta( Long maxTrailingBelowDelta) {
        this.maxTrailingBelowDelta = maxTrailingBelowDelta;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TrailingDeltaFilter trailingDeltaFilter = (TrailingDeltaFilter) o;
        return Objects.equals(this.filterType, trailingDeltaFilter.filterType)
                && Objects.equals(
                        this.minTrailingAboveDelta, trailingDeltaFilter.minTrailingAboveDelta)
                && Objects.equals(
                        this.maxTrailingAboveDelta, trailingDeltaFilter.maxTrailingAboveDelta)
                && Objects.equals(
                        this.minTrailingBelowDelta, trailingDeltaFilter.minTrailingBelowDelta)
                && Objects.equals(
                        this.maxTrailingBelowDelta, trailingDeltaFilter.maxTrailingBelowDelta);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                filterType,
                minTrailingAboveDelta,
                maxTrailingAboveDelta,
                minTrailingBelowDelta,
                maxTrailingBelowDelta);
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();
        Map<String, String> valMap = new TreeMap<String, String>();
        valMap.put("apiKey", getApiKey());
        String filterTypeValue = getFilterType();
        if (filterTypeValue != null) {
            String filterTypeValueAsString = filterTypeValue.toString();
            valMap.put("filterType", filterTypeValueAsString);
        }
        Long minTrailingAboveDeltaValue = getMinTrailingAboveDelta();
        if (minTrailingAboveDeltaValue != null) {
            String minTrailingAboveDeltaValueAsString = minTrailingAboveDeltaValue.toString();
            valMap.put("minTrailingAboveDelta", minTrailingAboveDeltaValueAsString);
        }
        Long maxTrailingAboveDeltaValue = getMaxTrailingAboveDelta();
        if (maxTrailingAboveDeltaValue != null) {
            String maxTrailingAboveDeltaValueAsString = maxTrailingAboveDeltaValue.toString();
            valMap.put("maxTrailingAboveDelta", maxTrailingAboveDeltaValueAsString);
        }
        Long minTrailingBelowDeltaValue = getMinTrailingBelowDelta();
        if (minTrailingBelowDeltaValue != null) {
            String minTrailingBelowDeltaValueAsString = minTrailingBelowDeltaValue.toString();
            valMap.put("minTrailingBelowDelta", minTrailingBelowDeltaValueAsString);
        }
        Long maxTrailingBelowDeltaValue = getMaxTrailingBelowDelta();
        if (maxTrailingBelowDeltaValue != null) {
            String maxTrailingBelowDeltaValueAsString = maxTrailingBelowDeltaValue.toString();
            valMap.put("maxTrailingBelowDelta", maxTrailingBelowDeltaValueAsString);
        }

        valMap.put("timestamp", getTimestamp());
        return asciiEncode(
                valMap.keySet().stream()
                        .map(key -> key + "=" + valMap.get(key))
                        .collect(Collectors.joining("&")));
    }

    public static String asciiEncode(String s) {
        return new String(s.getBytes(), StandardCharsets.US_ASCII);
    }

}
