/*
 * Binance Spot WebSocket API
 * OpenAPI Specifications for the Binance Spot WebSocket API  API documents:   - [Github web-socket-api documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-api.md)   - [General API information for web-socket-api on website](https://developers.binance.com/docs/binance-spot-api-docs/web-socket-api/general-api-information)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.quarkus.spot.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.stream.Collectors;

public class UiKlinesRequest extends BaseDTO {
    public static final String SERIALIZED_NAME_SYMBOL = "symbol";

    @JsonProperty(SERIALIZED_NAME_SYMBOL)
    
    private String symbol;

    public static final String SERIALIZED_NAME_INTERVAL = "interval";

    @JsonProperty(SERIALIZED_NAME_INTERVAL)
    
    private Interval interval;

    public static final String SERIALIZED_NAME_START_TIME = "startTime";

    @JsonProperty(SERIALIZED_NAME_START_TIME)
    
    private Long startTime;

    public static final String SERIALIZED_NAME_END_TIME = "endTime";

    @JsonProperty(SERIALIZED_NAME_END_TIME)
    
    private Long endTime;

    public static final String SERIALIZED_NAME_TIME_ZONE = "timeZone";

    @JsonProperty(SERIALIZED_NAME_TIME_ZONE)
    
    private String timeZone;

    public static final String SERIALIZED_NAME_LIMIT = "limit";

    @JsonProperty(SERIALIZED_NAME_LIMIT)
    
    private Integer limit;

    public UiKlinesRequest() {}

    public UiKlinesRequest symbol( String symbol) {
        this.symbol = symbol;
        return this;
    }

    /**
     * Get symbol
     *
     * @return symbol
     */
    
    
    public String getSymbol() {
        return symbol;
    }

    public void setSymbol( String symbol) {
        this.symbol = symbol;
    }

    public UiKlinesRequest interval( Interval interval) {
        this.interval = interval;
        return this;
    }

    /**
     * Get interval
     *
     * @return interval
     */
    
    
    
    public Interval getInterval() {
        return interval;
    }

    public void setInterval( Interval interval) {
        this.interval = interval;
    }

    public UiKlinesRequest startTime( Long startTime) {
        this.startTime = startTime;
        return this;
    }

    /**
     * Get startTime
     *
     * @return startTime
     */
    
    public Long getStartTime() {
        return startTime;
    }

    public void setStartTime( Long startTime) {
        this.startTime = startTime;
    }

    public UiKlinesRequest endTime( Long endTime) {
        this.endTime = endTime;
        return this;
    }

    /**
     * Get endTime
     *
     * @return endTime
     */
    
    public Long getEndTime() {
        return endTime;
    }

    public void setEndTime( Long endTime) {
        this.endTime = endTime;
    }

    public UiKlinesRequest timeZone( String timeZone) {
        this.timeZone = timeZone;
        return this;
    }

    /**
     * Get timeZone
     *
     * @return timeZone
     */
    
    public String getTimeZone() {
        return timeZone;
    }

    public void setTimeZone( String timeZone) {
        this.timeZone = timeZone;
    }

    public UiKlinesRequest limit( Integer limit) {
        this.limit = limit;
        return this;
    }

    /**
     * Get limit
     *
     * @return limit
     */
    
    public Integer getLimit() {
        return limit;
    }

    public void setLimit( Integer limit) {
        this.limit = limit;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UiKlinesRequest uiKlinesRequest = (UiKlinesRequest) o;
        return Objects.equals(this.symbol, uiKlinesRequest.symbol)
                && Objects.equals(this.interval, uiKlinesRequest.interval)
                && Objects.equals(this.startTime, uiKlinesRequest.startTime)
                && Objects.equals(this.endTime, uiKlinesRequest.endTime)
                && Objects.equals(this.timeZone, uiKlinesRequest.timeZone)
                && Objects.equals(this.limit, uiKlinesRequest.limit);
    }

    @Override
    public int hashCode() {
        return Objects.hash(symbol, interval, startTime, endTime, timeZone, limit);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class UiKlinesRequest {\n");
        sb.append("		symbol: ").append(toIndentedString(symbol)).append("\n");
        sb.append("		interval: ").append(toIndentedString(interval)).append("\n");
        sb.append("		startTime: ").append(toIndentedString(startTime)).append("\n");
        sb.append("		endTime: ").append(toIndentedString(endTime)).append("\n");
        sb.append("		timeZone: ").append(toIndentedString(timeZone)).append("\n");
        sb.append("		limit: ").append(toIndentedString(limit)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();
        Map<String, String> valMap = new TreeMap<String, String>();
        valMap.put("apiKey", getApiKey());
        String symbolValue = getSymbol();
        if (symbolValue != null) {
            String symbolValueAsString = symbolValue.toString();
            valMap.put("symbol", symbolValueAsString);
        }
        Interval intervalValue = getInterval();
        if (intervalValue != null) {
            String intervalValueAsString = intervalValue.toString();
            valMap.put("interval", intervalValueAsString);
        }
        Long startTimeValue = getStartTime();
        if (startTimeValue != null) {
            String startTimeValueAsString = startTimeValue.toString();
            valMap.put("startTime", startTimeValueAsString);
        }
        Long endTimeValue = getEndTime();
        if (endTimeValue != null) {
            String endTimeValueAsString = endTimeValue.toString();
            valMap.put("endTime", endTimeValueAsString);
        }
        String timeZoneValue = getTimeZone();
        if (timeZoneValue != null) {
            String timeZoneValueAsString = timeZoneValue.toString();
            valMap.put("timeZone", timeZoneValueAsString);
        }
        Integer limitValue = getLimit();
        if (limitValue != null) {
            String limitValueAsString = limitValue.toString();
            valMap.put("limit", limitValueAsString);
        }

        valMap.put("timestamp", getTimestamp());
        return asciiEncode(
                valMap.keySet().stream()
                        .map(key -> key + "=" + valMap.get(key))
                        .collect(Collectors.joining("&")));
    }

    public Map<String, Object> toMap() {
        Map<String, Object> valMap = new TreeMap<String, Object>();
        valMap.put("apiKey", getApiKey());
        Object symbolValue = getSymbol();
        if (symbolValue != null) {
            valMap.put("symbol", symbolValue);
        }
        Object intervalValue = getInterval();
        if (intervalValue != null) {
            valMap.put("interval", intervalValue);
        }
        Object startTimeValue = getStartTime();
        if (startTimeValue != null) {
            valMap.put("startTime", startTimeValue);
        }
        Object endTimeValue = getEndTime();
        if (endTimeValue != null) {
            valMap.put("endTime", endTimeValue);
        }
        Object timeZoneValue = getTimeZone();
        if (timeZoneValue != null) {
            valMap.put("timeZone", timeZoneValue);
        }
        Object limitValue = getLimit();
        if (limitValue != null) {
            valMap.put("limit", limitValue);
        }

        valMap.put("timestamp", getTimestamp());
        return valMap;
    }

    public static String asciiEncode(String s) {
        return new String(s.getBytes(), StandardCharsets.US_ASCII);
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n		");
    }

}
