/*
 * Binance Spot WebSocket Streams
 * OpenAPI Specifications for the Binance Spot WebSocket Streams  API documents:   - [Github web-socket-streams documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-streams.md)   - [General API information for web-socket-streams on website](https://developers.binance.com/docs/binance-spot-api-docs/web-socket-streams)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.client.spot.websocket.stream;

import com.binance.connector.client.common.DecimalFormatter;
import com.binance.connector.client.common.websocket.service.DeserializeExclusionStrategy;
import com.binance.connector.client.common.websocket.service.SerializeExclusionStrategy;
import com.binance.connector.client.spot.websocket.model.*;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonElement;
import com.google.gson.JsonParseException;
import com.google.gson.JsonPrimitive;
import com.google.gson.JsonSerializer;
import com.google.gson.TypeAdapter;
import com.google.gson.internal.bind.util.ISO8601Utils;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.io.StringReader;
import java.lang.reflect.Type;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.ParsePosition;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;


/*
 * A JSON utility class
 *
 * NOTE: in the future, this class may be converted to static, which may break
 *       backward-compatibility
 */
public class JSON {
    private static Gson gson;
    private static boolean isLenientOnJson = false;
    private static DateTypeAdapter dateTypeAdapter = new DateTypeAdapter();
    private static SqlDateTypeAdapter sqlDateTypeAdapter = new SqlDateTypeAdapter();
    private static OffsetDateTimeTypeAdapter offsetDateTimeTypeAdapter =
            new OffsetDateTimeTypeAdapter();
    private static LocalDateTypeAdapter localDateTypeAdapter = new LocalDateTypeAdapter();
    private static ByteArrayAdapter byteArrayAdapter = new ByteArrayAdapter();

    @SuppressWarnings("unchecked")
    public static GsonBuilder createGson() {
        GsonFireBuilder fireBuilder =
            new GsonFireBuilder()
                .registerTypeSelector(
                    AssetFilters.class,
                    new TypeSelector<AssetFilters>() {
                        @Override
                        public Class<? extends AssetFilters> getClassForElement(JsonElement readElement) {
                            Map<String, Class> classByDiscriminatorValue =new HashMap<String, Class>();
                            classByDiscriminatorValue.put("MAX_ASSET",MaxAssetFilter.class);
                            classByDiscriminatorValue.put("MaxAssetFilter",MaxAssetFilter.class);
                            classByDiscriminatorValue.put("assetFilters",AssetFilters.class);
                            return getClassByDiscriminator(classByDiscriminatorValue,getDiscriminatorValue(readElement, "filterType"));
                        }
                    })
                .registerTypeSelector(
                    ExchangeFilters.class,
                    new TypeSelector<ExchangeFilters>() {
                        @Override
                        public Class<? extends ExchangeFilters> getClassForElement(JsonElement readElement) {
                            Map<String, Class> classByDiscriminatorValue = new HashMap<String, Class>();
                            classByDiscriminatorValue.put("EXCHANGE_MAX_NUM_ALGO_ORDERS",ExchangeMaxNumAlgoOrdersFilter.class);
                            classByDiscriminatorValue.put("EXCHANGE_MAX_NUM_ICEBERG_ORDERS",ExchangeMaxNumIcebergOrdersFilter.class);
                            classByDiscriminatorValue.put("EXCHANGE_MAX_NUM_ORDERS",ExchangeMaxNumOrdersFilter.class);
                            classByDiscriminatorValue.put("EXCHANGE_MAX_NUM_ORDER_LISTS",ExchangeMaxNumOrderListsFilter.class);
                            classByDiscriminatorValue.put("ExchangeMaxNumAlgoOrdersFilter",ExchangeMaxNumAlgoOrdersFilter.class);
                            classByDiscriminatorValue.put("ExchangeMaxNumIcebergOrdersFilter",ExchangeMaxNumIcebergOrdersFilter.class);
                            classByDiscriminatorValue.put("ExchangeMaxNumOrderListsFilter",ExchangeMaxNumOrderListsFilter.class);
                            classByDiscriminatorValue.put("ExchangeMaxNumOrdersFilter",ExchangeMaxNumOrdersFilter.class);
                            classByDiscriminatorValue.put("exchangeFilters",ExchangeFilters.class);
                            return getClassByDiscriminator(classByDiscriminatorValue,getDiscriminatorValue(readElement, "filterType"));
                        }
                    })
                .registerTypeSelector(
                    SymbolFilters.class,
                    new TypeSelector<SymbolFilters>() {
                        @Override
                        public Class<? extends SymbolFilters> getClassForElement(JsonElement readElement) {
                            Map<String, Class> classByDiscriminatorValue =new HashMap<String, Class>();
                            classByDiscriminatorValue.put("ICEBERG_PARTS",IcebergPartsFilter.class);
                            classByDiscriminatorValue.put("LOT_SIZE",LotSizeFilter.class);
                            classByDiscriminatorValue.put("MARKET_LOT_SIZE",MarketLotSizeFilter.class);
                            classByDiscriminatorValue.put("MAX_NUM_ALGO_ORDERS",MaxNumAlgoOrdersFilter.class);
                            classByDiscriminatorValue.put("MAX_NUM_ICEBERG_ORDERS",MaxNumIcebergOrdersFilter.class);
                            classByDiscriminatorValue.put("MAX_NUM_ORDERS",MaxNumOrdersFilter.class);
                            classByDiscriminatorValue.put("MAX_NUM_ORDER_AMENDS",MaxNumOrderAmendsFilter.class);
                            classByDiscriminatorValue.put("MAX_NUM_ORDER_LISTS",MaxNumOrderListsFilter.class);
                            classByDiscriminatorValue.put("MAX_POSITION",MaxPositionFilter.class);
                            classByDiscriminatorValue.put("MIN_NOTIONAL",MinNotionalFilter.class);
                            classByDiscriminatorValue.put("NOTIONAL",NotionalFilter.class);
                            classByDiscriminatorValue.put("PERCENT_PRICE",PercentPriceFilter.class);
                            classByDiscriminatorValue.put("PERCENT_PRICE_BY_SIDE",PercentPriceBySideFilter.class);
                            classByDiscriminatorValue.put("PRICE_FILTER",PriceFilter.class);
                            classByDiscriminatorValue.put("TRAILING_DELTA",TrailingDeltaFilter.class);
                            classByDiscriminatorValue.put("T_PLUS_SELL",TPlusSellFilter.class);
                            classByDiscriminatorValue.put("IcebergPartsFilter",IcebergPartsFilter.class);
                            classByDiscriminatorValue.put("LotSizeFilter",LotSizeFilter.class);
                            classByDiscriminatorValue.put("MarketLotSizeFilter",MarketLotSizeFilter.class);
                            classByDiscriminatorValue.put("MaxNumAlgoOrdersFilter",MaxNumAlgoOrdersFilter.class);
                            classByDiscriminatorValue.put("MaxNumIcebergOrdersFilter",MaxNumIcebergOrdersFilter.class);
                            classByDiscriminatorValue.put("MaxNumOrderAmendsFilter",MaxNumOrderAmendsFilter.class);
                            classByDiscriminatorValue.put("MaxNumOrderListsFilter",MaxNumOrderListsFilter.class);
                            classByDiscriminatorValue.put("MaxNumOrdersFilter",MaxNumOrdersFilter.class);
                            classByDiscriminatorValue.put("MaxPositionFilter",MaxPositionFilter.class);
                            classByDiscriminatorValue.put("MinNotionalFilter",MinNotionalFilter.class);
                            classByDiscriminatorValue.put("NotionalFilter",NotionalFilter.class);
                            classByDiscriminatorValue.put("PercentPriceBySideFilter",PercentPriceBySideFilter.class);
                            classByDiscriminatorValue.put("PercentPriceFilter",PercentPriceFilter.class);
                            classByDiscriminatorValue.put("PriceFilter",PriceFilter.class);
                            classByDiscriminatorValue.put("TPlusSellFilter",TPlusSellFilter.class);
                            classByDiscriminatorValue.put("TrailingDeltaFilter",TrailingDeltaFilter.class);
                            classByDiscriminatorValue.put("symbolFilters",SymbolFilters.class);
                            return getClassByDiscriminator(classByDiscriminatorValue,getDiscriminatorValue(readElement, "filterType"));
                        }
                    });
        GsonBuilder builder = fireBuilder.createGsonBuilder();
        return builder;
    }
    private static String getDiscriminatorValue(
            JsonElement readElement, String discriminatorField) {
        JsonElement element = readElement.getAsJsonObject().get(discriminatorField);
        if (null == element) {
            throw new IllegalArgumentException(
                    "missing discriminator field: <" + discriminatorField + ">");
        }
        return element.getAsString();
    }

    /**
     * Returns the Java class that implements the OpenAPI schema for the specified discriminator
     * value.
     *
     * @param classByDiscriminatorValue The map of discriminator values to Java classes.
     * @param discriminatorValue The value of the OpenAPI discriminator in the input data.
     * @return The Java class that implements the OpenAPI schema
     */
    private static Class getClassByDiscriminator(
            Map classByDiscriminatorValue, String discriminatorValue) {
        Class clazz = (Class) classByDiscriminatorValue.get(discriminatorValue);
        if (null == clazz) {
            throw new IllegalArgumentException(
                    "cannot determine model class of name: <" + discriminatorValue + ">");
        }
        return clazz;
    }

    static {
        GsonBuilder gsonBuilder = createGson();
        gsonBuilder
                .registerTypeAdapter(
                        Double.class,
                        (JsonSerializer<Double>)
                                (src, typeOfSrc, context) -> {
                                    DecimalFormat df = DecimalFormatter.getFormatter();
                                    return new JsonPrimitive(df.format(src));
                                })
                .addSerializationExclusionStrategy(new SerializeExclusionStrategy())
                .addDeserializationExclusionStrategy(new DeserializeExclusionStrategy());
        gsonBuilder.registerTypeAdapter(Date.class, dateTypeAdapter);
        gsonBuilder.registerTypeAdapter(java.sql.Date.class, sqlDateTypeAdapter);
        gsonBuilder.registerTypeAdapter(OffsetDateTime.class, offsetDateTimeTypeAdapter);
        gsonBuilder.registerTypeAdapter(LocalDate.class, localDateTypeAdapter);
        gsonBuilder.registerTypeAdapter(byte[].class, byteArrayAdapter);
        gsonBuilder.registerTypeAdapterFactory(new AggTradeRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new AggTradeResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new AllMarketRollingWindowTickerRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new AllMarketRollingWindowTickerResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new AllMarketRollingWindowTickerResponseInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new AllMiniTickerResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new AllMiniTickerResponseInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new AllTickerResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new AllTickerResponseInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new AssetFilters.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new AvgPriceRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new AvgPriceResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new BookTickerRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new BookTickerResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new DiffBookDepthRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new DiffBookDepthResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ExchangeFilters.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(
                new ExchangeMaxNumAlgoOrdersFilter.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(
                new ExchangeMaxNumIcebergOrdersFilter.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(
                new ExchangeMaxNumOrderListsFilter.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(
                new ExchangeMaxNumOrdersFilter.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(
                new IcebergPartsFilter.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(
                new KlineOffsetRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(
                new KlineOffsetResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(
                new KlineRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(
                new KlineResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(
                new KlineResponseK.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(
                new LotSizeFilter.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(
                new MarketLotSizeFilter.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(
                new MaxAssetFilter.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(
                new MaxNumAlgoOrdersFilter.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(
                new MaxNumIcebergOrdersFilter.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(
                new MaxNumOrderAmendsFilter.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(
                new MaxNumOrderListsFilter.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(
                new MaxNumOrdersFilter.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(
                new MaxPositionFilter.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(
                new MinNotionalFilter.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(
                new MiniTickerRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(
                new MiniTickerResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(
                new NotionalFilter.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(
                new PartialBookDepthRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(
                new PartialBookDepthResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(
                new PercentPriceBySideFilter.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(
                new PercentPriceFilter.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(
                new PriceFilter.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(
                new RateLimits.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(
                new RollingWindowTickerRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(
                new RollingWindowTickerResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(
                new SymbolFilters.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(
                new TPlusSellFilter.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(
                new TickerRequestStream.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(
                new TickerResponseStream.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(
                new TradeRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(
                new TradeResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(
                new TrailingDeltaFilter.CustomTypeAdapterFactory());
        gson = gsonBuilder.create();
    }

    /**
     * Get Gson.
     *
     * @return Gson
     */
    public static Gson getGson() {
        return gson;
    }

    /**
     * Set Gson.
     *
     * @param gson Gson
     */
    public static void setGson(Gson gson) {
        JSON.gson = gson;
    }

    public static void setLenientOnJson(boolean lenientOnJson) {
        isLenientOnJson = lenientOnJson;
    }

    /**
     * Serialize the given Java object into JSON string.
     *
     * @param obj Object
     * @return String representation of the JSON
     */
    public static String serialize(Object obj) {
        return gson.toJson(obj);
    }

    /**
     * Deserialize the given JSON string to Java object.
     *
     * @param <T> Type
     * @param body The JSON string
     * @param returnType The type to deserialize into
     * @return The deserialized Java object
     */
    @SuppressWarnings("unchecked")
    public static <T> T deserialize(String body, Type returnType) {
        try {
            if (isLenientOnJson) {
                JsonReader jsonReader = new JsonReader(new StringReader(body));
                // see
                // https://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/stream/JsonReader.html#setLenient(boolean)
                jsonReader.setLenient(true);
                return gson.fromJson(jsonReader, returnType);
            } else {
                return gson.fromJson(body, returnType);
            }
        } catch (JsonParseException e) {
            // Fallback processing when failed to parse JSON form response body:
            // return the response body string directly for the String return type;
            if (returnType.equals(String.class)) {
                return (T) body;
            } else {
                throw (e);
            }
        }
    }

    /** Gson TypeAdapter for Byte Array type */
    public static class ByteArrayAdapter extends TypeAdapter<byte[]> {

        @Override
        public void write(JsonWriter out, byte[] value) throws IOException {
            if (value == null) {
                out.nullValue();
            } else {
                out.value(ByteString.of(value).base64());
            }
        }

        @Override
        public byte[] read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String bytesAsBase64 = in.nextString();
                    ByteString byteString = ByteString.decodeBase64(bytesAsBase64);
                    return byteString.toByteArray();
            }
        }
    }

    /** Gson TypeAdapter for JSR310 OffsetDateTime type */
    public static class OffsetDateTimeTypeAdapter extends TypeAdapter<OffsetDateTime> {

        private DateTimeFormatter formatter;

        public OffsetDateTimeTypeAdapter() {
            this(DateTimeFormatter.ISO_OFFSET_DATE_TIME);
        }

        public OffsetDateTimeTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, OffsetDateTime date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public OffsetDateTime read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    if (date.endsWith("+0000")) {
                        date = date.substring(0, date.length() - 5) + "Z";
                    }
                    return OffsetDateTime.parse(date, formatter);
            }
        }
    }

    /** Gson TypeAdapter for JSR310 LocalDate type */
    public static class LocalDateTypeAdapter extends TypeAdapter<LocalDate> {

        private DateTimeFormatter formatter;

        public LocalDateTypeAdapter() {
            this(DateTimeFormatter.ISO_LOCAL_DATE);
        }

        public LocalDateTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, LocalDate date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public LocalDate read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    return LocalDate.parse(date, formatter);
            }
        }
    }

    public static void setOffsetDateTimeFormat(DateTimeFormatter dateFormat) {
        offsetDateTimeTypeAdapter.setFormat(dateFormat);
    }

    public static void setLocalDateFormat(DateTimeFormatter dateFormat) {
        localDateTypeAdapter.setFormat(dateFormat);
    }

    /**
     * Gson TypeAdapter for java.sql.Date type If the dateFormat is null, a simple "yyyy-MM-dd"
     * format will be used (more efficient than SimpleDateFormat).
     */
    public static class SqlDateTypeAdapter extends TypeAdapter<java.sql.Date> {

        private DateFormat dateFormat;

        public SqlDateTypeAdapter() {}

        public SqlDateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, java.sql.Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = date.toString();
                }
                out.value(value);
            }
        }

        @Override
        public java.sql.Date read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    try {
                        if (dateFormat != null) {
                            return new java.sql.Date(dateFormat.parse(date).getTime());
                        }
                        return new java.sql.Date(
                                ISO8601Utils.parse(date, new ParsePosition(0)).getTime());
                    } catch (ParseException e) {
                        throw new JsonParseException(e);
                    }
            }
        }
    }

    /**
     * Gson TypeAdapter for java.util.Date type If the dateFormat is null, ISO8601Utils will be
     * used.
     */
    public static class DateTypeAdapter extends TypeAdapter<Date> {

        private DateFormat dateFormat;

        public DateTypeAdapter() {}

        public DateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = ISO8601Utils.format(date, true);
                }
                out.value(value);
            }
        }

        @Override
        public Date read(JsonReader in) throws IOException {
            try {
                switch (in.peek()) {
                    case NULL:
                        in.nextNull();
                        return null;
                    default:
                        String date = in.nextString();
                        try {
                            if (dateFormat != null) {
                                return dateFormat.parse(date);
                            }
                            return ISO8601Utils.parse(date, new ParsePosition(0));
                        } catch (ParseException e) {
                            throw new JsonParseException(e);
                        }
                }
            } catch (IllegalArgumentException e) {
                throw new JsonParseException(e);
            }
        }
    }

    public static void setDateFormat(DateFormat dateFormat) {
        dateTypeAdapter.setFormat(dateFormat);
    }

    public static void setSqlDateFormat(DateFormat dateFormat) {
        sqlDateTypeAdapter.setFormat(dateFormat);
    }
}
